### ISSUE TITLE
node-inspector installation (Error)

### ISSUE THREAD

**Issue by sterrly** [node-inspector/node-inspector#1013]
Got some trouble on installing node-inspector

```
node -v && npm -v
v8.1.3
5.0.3
```

```
gyp ERR! cwd /usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler
gyp ERR! node -v v8.1.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler@5.7.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler@5.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Djamal/.npm/_logs/2017-07-06T21_14_29_065Z-debug.log
```

**Comment by zhijunzhou** [comment]
os: windows 10
I've got the same error after upgrade node to v8.1.3. And the details like that:
```shell
C:\xxx>npm install -g node-inspector

> v8-profiler@5.7.0 preinstall C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler
> node -e 'process.exit(0)'


> v8-debug@1.0.1 preinstall C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug
> node -e 'process.exit(0)'

C:\Users\xxx\AppData\Roaming\npm\node-debug -> C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\bin\node-debug.js
C:\Users\xxx\AppData\Roaming\npm\node-inspector -> C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\bin\inspector.js

> v8-profiler@5.7.0 install C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.7.0 and node@8.1.3 (node-v57 ABI) (falling back to source compile with node-gyp)

C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.7.0\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.7.0\node-v57-win32-x64 )  else (node "" configure --fallback-to-build --module=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.7.0\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.7.0\node-v57-win32-x64 )

C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.7.0\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.7.0\node-v57-win32-x64 )  else (node "" build --fallback-to-build --module=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.7.0\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.7.0\node-v57-win32-x64 )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framew
ork 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it i
s installed elsewhere.  [C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build
\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\v8-profiler\\build\\profiler\\v5.7.0\\node-v57-win32-x64\\profiler.node" "--module_name=profiler" "--module_path=C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\v8-profiler\\build\\profiler\\v5.7.0\\node-v57-win32-x64"
gyp ERR! cwd C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler
gyp ERR! node -v v8.1.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.7.0\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.7.0\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:897:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler
node-pre-gyp ERR! node -v v8.1.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.7.0\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.7.0\node-v57-win32-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler@5.7.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler@5.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by sterrly** [comment]
You should definitely download and install the current version which is recommended for most users (6.11.1 LTS) 
It worked for me, I really think the 8th version is too recent for node-inspector

**Comment by mrhammadasif** [comment]
I am also using v8.1.4 & getting this error

`> v8-profiler@5.7.0 preinstall /usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler
> node -e 'process.exit(0)'


> v8-debug@1.0.1 preinstall /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug
> node -e 'process.exit(0)'

/usr/local/bin/node-debug -> /usr/local/lib/node_modules/node-inspector/bin/node-debug.js
/usr/local/bin/node-inspector -> /usr/local/lib/node_modules/node-inspector/bin/inspector.js

> v8-debug@1.0.1 install /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@8.1.3 (node-v57 ABI) (falling back to source compile with node-gyp)
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc:41:20: warning: 'Call' is deprecated
      [-Wdeprecated-declarations]
        v8::Debug::Call(context, fn);
                   ^
/Users/hammadasif/.node-gyp/8.1.3/include/node/v8-debug.h:193:42: note:
      'Call' has been explicitly marked deprecated here
                static MaybeLocal<Value> Call(
                                         ^
../src/debug.cc:52:45: warning: 'GetDebugContext' is deprecated
      [-Wdeprecated-declarations]
        Isolate* debug_isolate = v8::Debug::GetDebugContext(Isolate::G...
                                            ^
/Users/hammadasif/.node-gyp/8.1.3/include/node/v8-debug.h:209:39: note:
      'GetDebugContext' has been explicitly marked deprecated here
                static Local<Context> GetDebugContext(Isolate* isolate));
                                      ^
../src/debug.cc:57:20: warning: 'SendCommand' is deprecated
      [-Wdeprecated-declarations]
        v8::Debug::SendCommand(debug_isolate, *command, command.length());
                   ^
/Users/hammadasif/.node-gyp/8.1.3/include/node/v8-debug.h:170:29: note:
      'SendCommand' has been explicitly marked deprecated here
                static void SendCommand(Isolate* isolate,
                            ^
../src/debug.cc:71:51: warning: 'GetDebugContext' is deprecated
      [-Wdeprecated-declarations]
        Local<Context> debug_context = v8::Debug::GetDebugContext(Isol...
                                                  ^
/Users/hammadasif/.node-gyp/8.1.3/include/node/v8-debug.h:209:39: note:
      'GetDebugContext' has been explicitly marked deprecated here
                static Local<Context> GetDebugContext(Isolate* isolate));
                                      ^
../src/debug.cc:78:22: error: no member named 'GetMirror' in 'v8::Debug'
          v8::Debug::GetMirror(info.GetIsolate()->GetCurrentContext()...
          ~~~~~~~~~~~^
../src/debug.cc:80:38: warning: 'GetDebugContext' is deprecated
      [-Wdeprecated-declarations]
          debug_context = v8::Debug::GetDebugContext(Isolate::GetCurrent());
                                     ^
/Users/hammadasif/.node-gyp/8.1.3/include/node/v8-debug.h:209:39: note:
      'GetDebugContext' has been explicitly marked deprecated here
                static Local<Context> GetDebugContext(Isolate* isolate));
                                      ^
5 warnings and 1 error generated.
make: *** [Release/obj.target/debug/src/debug.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/usr/local/Cellar/node/8.1.3/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64/debug.node" "--module_name=debug" "--module_path=/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64"
gyp ERR! cwd /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug
gyp ERR! node -v v8.1.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/8.1.3/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64/debug.node --module_name=debug --module_path=/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/node-inspector/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:897:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
node-pre-gyp ERR! System Darwin 16.6.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/8.1.3/bin/node" "/usr/local/lib/node_modules/node-inspector/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug
node-pre-gyp ERR! node -v v8.1.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/8.1.3/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64/debug.node --module_name=debug --module_path=/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-debug@1.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by tpae** [comment]
@mrhammadasif I was having the same issue and I found this: #1010 

Hope it helps

**Comment by frank198** [comment]
root@frank ~# npm i -g node-inspector --registry=https://registry.npm.taobao.org


> v8-profiler@5.7.0 preinstall /usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler
> node -e 'process.exit(0)'

npm ERR! Cannot read property 'pause' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-20T10_16_24_176Z-debug.log


4830 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "node-inspector" "--registry=https://registry.npm.taobao.org"
4831 verbose node v8.5.0
4832 verbose npm  v5.4.2
4833 error Cannot read property 'pause' of undefined
4834 verbose exit [ 1, true ]

**Comment by jettangs** [comment]
I got the same error, hope it solved in official way.

**Comment by PINK-FL0YD** [comment]
What the fuck???
Before solving this most fundamental problem, how many issues should we submit?
Developers mental retardation yet?

**Comment by YouShengBS** [comment]
What the fuck???
Before solving this most fundamental problem, how many issues should we submit?
Developers mental retardation yet?

**Comment by mwcz** [comment]
I think @YouShengBS is volunteering to fix this. :baggage_claim:

**Comment by dongalor** [comment]
```
nvm install 6.1.0
nvm use 6.1.0
npm install -g node-inspector
```
