### ISSUE TITLE
Cannot find module '_debugger'

### ISSUE THREAD

**Issue by ClearLoving** [node-inspector/node-inspector#1025]
when I run "node-inspector --web-port 8080 --debug-port 5858", the terminal shows "Cannot find module '_debugger'",what should I do next?

**Comment by mingjunz** [comment]
got the same issue.
Node: v8.7.0
NPM: 5.3.0
Node Inspector v1.1.1


module.js:529
    throw err;
    ^

Error: Cannot find module '_debugger'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (...\AppData\Roaming\npm\node_modules\node-inspector\lib\debugger.js:2:16)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)

**Comment by wzup** [comment]
Same here. 
Any solution so far?

```
$ ni
module.js:529
    throw err;
    ^

Error: Cannot find module '_debugger'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\node-inspector\lib\debugger.js:2:16)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by hooper-hc** [comment]
![image](https://user-images.githubusercontent.com/11420374/31994250-8afe3f78-b9b2-11e7-94d7-a5b70db37f60.png)

please resolve it. 

node 8.7.0
system: mac.
![image](https://user-images.githubusercontent.com/11420374/31994319-d455dfc8-b9b2-11e7-8eea-47a2a2623b01.png)

**Comment by umartahir5** [comment]
Check the answer here: [https://stackoverflow.com/a/47158883/3573125](url)

**Comment by quant-daddy** [comment]
Still getting the same error for v9.7.1

```
> node --inspect-brk lib/cli.js
> node-inspector // in a different tab
Error: Cannot find module '_debugger'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-inspector/lib/debugger.js:2:16)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
```

**Comment by telomere2018** [comment]
try : sudo npm install debugger
