### ISSUE TITLE
Fresh installation: Cannot find module '_debugger'

### ISSUE THREAD

**Issue by Bizarrus** [node-inspector/node-inspector#1040]
`root@host:/opt/# npm i node-inspector -g
/usr/bin/node-inspector -> /usr/lib/node_modules/node-inspector/bin/inspector.js
/usr/bin/node-debug -> /usr/lib/node_modules/node-inspector/bin/node-debug.js
+ node-inspector@1.1.2
updated 1 package in 6.757s
root@rs-zap340838-1:/opt/chatserver# node-inspector
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '_debugger'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/node-inspector/lib/debugger.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
`

**Comment by zhidelin** [comment]
nodejs only under v8.x can use _debugger
I copy https://github.com/nodejs/node/blob/v7.x/lib/_debugger.js to node-inspector/lib/_debugger.js
In node-insspector/lib/debugger.js: require('_debugger') change to require('./_debugger')
And use 'node --inspect-brk' command
It's OK
