### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by jackletter** [node-inspector/node-inspector#1041]
when i excute the code
`npm install -g node-inspector`
it happens :
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v64-win32-x64.tar.gz

**Comment by kvokka** [comment]
Same with node 8.11.1
```
error /Users/kvokka/proj/bancnl-api/node_modules/v8-debug: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /Users/kvokka/proj/bancnl-api/node_modules/v8-debug
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@8.11.1 | darwin | x64
node-pre-gyp info check checked for "/Users/kvokka/proj/bancnl-api/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64/debug.node" (not found)
node-pre-gyp http GET https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-darwin-x64.tar.gz
node-pre-gyp http 404 https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@8.11.1 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-darwin-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.1 | darwin | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.1 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/kvokka/proj/bancnl-api/node_modules/v8-debug/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/kvokka/.node-gyp/8.11.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/kvokka/.node-gyp/8.11.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/kvokka/.node-gyp/8.11.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/kvokka/proj/bancnl-api/node_modules/v8-debug',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.1 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc:41:20: warning: 'Call' is deprecated [-Wdeprecated-declarations]
        v8::Debug::Call(context, fn);
                   ^
/Users/kvokka/.node-gyp/8.11.1/include/node/v8-debug.h:192:3: note: 'Call' has been explicitly marked deprecated here
  V8_DEPRECATED("No longer supported",
  ^
/Users/kvokka/.node-gyp/8.11.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/debug.cc:52:45: warning: 'GetDebugContext' is deprecated [-Wdeprecated-declarations]
        Isolate* debug_isolate = v8::Debug::GetDebugContext(Isolate::GetCurrent())->GetIsolate();
                                            ^
/Users/kvokka/.node-gyp/8.11.1/include/node/v8-debug.h:208:3: note: 'GetDebugContext' has been explicitly marked deprecated here
  V8_DEPRECATED("Use v8-inspector",
  ^
/Users/kvokka/.node-gyp/8.11.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/debug.cc:57:20: warning: 'SendCommand' is deprecated [-Wdeprecated-declarations]
        v8::Debug::SendCommand(debug_isolate, *command, command.length());
                   ^
/Users/kvokka/.node-gyp/8.11.1/include/node/v8-debug.h:169:3: note: 'SendCommand' has been explicitly marked deprecated here
  V8_DEPRECATED("No longer supported",
  ^
/Users/kvokka/.node-gyp/8.11.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/debug.cc:71:51: warning: 'GetDebugContext' is deprecated [-Wdeprecated-declarations]
        Local<Context> debug_context = v8::Debug::GetDebugContext(Isolate::GetCurrent());
                                                  ^
/Users/kvokka/.node-gyp/8.11.1/include/node/v8-debug.h:208:3: note: 'GetDebugContext' has been explicitly marked deprecated here
  V8_DEPRECATED("Use v8-inspector",
  ^
/Users/kvokka/.node-gyp/8.11.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/debug.cc:78:22: error: no member named 'GetMirror' in 'v8::Debug'
          v8::Debug::GetMirror(info.GetIsolate()->GetCurrentContext(), info[0]);
          ~~~~~~~~~~~^
../src/debug.cc:80:38: warning: 'GetDebugContext' is deprecated [-Wdeprecated-declarations]
          debug_context = v8::Debug::GetDebugContext(Isolate::GetCurrent());
                                     ^
/Users/kvokka/.node-gyp/8.11.1/include/node/v8-debug.h:208:3: note: 'GetDebugContext' has been explicitly marked deprecated here
  V8_DEPRECATED("Use v8-inspector",
  ^
/Users/kvokka/.node-gyp/8.11.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
5 warnings and 1 error generated.
make: *** [Release/obj.target/debug/src/debug.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/kvokka/proj/bancnl-api/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64/debug.node" "--module_name=debug" "--module_path=/Users/kvokka/proj/bancnl-api/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64"
gyp ERR! cwd /Users/kvokka/proj/bancnl-api/node_modules/v8-debug
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/kvokka/proj/bancnl-api/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64/debug.node --module_name=debug --module_path=/Users/kvokka/proj/bancnl-api/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/kvokka/proj/bancnl-api/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Darwin 17.5.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/kvokka/proj/bancnl-api/node_modules/v8-debug/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/kvokka/proj/bancnl-api/node_modules/v8-debug
node-pre-gyp ERR! node -v v8.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
```

**Comment by chucklu** [comment]
I have tried to search the result for https://node-inspector.s3.amazonaws.com/ with the following regular expression `v1.0.1/node-v..-win32-x64.tar.gz`, I got this:
 

>  C:\Users\clu\Desktop\test.xml(1323):  <Key>debug/v1.0.1/node-v11-win32-x64.tar.gz</Key>
>   C:\Users\clu\Desktop\test.xml(1351):  <Key>debug/v1.0.1/node-v14-win32-x64.tar.gz</Key>
>   C:\Users\clu\Desktop\test.xml(1379):  <Key>debug/v1.0.1/node-v46-win32-x64.tar.gz</Key>
>   C:\Users\clu\Desktop\test.xml(1407):  <Key>debug/v1.0.1/node-v47-win32-x64.tar.gz</Key>
>   C:\Users\clu\Desktop\test.xml(1435):  <Key>debug/v1.0.1/node-v48-win32-x64.tar.gz</Key>
>   C:\Users\clu\Desktop\test.xml(1463):  <Key>debug/v1.0.1/node-v51-win32-x64.tar.gz</Key>

There is no v64 but have a v46, maybe a typo in install script.
How do you think? @hustxiaoc

**Comment by chucklu** [comment]
After check the [ReadMe ](https://github.com/node-inspector/node-inspector/blob/master/README.md) document of this repository.
 I find this:

> Since version 6.3, Node.js provides a built-in DevTools-based debugger which mostly deprecates Node Inspector, see e.g. [this blog post](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27#.pmqejrn8q) to get started. The built-in debugger is developed directly by the V8/Chromium team and provides certain advanced features (e.g. long/async stack traces) that are too difficult to implement in Node Inspector.

If you want to debug, you can use the built-in debugger.

**Comment by jackletter** [comment]
thanks @chucklu, I got it

**Comment by chucklu** [comment]
@jackletter  I think you can debug Node.js in vs2017
https://github.com/Microsoft/nodejstools/wiki
https://github.com/Microsoft/nodejstools/wiki/Projects
https://github.com/Microsoft/nodejstools/wiki/Debugging

**Comment by snowman** [comment]
hey, guys, look at here.
1. Install [nvm](https://github.com/creationix/nvm)
2. run command `nvm install 6.2`
3. run command `node install node-inspector`
4. `node-inspector`
