### ISSUE TITLE
internal/modules/cjs/loader.js:589

### ISSUE THREAD

**Issue by shehrozeikram** [node-inspector/node-inspector#1048]

**Comment by benjaminMaine** [comment]
Same problem while restarting my project on a empty new Macbook pro 2018 from a git repo 

```
 node index.js
internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module './helpers/update/applyTimestampsToChildren'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/benjaminmaine/WORKSPACE/book-help-comprehension-translator/node_modules/mongoose/lib/schema.js:11:35)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/benjaminmaine/WORKSPACE/book-help-comprehension-translator/node_modules/mongoose/lib/index.js:13:16)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
error Command failed with exit code 1.
```

**Comment by benjaminMaine** [comment]
Just a problem with my devs configuration keys in my case.
Maybe can find a way with that check il you succeed in accessing your database

**Comment by tuanticker** [comment]
I took the npm folder in the installation directory of nodejs "\node_modules\npm" copy them to "C:\Users\% User%\AppData\Roaming\npm\node_modules\npm " So the problem is solved =))

**Comment by delacruzjames** [comment]
**Try this works on my end.**

* rm -rf  node_modules
* rm package-lock.json
* npm install
* npm start

**Comment by benjaminMaine** [comment]
Thanks a lot @delacruzjames it works with your solution.
Thanks a lot !

**Comment by cbyad** [comment]
These don't work for me. I even reinstalled node

**Comment by Jalever** [comment]
> 
> 
> **Try this works on my end.**
> 
>     * rm -rf  node_modules
> 
>     * rm package-lock.json
> 
>     * npm install
> 
>     * npm start

Thanks a lot. 👍

**Comment by stonedcoder** [comment]
This doesn't work on my end .
* rm -rf  node_modules

* rm package-lock.json

* npm install

* npm start

<img width="1410" alt="Screenshot 2019-05-14 at 12 01 52 pm" src="https://user-images.githubusercontent.com/23911161/57675621-1abba380-7640-11e9-8be9-b052c387fbb4.png">

**Comment by sdr46** [comment]
node index.js 

This gives this error because the file and path cannot be found. It becomes an idea for friends who will experience this problem in the future.
