### ISSUE TITLE
internal/modules/cjs/loader.js:670     throw err;

### ISSUE THREAD

**Issue by 068089dy** [node-inspector/node-inspector#1059]
➜  ~ npm
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)

**Comment by ChaimStanton** [comment]
I have the same problem, have you found any solutions?

**Comment by MusheAbdulHakim** [comment]
I have the same issue here.

**Comment by MusheAbdulHakim** [comment]
I just found the solution for my issue here. 
[https://askubuntu.com/questions/1152570/npm-cant-find-module-semver-error-in-ubuntu-19-04](https://askubuntu.com/questions/1152570/npm-cant-find-module-semver-error-in-ubuntu-19-04)

These solutions on stackoverflow might also help.
[https://stackoverflow.com/questions/33870520/npm-install-cannot-find-module-semver](https://stackoverflow.com/questions/33870520/npm-install-cannot-find-module-semver)
