### ISSUE TITLE
Can't install properly

### ISSUE THREAD

**Issue by MatteoGauthier** [node-inspector/node-inspector#1060]
```bash
npm i -g node-inspector
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

> v8-profiler@5.7.0 preinstall C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-profiler
> node -e 'process.exit(0)'


> v8-debug@1.0.1 preinstall C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-debug
> node -e 'process.exit(0)'

C:\Program Files\nodejs\node-inspector -> C:\Program Files\nodejs\node_modules\node-inspector\bin\inspector.js
C:\Program Files\nodejs\node-debug -> C:\Program Files\nodejs\node_modules\node-inspector\bin\node-debug.js

> v8-debug@1.0.1 install C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@10.16.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@10.16.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! gypconfigure error
 ERR! gypconfigure error
ERR! stack Error: Command failed: C:\Users\Mattaio\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gypgyp  ERR!ERR!  stackstack Error: Command failed: C:\Users\Mattaio\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
   File "<string>", line 1
gypgyp  ERR! ERR!stack    File "<string>", line 1
stackgyp     import sys; print "%s.%s.%s" % sys.version_info[:3];
 gyp ERR!ERR!  stackstack     import sys; print "%s.%s.%s" % sys.version_info[:3];
                                ^
gypgyp  ERR! ERR!stack stack                                ^
gyp SyntaxError: invalid syntax
 gypERR!  ERR!stack  SyntaxError: invalid syntax
stackgyp
ERR!gyp  stackERR!
 gypstack ERR!     at ChildProcess.exithandler (child_process.js:294:12)
 gypstack     at ChildProcess.exithandler (child_process.js:294:12)
 gypERR!  ERR!stack      at ChildProcess.emit (events.js:198:13)
stackgyp     at ChildProcess.emit (events.js:198:13)
 gypERR!  ERR!stack      at maybeClose (internal/child_process.js:982:16)
stack     at maybeClose (internal/child_process.js:982:16)
gypgyp  ERR!ERR!  stackstack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp gypERR!  ERR!System  Windows_NT 10.0.17763
Systemgyp Windows_NT 10.0.17763
 ERR!gyp  commandERR! "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Mattaio\\AppData\\Roaming\\nvm\\v10.16.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Program Files\\nodejs\\node_modules\\node-inspector\\node_modules\\v8-debug\\build\\debug\\v1.0.1\\node-v64-win32-x64\\debug.node" "--module_name=debug" "--module_path=C:\\Program Files\\nodejs\\node_modules\\node-inspector\\node_modules\\v8-debug\\build\\debug\\v1.0.1\\node-v64-win32-x64"
 gyp command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Mattaio\\AppData\\Roaming\\nvm\\v10.16.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Program Files\\nodejs\\node_modules\\node-inspector\\node_modules\\v8-debug\\build\\debug\\v1.0.1\\node-v64-win32-x64\\debug.node" "--module_name=debug" "--module_path=C:\\Program Files\\nodejs\\node_modules\\node-inspector\\node_modules\\v8-debug\\build\\debug\\v1.0.1\\node-v64-win32-x64"
ERR!gyp  cwd C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-debug
ERR!gyp  cwdERR! C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-debug
 gypnode -v  v10.16.0
ERR!gyp  node -vERR! v10.16.0
gyp node-gyp -v  v3.8.0
ERR!gyp  node-gyp -vERR! v3.8.0
 gyp not okERR!
 not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Mattaio\AppData\Roaming\nvm\v10.16.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-debug\build\debug\v1.0.1\node-v64-win32-x64\debug.node --module_name=debug --module_path=C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-debug\build\debug\v1.0.1\node-v64-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Mattaio\AppData\Roaming\nvm\v10.16.0\node_modules\node-inspector\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Windows_NT 10.0.17763
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-inspector\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-debug
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Mattaio\AppData\Roaming\nvm\v10.16.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-debug\build\debug\v1.0.1\node-v64-win32-x64\debug.node --module_name=debug --module_path=C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-debug\build\debug\v1.0.1\node-v64-win32-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-debug@1.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mattaio\AppData\Roaming\npm-cache\_logs\2019-07-20T13_17_15_013Z-debug.log
```

**Comment by davidoskay** [comment]
Same problem..

**Comment by kerosan** [comment]
=( same on mac os

**Comment by kerosan** [comment]
`
> v8-profiler@5.7.0 preinstall /Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/node-inspector/node_modules/v8-profiler
> node -e 'process.exit(0)'


> v8-debug@1.0.1 preinstall /Users//.nvm/versions/node/v10.16.0/lib/node_modules/node-inspector/node_modules/v8-debug
> node -e 'process.exit(0)'

/Users/I/.nvm/versions/node/v10.16.0/bin/node-inspector -> /Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/node-inspector/bin/inspector.js
/Users/I/.nvm/versions/node/v10.16.0/bin/node-debug -> /Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/node-inspector/bin/node-debug.js

> v8-debug@1.0.1 install /Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@10.16.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@10.16.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
  CXX(target) Release/obj.target/debug/src/debug.o
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc../src/debug.cc::11::1010::  fatal errorfatal error: : 'v8-debug.h''v8-debug.h'  filefile  notnot  foundfound

#include <v8-debug.h>#include <v8-debug.h>

         ^~~~~~~~~~~~         ^~~~~~~~~~~~

1 error generated.
1 error generated.
make: *** [Release/obj.target/debug/src/debug.o] Error 1
make: *** [Release/obj.target/debug/src/debug.o] Error 1
gypgyp  ERR!ERR!  build errorbuild error 
 
gypgyp  ERR!ERR!  stackstack Error: `make` failed with exit code: 2
 Error: `make` failed with exit code: 2
gyp gyp ERR! ERR!stack      at ChildProcess.onExit (/Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
stack     at ChildProcess.onExit (/Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gypgyp  ERR!ERR!  stackstack     at ChildProcess.emit (events.js:198:13)
     at ChildProcess.emit (events.js:198:13)
gypgyp  ERR!ERR!  stackstack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gypgyp  ERR!ERR!  SystemSystem Darwin 18.7.0
 Darwin 18.7.0
gyp ERR! command "/Users/I/.nvm/versions/node/v10.16.0/bin/node" "/Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v64-darwin-x64/debug.node" "--module_name=debug" "--module_path=/Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v64-darwin-x64"
gyp gyp ERR! ERR! commandcwd "/Users/I/.nvm/versions/node/v10.16.0/bin/node" "/Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v64-darwin-x64/debug.node" "--module_name=debug" "--module_path=/Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v64-darwin-x64"
 /Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/node-inspector/node_modules/v8-debug
gyp gyp ERR! ERR!node -v  v10.16.0
cwd /Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/node-inspector/node_modules/v8-debug
gyp gyp ERR! ERR!node-gyp -v  v3.8.0
node -v v10.16.0
gyp gyp ERR! ERR!not ok  
node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/I/.nvm/versions/node/v10.16.0/bin/node /Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v64-darwin-x64/debug.node --module_name=debug --module_path=/Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/node-inspector/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/Users/I/.nvm/versions/node/v10.16.0/bin/node" "/Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/node-inspector/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/node-inspector/node_modules/v8-debug
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/Users/I/.nvm/versions/node/v10.16.0/bin/node /Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v64-darwin-x64/debug.node --module_name=debug --module_path=/Users/I/.nvm/versions/node/v10.16.0/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v64-darwin-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-debug@1.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/I/.npm/_logs/2019-08-07T18_38_08_789Z-debug.log
[I@mbp ~/work/nbs-gw (master)]$ 
`

**Comment by gaborluk** [comment]
From the readme:

> **Since version 6.3, Node.js provides a built-in DevTools-based debugger which mostly deprecates Node Inspector, see e.g. [this blog post](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27#.pmqejrn8q) to get started. The built-in debugger is developed directly by the V8/Chromium team and provides certain advanced features (e.g. long/async stack traces) that are too difficult to implement in Node Inspector.**

For Node.js versions `>=6.3` , just use the built-in `node --inspect index.js`, documentation [here](https://nodejs.org/en/docs/guides/debugging-getting-started/).

**Comment by davehowson** [comment]
`node --inspect` does not show network requests though

**Comment by dpetrovaliev** [comment]
Same here!

**Comment by jackkenlay** [comment]
Did anyone find a way to solve this issue?

**Comment by ahmedkhederali** [comment]
same problem

**Comment by furkanalptokac** [comment]
Same problem on macOS and node v14 - v16 both
