### ISSUE TITLE
Can't start node-inspector

### ISSUE THREAD

**Issue by diegovar** [node-inspector/node-inspector#36]
I get the following when trying to run node-inspector

diego@diego-Ubuntu:~/Node.js applications/Blog$ 
events.js:45
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: EADDRINUSE, Address already in use
    at Server._doListen (net.js:1088:5)
    at net.js:1059:14
    at Object.lookup (dns.js:153:45)
    at Server.listen (net.js:1053:20)
    at Server.listen (/usr/local/lib/node/.npm/node-inspector/0.1.6/package/vendor/ws.js:108:22)
    at Object.create (/usr/local/lib/node/.npm/node-inspector/0.1.6/package/lib/debug-server.js:44:12)
    at /usr/local/lib/node/.npm/node-inspector/0.1.6/package/bin/inspector.js:52:11
    at [object Object].<anonymous> (fs.js:107:5)
    at [object Object].emit (events.js:61:17)
    at afterRead (fs.js:903:12)

**Comment by akhilesh009** [comment]
in one shell i fired node --debug-brk app.js  in second   node-inspector --web-port=8989 still giving error  Unhandled 'error' event
