### ISSUE TITLE
Error: listen EADDRINUSE after ~ 10 seconds

### ISSUE THREAD

**Issue by Olgagr** [node-inspector/node-inspector#468]
When I run node-inspector, it runs as expected. It opens new tab in Chrome and stops on first breakpoint. I resume the first breakpoint. After about 10 seconds, the node-inspector stops and throws an error:

```
Node Inspector is now available from http://localhost:8989/debug?port=5858
Debugging `server.js`

debugger listening on port 5858

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1138:5)
    at EventEmitter.app.listen (/Users/ograbek/Documents/learning/node/multi_vision/node_modules/express/lib/application.js:559:24)
    at Object.<anonymous> (/Users/ograbek/Documents/learning/node/multi_vision/server.js:20:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

I've tried different ports, I run for example:

```
node-debug  --web-port=8989 server.js
```

but it didn't help.

**Comment by xiangpenpende** [comment]
I have the same problem. I didn't get the error when running node server.js

**Comment by Nditah** [comment]
I encountered the same problem and after changing my port to another PORT:4000
Voila! Problem solved
