### ISSUE TITLE
Installation on CentOS 6.3

### ISSUE THREAD

**Issue by iJoyCode** [node-inspector/node-inspector#508]
Hello, I've got this error while while trying to install node-inspector on CentOS 6.3:

```
npm i -g node-inspector --unsafe-perm

> ws@0.4.32 install /usr/local/node/node-v0.10.35/lib/node_modules/node-inspecto                                                                                                                                                             r/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/ws/build'

> v8-profiler@5.2.1 install /usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

Traceback (most recent call last):
  File "/usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 534, in script_main
    return main(sys.argv[1:])
  File "/usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 527, in main
    return gyp_main(args)
  File "/usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 503, in gyp_main
    options.circular_check)
  File "/usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File "/usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2692, in Load
    variables, includes, depth, check, True)
  File "/usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 362, in LoadTargetBuildFile
    includes, True, check)
  File "/usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 219, in LoadOneBuildFile
    None)
  File "binding.gyp", line 1
    {
     ^
SyntaxError: invalid syntax
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-358.el6.x86_64
gyp ERR! command "/usr/local/node/node-v0.10.35/bin/node" "/usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=v8-profiler" "--configuration=Release" "--module_name=profiler" "--version=5.2.1" "--major=5" "--minor=2" "--patch=1" "--runtime=node" "--node_abi=node-v11" "--platform=linux" "--target_platform=linux" "--arch=x64" "--target_arch=x64" "--module_main=v8-profiler" "--host=https://node-inspector.s3.amazonaws.com/" "--module_path=/usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.1/node-v11-linux-x64" "--module=/usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.1/node-v11-linux-x64/profiler.node" "--remote_path=./profiler/v5.2.1/" "--package_name=node-v11-linux-x64.tar.gz" "--staged_tarball=build/stage/profiler/v5.2.1/node-v11-linux-x64.tar.gz" "--hosted_path=https://node-inspector.s3.amazonaws.com/profiler/v5.2.1/" "--hosted_tarball=https://node-inspector.s3.amazonaws.com/profiler/v5.2.1/node-v11-linux-x64.tar.gz"
gyp ERR! cwd /usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/v8-profiler
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/node/node-v0.10.35/bin/node /usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=v8-profiler --configuration=Release --module_name=profiler --version=5.2.1 --major=5 --minor=2 --patch=1 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=v8-profiler --host=https://node-inspector.s3.amazonaws.com/ --module_path=/usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.1/node-v11-linux-x64 --module=/usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.1/node-v11-linux-x64/profiler.node --remote_path=./profiler/v5.2.1/ --package_name=node-v11-linux-x64.tar.gz --staged_tarball=build/stage/profiler/v5.2.1/node-v11-linux-x64.tar.gz --hosted_path=https://node-inspector.s3.amazonaws.com/profiler/v5.2.1/ --hosted_tarball=https://node-inspector.s3.amazonaws.com/profiler/v5.2.1/node-v11-linux-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/v8-profiler/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 2.6.32-358.el6.x86_64
node-pre-gyp ERR! command "node" "/usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/v8-profiler/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/v8-profiler
node-pre-gyp ERR! node -v v0.10.35
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/node/node-v0.10.35/bin/node /usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=v8-profiler --configuration=Release --module_name=profiler --version=5.2.1 --major=5 --minor=2 --patch=1 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=v8-profiler --host=https://node-inspector.s3.amazonaws.com/ --module_path=/usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.1/node-v11-linux-x64 --module=/usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.1/node-v11-linux-x64/profiler.node --remote_path=./profiler/v5.2.1/ --package_name=node-v11-linux-x64.tar.gz --staged_tarball=build/stage/profiler/v5.2.1/node-v11-linux-x64.tar.gz --hosted_path=https://node-inspector.s3.amazonaws.com/profiler/v5.2.1/ --hosted_tarball=https://node-inspector.s3.amazonaws.com/profiler/v5.2.1/node-v11-linux-x64.tar.gz' (1)

> v8-debug@0.3.1 install /usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

Traceback (most recent call last):
  File "/usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 534, in script_main
    return main(sys.argv[1:])
  File "/usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 527, in main
    return gyp_main(args)
  File "/usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 503, in gyp_main
    options.circular_check)
  File "/usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File "/usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2692, in Load
    variables, includes, depth, check, True)
  File "/usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 362, in LoadTargetBuildFile
    includes, True, check)
  File "/usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 219, in LoadOneBuildFile
    None)
  File "binding.gyp", line 1
    {
     ^
SyntaxError: invalid syntax
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-358.el6.x86_64
gyp ERR! command "/usr/local/node/node-v0.10.35/bin/node" "/usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=v8-debug" "--configuration=Release" "--module_name=debug" "--version=0.3.1" "--minor=3" "--patch=1" "--runtime=node" "--node_abi=node-v11" "--platform=linux" "--target_platform=linux" "--arch=x64" "--target_arch=x64" "--module_main=v8-debug" "--host=https://node-inspector.s3.amazonaws.com/" "--module_path=/usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.3.1/node-v11-linux-x64" "--module=/usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.3.1/node-v11-linux-x64/debug.node" "--remote_path=./debug/v0.3.1/" "--package_name=node-v11-linux-x64.tar.gz" "--staged_tarball=build/stage/debug/v0.3.1/node-v11-linux-x64.tar.gz" "--hosted_path=https://node-inspector.s3.amazonaws.com/debug/v0.3.1/" "--hosted_tarball=https://node-inspector.s3.amazonaws.com/debug/v0.3.1/node-v11-linux-x64.tar.gz"
gyp ERR! cwd /usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/v8-debug
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/node/node-v0.10.35/bin/node /usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=v8-debug --configuration=Release --module_name=debug --version=0.3.1 --minor=3 --patch=1 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=v8-debug --host=https://node-inspector.s3.amazonaws.com/ --module_path=/usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.3.1/node-v11-linux-x64 --module=/usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.3.1/node-v11-linux-x64/debug.node --remote_path=./debug/v0.3.1/ --package_name=node-v11-linux-x64.tar.gz --staged_tarball=build/stage/debug/v0.3.1/node-v11-linux-x64.tar.gz --hosted_path=https://node-inspector.s3.amazonaws.com/debug/v0.3.1/ --hosted_tarball=https://node-inspector.s3.amazonaws.com/debug/v0.3.1/node-v11-linux-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 2.6.32-358.el6.x86_64
node-pre-gyp ERR! command "node" "/usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/v8-debug/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/v8-debug
node-pre-gyp ERR! node -v v0.10.35
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/node/node-v0.10.35/bin/node /usr/local/node/node-v0.10.35/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=v8-debug --configuration=Release --module_name=debug --version=0.3.1 --minor=3 --patch=1 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=v8-debug --host=https://node-inspector.s3.amazonaws.com/ --module_path=/usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.3.1/node-v11-linux-x64 --module=/usr/local/node/node-v0.10.35/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.3.1/node-v11-linux-x64/debug.node --remote_path=./debug/v0.3.1/ --package_name=node-v11-linux-x64.tar.gz --staged_tarball=build/stage/debug/v0.3.1/node-v11-linux-x64.tar.gz --hosted_path=https://node-inspector.s3.amazonaws.com/debug/v0.3.1/ --hosted_tarball=https://node-inspector.s3.amazonaws.com/debug/v0.3.1/node-v11-linux-x64.tar.gz' (1)

npm ERR! v8-profiler@5.2.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler@5.2.1 install script.
npm ERR! This is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-358.el6.x86_64
npm ERR! command "/usr/local/node/node-v0.10.35/bin/node" "/usr/local/node/node-default/bin/npm" "i" "-g" "node-inspector" "--unsafe-perm"
npm ERR! cwd /root
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

NodeJs - v0.10.35
NPM - v1.4.28

**Comment by iJoyCode** [comment]
Any progress with build progress?

**Comment by singh1469** [comment]
I'm facing the same issue, any updates greatly appreciated.

**Comment by 3y3** [comment]
I added some fixes to v8-profiler and v8-debug. Also I added prebuild binaries for Linux and OSX.
Please try to reinstall node-inspector now.

**Comment by 3y3** [comment]
Please confirm that problem solved in 0.8.2

**Comment by bajan64** [comment]
Builds cleanly now.

But I'm not getting past the initial startup message:

Node Inspector v0.8.1
Visit http://127.0.0.1:8080/debug?port=5858 to start debugging.
express deprecated res.sendfile: Use res.sendFile instead ../../../../usr/lib/node_modules/node-inspector/lib/debug-server.js:17:7

Then it hangs - or at least doesn't display the console messages at the start of my application indicating that it has started to run.

I am able to connect via the browser and the default screen comes up but with no sources or other information specific to my application.

**Comment by iJoyCode** [comment]
I close this issue, because now it builds clearly. For other problems, I think, opening new issue will be better.
