### ISSUE TITLE
console.timeEnd crashes node-inspector

### ISSUE THREAD

**Issue by gillesdemey** [node-inspector/node-inspector#509]
I've recently upgraded my node-inspector version, and it appears that console output is now logged in the inspector. Nice!

However, this particular use-case — involving `console.time` and `console.timeEnd` — crashes node-inspector:

```javascript

var provider = "foo";
var feedid = 1;

console.time('fetching ', provider ,' posts for feedid ' + feedid);

(function someAsyncFunction() {
  setTimeout(function() {
    console.timeEnd('fetching ', provider ,' posts for feedid ' + feedid);
  }, 2000);
})();
```

Complete stack trace:

```

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property '1' of null
    at getCallerFuncLocation (eval at WRAPPED_BY_NODE_INSPECTOR (/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/v8-debug.js:86:15), <anonymous>:63:31)
    at new ConsoleMessage (eval at WRAPPED_BY_NODE_INSPECTOR (/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/v8-debug.js:86:15), <anonymous>:10:20)
    at Console.debug.register.messageId [as timeEnd] (eval at WRAPPED_BY_NODE_INSPECTOR (/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/v8-debug.js:86:15), <anonymous>:103:21)
    at /Users/gillesdemey/Documents/Subatomic/n2-aggregator/routes/feeds.js:70:15
    at /Users/gillesdemey/Documents/Subatomic/n2-aggregator/db/cache.js:177:11
    at /Users/gillesdemey/Documents/Subatomic/n2-aggregator/db/cache.js:144:7
    at try_callback (/Users/gillesdemey/Documents/Subatomic/n2-aggregator/node_modules/redis/index.js:573:9)
    at RedisClient.return_reply (/Users/gillesdemey/Documents/Subatomic/n2-aggregator/node_modules/redis/index.js:661:13)
    at HiredisReplyParser.<anonymous> (/Users/gillesdemey/Documents/Subatomic/n2-aggregator/node_modules/redis/index.js:309:14)
    at HiredisReplyParser.emit (events.js:95:17)
```

I'm using node `0.10.33` and node-inspector `0.8.1`.

**Comment by 3y3** [comment]
@bajtos , I added a pr that fixes this bug (#512)
