### ISSUE TITLE
Compatibility with io.js

### ISSUE THREAD

**Issue by geforcesong** [node-inspector/node-inspector#523]
I installed iojs 1.0.1 x64 on windows 7 and I want to debug the code, I can not install the node-inspector successfully. How can I do with this?

The error is as follows:
```
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 64-bit node.lib
gyp ERR! stack     at Request.<anonymous> (C:\Program Files\iojs\node_modules\npm\node_modules\node-gyp\lib\install.js:395:20)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (C:\Program Files\iojs\node_modules\npm\node_modules\request\request.js:1255:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:399:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:89:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:290:20)
gyp ERR! stack     at TLSSocket.emit (events.js:95:17)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:143:16)
gyp ERR! stack     at TLSSocket.Readable.push (_stream_readable.js:106:10)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\iojs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--name=v8-profiler" "--configuration=Release" "--module_nam
ode_modules\\node-inspector\\node_modules\\v8-profiler\\build\\profiler\\v5.2.2\\node-v42-win32-x64" "--module=C:\\Users\\george\\AppData\\Roaming\\npm\\node_modules\\node-inspector
-hosted_tarball=https://node-inspector.s3.amazonaws.com/profiler/v5.2.2/node-v42-win32-x64.tar.gz"
gyp ERR! cwd C:\Users\george\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler
gyp ERR! node -v v1.0.1
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd rebuild --name=v8-profiler --configuration=Release --module_name=profiler --version=5.2.2 --major=5 --minor=2 --patch=
2-x64 --module=C:\Users\george\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.2\node-v42-win32-x64\profiler.node --remote_path=./profil
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\george\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\lib\util\
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:979:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1051:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "node" "C:\\Users\\george\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\v8-profiler\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "
node-pre-gyp ERR! cwd C:\Users\george\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler
node-pre-gyp ERR! node -v v1.0.1
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd rebuild --name=v8-profiler --configuration=Release --module_name=profiler --version=5.2.2 --major=5 --minor=2 --patch=2 --runtime=node --node_abi=nod
AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.2\node-v42-win32-x64\profiler.node --remote_path=./profiler/v5.2.2/ --package_name=node-
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\iojs\\\\node.exe" "C:\\Program Files\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-inspector"
npm ERR! node v1.0.1
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.3.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.3.3 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\george\npm-debug.log
```

**Comment by 3y3** [comment]
Good question. So for now I'm not sure in the response, but I think 90% that it is  "No".

First problem is [nan uncompatibility issue](https://github.com/rvagg/nan/pull/224) - we wait v1.5 for updating v8-debug and v8-profiler modules.

Second problem - prebuild binaries. We build they in cloud CI (TravisCI and AppVeyor), so we need to update building matrix for iojs.

### BUT! You can try to continue installation:
How I can see you don't have globally installed `node-gyp`, which is needed to build some submodules of Node Inspector (`v8-debug`, `v8-profiler`). Look at [node-gyp installation info](https://github.com/TooTallNate/node-gyp#installation)

**Comment by timoxley** [comment]
https://github.com/iojs/io.js/issues/456

**Comment by ponychicken** [comment]
nan 1.5 has been released now

**Comment by bajtos** [comment]
@3y3 any updates on this?

**Comment by geforcesong** [comment]
Still not installed successfully.

**Comment by andyhu** [comment]
+1 Can't wait to get it working with io.js

**Comment by ChrisGciso** [comment]
+1

**Comment by Pana** [comment]
+1

**Comment by bajtos** [comment]
A possible workaround: downgrade to 0.7.x.

```
npm install -g node-inspector@0.7
```

**Comment by mrgamer** [comment]
thanks @bajtos, works like a charm until everything is fixed

**Comment by clintwood** [comment]
+1 would more than love to see this work for io.js!

**Comment by jlukanta** [comment]
I can't see the content of arrays or objects using the old version. Any idea why?

**Comment by bajtos** [comment]
> @jlukanta I can't see the content of arrays or objects using the old version. Any idea why?

See https://github.com/node-inspector/node-inspector/pull/492#issuecomment-87848516

**Comment by ericmdantas** [comment]
:+1:

**Comment by JLHwung** [comment]
node-inspector@0.9.2 seems to work with iojs@1.8.1, have tested `--debug-brk` and also can see the contents of objects.
