### ISSUE TITLE
Crash when trying to debug a v0.11.15 node app

### ISSUE THREAD

**Issue by leonidasKap** [node-inspector/node-inspector#536]
I am using 
- Node : v0.11.15 
- node-inspector : v0.8.3
on windows

I start my application as follows :
> node --debug bin\www.js
Then start node inspector
> node-inspector --web-port=8081

When I open the debugger interface
http://127.0.0.1:8081/debug?port=5858
I see no application files and after a few seconds it crashes node-inspector with :

$HOME\AppData\Roaming\npm\node_modules\node-inspector\node_modules\ws\lib\WebSocket.js:181
    else throw new Error('not opened');
               ^
Error: not opened
    at WebSocket.send ($HOME\AppData\Roaming\npm\node_modules\node-inspector\node_modules\ws\lib\WebSocket.js:181:16)
    at FrontendClient._sendMessage ($HOME\AppData\Roaming\npm\node_modules\node-inspector\lib\FrontendClient.js:62:20)
    at FrontendClient.sendEvent ($HOME\AppData\Roaming\npm\node_modules\node-inspector\lib\FrontendClient.js:114:10)
    at EventEmitter.notifyFrontEnd ($HOME\AppData\Roaming\npm\node_modules\node-inspector\lib\ScriptManager.js:134:30)
    at EventEmitter.Object.create.addScript.value ($HOME\AppData\Roaming\npm\node_modules\node-inspector\lib\ScriptManager.js:110:24)
    at Array.forEach (native)
    at Object.handleScriptsResponse ($HOME\AppData\Roaming\npm\node_modules\node-inspector\lib\DebuggerAgent.js:119:16)
    at $HOME\AppData\Roaming\npm\node_modules\node-inspector\lib\DebuggerClient.js:122:7
    at Object.create.processResponse.value ($HOME\AppData\Roaming\npm\node_modules\node-inspector\lib\callback.js:23:20)
    at Debugger._processResponse ($HOME\AppData\Roaming\npm\node_modules\node-inspector\lib\debugger.js:92:21)

The application I am debugging also crashes with :

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:550:26)

**Comment by bajtos** [comment]
Can you reproduce the issue using the latest Node Inspector version (0.9.x at the moment) and either Node v0.12 or io.js 1.x?

**Comment by leonidasKap** [comment]
I tried it with node v0.12 and I can see the exact same issue

**Comment by 3y3** [comment]
Please try to reproduce this issue with node-inspector 0.10.1

**Comment by 3y3** [comment]
No activity by long time. Feel free to reopen it, if issue doesn't solved.

**Comment by eyz** [comment]
I was able to reproduce this with node-inspect 0.12.8 and NodeJS v6.3.1. I was connected via devtools and when I closed the Chrome tab, the Node application I was profiling died with the following exception -
``
2017-03-03: events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:285:12)
    at Client.send (_debug_agent.js:169:15)
    at _debug_agent.js:57:14
    at Array.forEach (native)
    at DebugAPI.Agent.binding.onmessage (_debug_agent.js:56:18)
``
