### ISSUE TITLE
InjectorServer TypeError: Cannot read property 'handle' of undefined

### ISSUE THREAD

**Issue by dillonkrug** [node-inspector/node-inspector#552]
This occurs while I am running a pretty intense test script against my code, so a *lot* of stuff is happening quite quickly.

```
TypeError: Cannot read property 'handle' of undefined
    at checkRefProperty (~/.nvm/v0.11.14/lib/node_modules/node-inspector/lib/InjectorServer.js:73:32)
    at ~/.nvm/v0.11.14/lib/node_modules/node-inspector/lib/InjectorServer.js:32:7
    at Array.forEach (native)
    at V8Debug.debug.serializeAndCacheMirror (~/.nvm/v0.11.14/lib/node_modules/node-inspector/lib/InjectorServer.js:30:23)
    at eval (eval at WRAPPED_BY_NODE_INSPECTOR (~/.nvm/v0.11.14/lib/node_modules/node-inspector/node_modules/v8-debug/v8-debug.js:113:15), <anonymous>:118:22)
    at Array.map (native)
    at Console.eval [as log] (eval at WRAPPED_BY_NODE_INSPECTOR (~/.nvm/v0.11.14/lib/node_modules/node-inspector/node_modules/v8-debug/v8-debug.js:113:15), <anonymous>:117:47)
    at Object.doSomething (~/test/test.js:184:10)
    at _.extend.DO_THE_THING (~/test/test.js:65:21)
    at ~/test/test.js:78:11
```

**Comment by 3y3** [comment]
Hm... Are you using `--harmony` flag in test?

**Comment by dillonkrug** [comment]
Nope

**Comment by bajtos** [comment]
@dillonkrug can you reproduce the problem using the latest Node Inspector version on Node v0.12 or io.js 1.x?
