### ISSUE TITLE
Install fails due to missing lodash.repeat

### ISSUE THREAD

**Issue by rochal** [node-inspector/node-inspector#583]
Hi,

I'm trying to install latest with npm, but I keep getting error related to lodash.repeat:

```
npm http 304 https://registry.npmjs.org/nan

> v8-profiler@5.2.4 install c:\Program Files (x86)\nodejs\node_modules\node-inspector\node_modules\v8-profiler
> node-pre-gyp install --fallback-to-build


> v8-debug@0.4.2 install c:\Program Files (x86)\nodejs\node_modules\node-inspector\node_modules\v8-debug
> node-pre-gyp install --fallback-to-build

module.js:338
    throw err;
          ^
Error: Cannot find module 'lodash.repeat'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\Program Files (x86)\nodejs\node_modules\node-inspector\node_modules\v8-profiler\node_modul
es\node-pre-gyp\node_modules\npmlog\node_modules\gauge\node_modules\lodash.padright\node_modules\lodash._createpad\index
.js:9:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
module.js:338
    throw err;
          ^
Error: Cannot find module 'lodash.repeat'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\Program Files (x86)\nodejs\node_modules\node-inspector\node_modules\v8-debug\node_modules\
node-pre-gyp\node_modules\npmlog\node_modules\gauge\node_modules\lodash.padright\node_modules\lodash._createpad\index.js
:9:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by bajtos** [comment]
Weird, the module is on npm: https://www.npmjs.com/package/lodash.repeat 

Please try `npm cache clean` and then install again. Do you use any proxy or a caching registry?

**Comment by 3y3** [comment]
No activity by long time. Feel free to reopen it, if issue doesn't solved.
Issue looks like resolved.

**Comment by rbaprado** [comment]
I am having this issue as well

**Comment by 3y3** [comment]
@rbaprado , have you tried `npm cache clean`?

**Comment by rbaprado** [comment]
Yep

**Comment by roseanngabon** [comment]
I've tried  <code>npm cache clean</code>, install lodash.repeat both and global and local, uninstall and install npm

But it keeps on  loading these errors.
Please help  :)

<code>
$ ionic start myApp tabs

Error: Cannot find module 'lodash.repeat'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Rose Ann\AppData\Roaming\npm\node_modules\io
nic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\npm\n
ode_modules\npmlog\node_modules\gauge\node_modules\lodash.pad\node_modules\lodas
h._createpadding\index.js:9:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

Cannot find module 'lodash.repeat' (CLI v1.7.12)

Your system information:
Cordova CLI: Not installed
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
OS: Windows 8.1
Node Version: v5.0.0
</code>

<code>
$ cordova -v

module.js:339
    throw err;
    ^
Error: Cannot find module 'path-is-absolute'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Rose Ann\AppData\Roaming\npm\node_modules\co
rdova\node_modules\cordova-lib\node_modules\cordova-common\node_modules\glob\glo
b.js:50:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
</code>

**Comment by roseanngabon** [comment]
I just now solved the issue. This is what I did
1. Go to Control Panel > System and Security > System > Environment Variables. 
2. Add to PATH this: <code>%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\; </code>
3. <code>npm i lodash -g</code>
4. <code>npm i lodash.repeat -g</code>
5. <code>npm i lodash._basetostring -g</code>
6. <code>npm i lodash._createpadding -g</code>
 
Note: I use to install this required module for cordova setup

**Comment by daniell0gda** [comment]
heh, just had this issue, fixed it by removing npm folder from Roaming\npm\node_modules

**Comment by yoav-zibin** [comment]
Same issue, solved also by removing node_modules using:
rm -rf /usr/local/lib/node_modules/phonegap

**Comment by Abybhaskaran** [comment]
I'm trying to install  with npm but it's showing like this anyone can help to me for solveing.
module.js:338
    throw err;
          ^
Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\abhaska4\source\repos\NodeJS\NodeJS\app.js:2:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.runMain [as _onTimeout] (module.js:501:10)
