### ISSUE TITLE
"Cannot read property 'prototype' of undefined" when installing

### ISSUE THREAD

**Issue by jfromaniello** [node-inspector/node-inspector#600]
I'm getting this error when installing with npm on ubuntu, using node 0.8.

```
> v8-debug@0.4.2 install /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build


util.js:538
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:538:43)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet/index.js:114:6)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp/node_modules/npmlog/log.js:2:16)
    at Module._compile (module.js:449:26)
```

**Comment by bajtos** [comment]
@3y3 does v8-debug support Node v0.8?

@jfromaniello what is your npm version? Can you reproduce the problem using `npm@1.4` too?

**Comment by 3y3** [comment]
`v8-debug` has `engine: >=0.10`. It may be reasonable to update `node-inspector` engine. Or we need to support 0.8?

**Comment by jfromaniello** [comment]
@bajtos 

```
» npm version
{ http_parser: '1.0',
  node: '0.8.28',
  v8: '3.11.10.26',
  ares: '1.7.5-DEV',
  uv: '0.8',
  zlib: '1.2.3',
  openssl: '1.0.0m',
  npm: '1.4.23',
  'auth0-manage': '0.0.0' }
```

**Comment by bajtos** [comment]
> @3y3 v8-debug has engine: >=0.10. It may be reasonable to update node-inspector engine. Or we need to support 0.8?

How much work is needed to support Node v0.8?

If it's too much work and/or you don't have time to maintain support for Node v0.8, then we should drop support for Node v0.8 in Node Inspector indeed.

@jfromaniello I believe `node-inspector@0.7` supports Node v0.8 well, can you please give it a try?

**Comment by 3y3** [comment]
There are some small problems with `v8-debug`, but supporting of `v8-profiler` on 0.8.0 is very hard. I prefer to update `node-inspector` engine
