### ISSUE TITLE
Fails to start when Chrome isn't default browser

### ISSUE THREAD

**Issue by LegendaryTom** [node-inspector/node-inspector#626]
Hello,  I'm just trying out node-inspector for the first time and it looks like a fantastic tool.  I'm noticing that when I tried to start node-debug with Firefox as my default browser, the browser opener runs into an error.  

Environment:
Windows 7
Node: v0.10.33

When I switched to having Chrome as my main browser, the inspector started without issue (both versions worked node-inspector@0.9.2 and node-inspector@0.10.0).

Here is the error that I received when Firefox was my default browser.
```
Node Inspector is now available from http://127.0.0.1:8080/debug?port=5858
Debugging `app.js`

debugger listening on port 5858

C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules\biased-opener\node_modules\browser-launcher2\lib\run.js:330
        return +version.split( '.' )[ 0 ];
                        ^
TypeError: Cannot call method 'split' of null
    at major (C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules\biased-opener\node_modules\browser-launcher2\lib\run.js:330:18)
    at C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules\biased-opener\node_modules\browser-launcher2\lib\run.js:344:10
    at Array.sort (native)
    at findMatch (C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules\biased-opener\node_modules\browser-launcher2\lib\run.js:343:6)
    at runBrowser (C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules\biased-opener\node_modules\browser-launcher2\lib\run.js:202:16)
    at launch (C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules\biased-opener\node_modules\browser-launcher2\index.js:54:13)
    at C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules\biased-opener\index.js:69:13
    at C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules\biased-opener\node_modules\browser-launcher2\index.js:31:4
    at C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules\biased-opener\node_modules\browser-launcher2\lib\config.js:34:6
    at fs.js:271:14
```

**Comment by 3y3** [comment]
Retargetted to @jakub-g.

**Comment by jakub-g** [comment]
Hi,

so there seems to be a bug in https://github.com/benderjs/browser-launcher2 but I also have to probably wrap the call with a try-catch to avoid the error.

@LegendaryTom can you do the following in your shell and paste your output?

```
# go to browser-launcher2 dir
cd "C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules\biased-opener\node_modules\browser-launcher2\"

# print the version of browser-launcher2
node -e "console.log(JSON.parse(require('fs').readFileSync('package.json', 'utf-8')).version)"

# detect browsers
node example/detect.js
```

**Comment by jakub-g** [comment]
It seems this could be linked to https://github.com/vweevers/win-detect-browsers/issues/16

**Comment by jakub-g** [comment]
[win-detect-browsers@1.0.2 was released](https://github.com/vweevers/win-detect-browsers/commits/1.0)

Reinstalling node inspector should be enough to fix the issue:

```
npm uninstall -g node-inspector
npm install -g node-inspector
```
Or alternatively
```
cd C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules
rm -rf ./biased-opener
npm install
```

**Comment by LegendaryTom** [comment]
Thanks @jakub-g for looking into this.  Here's the shell output:
```
C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules\biased-opener\node_modules\browser-launcher2>node -e "console.log(JSON.parse(require('fs').readFileSync('package.json', 'utf-8')).version)"
0.4.5

C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules\biased-opener\node_modules\browser-launcher2>node example/detect.js
Available browsers:
[ { name: 'firefox',
    version: '37.0.2.5583',
    type: 'firefox',
    command: 'C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe' },
  { name: 'chrome',
    version: '42.0.2311.135',
    type: 'chrome',
    command: 'C:\\Users\\LegendaryTom\\AppData\\Local\\Google\\Chrome\\Application\\chrome.exe' },
  { name: 'chrome',
    version: null,
    type: 'chrome',
    command: 'C:\\Users\\LegendaryTom\\AppData\\Local\\Google\\Chrome\\Application' },
  { name: 'ie',
    version: '11.0.9600.17728',
    type: 'ie',
    command: 'C:\\Program Files (x86)\\Internet Explorer\\iexplore.exe' },
  { name: 'ie',
    version: '11.0.9600.17728',
    type: 'ie',
    command: 'C:\\Program Files\\Internet Explorer\\iexplore.exe' },
  { name: 'safari',
    version: '5.34.54.16',
    type: 'safari',
    command: 'C:\\Program Files (x86)\\Safari\\Safari.exe' } ]

C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules\biased-opener\node_modules\browser-launcher2>
```
I tried uninstall/reinstall of node-inspector and got the same result.  I also tried the alternative method:
```
C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules>npm install
npm WARN optional dep failed, continuing default-browser-id@1.0.2
fs-extra@0.8.1 fs-extra
+-- ncp@0.4.2
+-- jsonfile@1.1.1
+-- rimraf@2.2.8
+-- mkdirp@0.3.5

chai@1.10.0 chai
+-- assertion-error@1.0.0
+-- deep-eql@0.1.3 (type-detect@0.1.1)

mocha@1.21.5 mocha
+-- escape-string-regexp@1.0.2
+-- diff@1.0.8
+-- commander@2.3.0
+-- growl@1.8.1
+-- debug@2.0.0 (ms@0.6.2)
+-- mkdirp@0.5.0 (minimist@0.0.8)
+-- jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
+-- glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)

jshint@2.7.0 jshint
+-- strip-json-comments@1.0.2
+-- exit@0.1.2
+-- shelljs@0.3.0
+-- console-browserify@1.1.0 (date-now@0.1.4)
+-- minimatch@2.0.7 (brace-expansion@1.1.0)
+-- cli@0.6.6 (glob@3.2.11)
+-- lodash@3.6.0
+-- htmlparser2@3.8.2 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13, domutils@1.5.1)

biased-opener@0.2.5 biased-opener
+-- opener@1.4.1
+-- minimist@1.1.0
+-- x-default-browser@0.3.0
+-- browser-launcher2@0.4.5 (headless@0.1.7, osenv@0.1.0, rimraf@2.2.8, uid@0.0.2, lodash@2.4.2, mkdirp@0.5.0, win-detect-browsers@1.0.2, plist@1.1.0)

C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules>cd "C:\Users\LegendaryTom\Desktop\debug_test"

C:\Users\LegendaryTom\Desktop\debug_test>node-debug app.js
Node Inspector is now available from http://127.0.0.1:8080/debug?ws=127.0.0.1:8080&port=5858
Debugging `app.js`

debugger listening on port 5858

C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules\biased-opener\node_modules\browser-launcher2\lib\run.js:330
        return +version.split( '.' )[ 0 ];
                        ^
TypeError: Cannot call method 'split' of null
    at major (C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules\biased-opener\node_modules\browser-launcher2\lib\run.js:330:18)
    at C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules\biased-opener\node_modules\browser-launcher2\lib\run.js:344:10
    at Array.sort (native)
    at findMatch (C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules\biased-opener\node_modules\browser-launcher2\lib\run.js:343:6)
    at runBrowser (C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules\biased-opener\node_modules\browser-launcher2\lib\run.js:202:16)
    at launch (C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules\biased-opener\node_modules\browser-launcher2\index.js:54:13)
    at C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules\biased-opener\index.js:69:13
    at C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules\biased-opener\node_modules\browser-launcher2\index.js:31:4
    at C:\Users\LegendaryTom\AppData\Roaming\npm\node_modules\node-inspector\node_modules\biased-opener\node_modules\browser-launcher2\lib\config.js:34:6
    at fs.js:271:14

C:\Users\LegendaryTom\Desktop\debug_test>
```

**Comment by vweevers** [comment]
@LegendaryTom try removing the cached browser list at `%USERPROFILE%/.config/browser-launcher2/config.json`. Otherwise, the new win-detect-browsers is never called (I suspect).

**Comment by LegendaryTom** [comment]
That did the trick.  Now node-inspector is running and successfully opens up Chrome (even when Firefox is set as my default browser).  Much thanks!

**Comment by reyou** [comment]
@vweevers I am getting same error on Windows 7 machine. My default browser is FF. Is there work around for this?

**Comment by vweevers** [comment]
@reyou Have you tried the above (reinstalling or updating, then removing the cache file)?

**Comment by Pablo76** [comment]
Any ideas why i'm getting that when I try to install node-inspector on ubuntu? It installs successfully but it doesn't work (as if it wasn't installed)
