### ISSUE TITLE
Installing on fedora 20

### ISSUE THREAD

**Issue by jetsonjohn** [node-inspector/node-inspector#642]
Having issue on running `npm install -g node-inspector`. Installed node version is 0.12.2

```
> v8-profiler@5.2.7 preinstall /lib/node_modules/node-inspector/node_modules/v8-profiler
>  

 
> v8-debug@0.4.4 preinstall /lib/node_modules/node-inspector/node_modules/v8-debug
>  

npm WARN optional dep failed, continuing default-browser-id@1.0.2
-
> ws@0.4.32 install /lib/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/lib/node_modules/node-inspector/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/usr/lib/node_modules/node-inspector/node_modules/ws/build'
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.2","npm":"2.7.4"})

> v8-profiler@5.2.7 postinstall /lib/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/lib/node_modules/node-inspector/node_modules/v8-profiler/.node-gyp"
make: Entering directory `/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build'
  CXX(target) Release/obj.target/profiler/src/profiler.o
make: g++: Command not found
make: *** [Release/obj.target/profiler/src/profiler.o] Error 127
make: Leaving directory `/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/installs/node-v0.12.2-linux-x86/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.19.5-100.fc20.i686+PAE
gyp ERR! command "/opt/installs/node-v0.12.2-linux-x86/bin/node" "/opt/installs/node-v0.12.2-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.7/node-v14-linux-ia32/profiler.node" "--module_name=profiler" "--module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.7/node-v14-linux-ia32"
gyp ERR! cwd /usr/lib/node_modules/node-inspector/node_modules/v8-profiler
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/opt/installs/node-v0.12.2-linux-x86/bin/node /opt/installs/node-v0.12.2-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.7/node-v14-linux-ia32/profiler.node --module_name=profiler --module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.7/node-v14-linux-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Linux 3.19.5-100.fc20.i686+PAE
node-pre-gyp ERR! command "node" "/lib/node_modules/node-inspector/node_modules/v8-profiler/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/node-inspector/node_modules/v8-profiler
node-pre-gyp ERR! node -v v0.12.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok 
Failed to execute '/opt/installs/node-v0.12.2-linux-x86/bin/node /opt/installs/node-v0.12.2-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.7/node-v14-linux-ia32/profiler.node --module_name=profiler --module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.7/node-v14-linux-ia32' (1)

> v8-debug@0.4.4 postinstall /lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/lib/node_modules/node-inspector/node_modules/v8-debug/.node-gyp"
make: Entering directory `/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build'
  CXX(target) Release/obj.target/debug/src/debug.o
make: g++: Command not found
make: *** [Release/obj.target/debug/src/debug.o] Error 127
make: Leaving directory `/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/installs/node-v0.12.2-linux-x86/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.19.5-100.fc20.i686+PAE
gyp ERR! command "/opt/installs/node-v0.12.2-linux-x86/bin/node" "/opt/installs/node-v0.12.2-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.4/node-v14-linux-ia32/debug.node" "--module_name=debug" "--module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.4/node-v14-linux-ia32"
gyp ERR! cwd /usr/lib/node_modules/node-inspector/node_modules/v8-debug
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/opt/installs/node-v0.12.2-linux-x86/bin/node /opt/installs/node-v0.12.2-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.4/node-v14-linux-ia32/debug.node --module_name=debug --module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.4/node-v14-linux-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Linux 3.19.5-100.fc20.i686+PAE
node-pre-gyp ERR! command "node" "/lib/node_modules/node-inspector/node_modules/v8-debug/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/node-inspector/node_modules/v8-debug
node-pre-gyp ERR! node -v v0.12.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok 
Failed to execute '/opt/installs/node-v0.12.2-linux-x86/bin/node /opt/installs/node-v0.12.2-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.4/node-v14-linux-ia32/debug.node --module_name=debug --module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.4/node-v14-linux-ia32' (1)
npm ERR! Linux 3.19.5-100.fc20.i686+PAE
npm ERR! argv "/bin/node" "/bin/npm" "install" "-g" "node-inspector"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! v8-profiler@5.2.7 postinstall: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-profiler@5.2.7 postinstall script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

**Comment by 3y3** [comment]
Read this issue discussion https://github.com/TooTallNate/node-gyp/issues/454

**Comment by jetsonjohn** [comment]
Installing gyp, build-essential, g++ and added the permission to .node-gyp solved the problem

```
yum install gyp
yum groupinstall "Development Tools" "Development Libraries"
yum install gcc-c++
```

After all that run the code 

`sudo npm install --unsafe-perm -g node-inspector`


It works!
