### ISSUE TITLE
Error: not opened

### ISSUE THREAD

**Issue by ritch** [node-inspector/node-inspector#643]
```
Node Inspector v0.10.0
Visit http://127.0.0.1:8080/debug?ws=127.0.0.1:8080&port=5858 to start debugging.
/usr/local/lib/node_modules/node-inspector/node_modules/ws/lib/WebSocket.js:181
    else throw new Error('not opened');
               ^
Error: not opened
    at WebSocket.send (/usr/local/lib/node_modules/node-inspector/node_modules/ws/lib/WebSocket.js:181:16)
    at FrontendClient._sendMessage (/usr/local/lib/node_modules/node-inspector/lib/FrontendClient.js:62:20)
    at FrontendClient.sendEvent (/usr/local/lib/node_modules/node-inspector/lib/FrontendClient.js:114:10)
    at BreakEventHandler.<anonymous> (/usr/local/lib/node_modules/node-inspector/lib/BreakEventHandler.js:150:28)
    at /usr/local/lib/node_modules/node-inspector/node_modules/async/lib/async.js:254:17
    at done (/usr/local/lib/node_modules/node-inspector/node_modules/async/lib/async.js:135:19)
    at /usr/local/lib/node_modules/node-inspector/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/node-inspector/node_modules/async/lib/async.js:251:21
    at Object.CallFramesProvider._convertDebuggerFrameToInspectorFrame (/usr/local/lib/node_modules/node-inspector/lib/CallFramesProvider.js:57:5)
    at /usr/local/lib/node_modules/node-inspector/node_modules/async/lib/async.js:249:17
```

I'm not sure how to reproduce this exactly, but these are the steps I took when the error occured:

 1. `mocha --debug-brk`
 2. `node-inspector`
 3. opened inspector in chrome
 4. set several break points
 5. ctrl+c on the mocha tab
 6. `mocha --debug-brk`
 7. refreshed inspector in chrome (blank screen for almost a minute)
 8. saw error (above) in node-inspector tab in terminal

@bajtos

**Comment by 3y3** [comment]
@ritch , I released 0.10.1 just now. Can you reproduce this on new version?

**Comment by ritch** [comment]
I'll give it a shot.

**Comment by ritch** [comment]
Can't reproduce with the new version. Although I'm not sure that means its fixed.

**Comment by ritch** [comment]
I'll re-open if I get the error again.
