### ISSUE TITLE
TypeError: Object #<Object> has no method 'isAbsolute'

### ISSUE THREAD

**Issue by jlecomte** [node-inspector/node-inspector#686]
First of all, thanks to the team for maintaining and evolving this critical tool. The community is grateful for your work!

I see the following error, which prevents me from debugging my app:
```
$ node-inspector 
Node Inspector v0.10.2
Visit http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858 to start debugging.

/Users/jlecomte/.nvm/v0.10.38/lib/node_modules/node-inspector/lib/ScriptManager.js:243
          if (!path.isAbsolute(source)) return source;
                    ^
TypeError: Object #<Object> has no method 'isAbsolute'
    at /Users/jlecomte/.nvm/v0.10.38/lib/node_modules/node-inspector/lib/ScriptManager.js:243:21
    at Array.map (native)
    at fixAbsoluteSourcePaths (/Users/jlecomte/.nvm/v0.10.38/lib/node_modules/node-inspector/lib/ScriptManager.js:242:47)
    at EventEmitter.Object.create._checkSourceMapIssues.value (/Users/jlecomte/.nvm/v0.10.38/lib/node_modules/node-inspector/lib/ScriptManager.js:236:7)
    at EventEmitter.Object.create._checkInlineSourceMap.value (/Users/jlecomte/.nvm/v0.10.38/lib/node_modules/node-inspector/lib/ScriptManager.js:225:12)
    at EventEmitter.onGetSourceMapUrlReturn (/Users/jlecomte/.nvm/v0.10.38/lib/node_modules/node-inspector/lib/ScriptManager.js:200:18)
    at EventEmitter.Object.create._parseSourceMapUrlFromScriptSource.value (/Users/jlecomte/.nvm/v0.10.38/lib/node_modules/node-inspector/lib/ScriptManager.js:344:7)
    at fn (/Users/jlecomte/.nvm/v0.10.38/lib/node_modules/node-inspector/node_modules/async/lib/async.js:638:34)
    at Object._onImmediate (/Users/jlecomte/.nvm/v0.10.38/lib/node_modules/node-inspector/node_modules/async/lib/async.js:554:34)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

I haven't had time to try and figure out why this was happening, but hopefully, the stack trace will be revealing enough. Let me know if there is anything else I can do to help you debug this issue. Cheers!

**Comment by jlecomte** [comment]
Oh, wow, this is weird:

$ node
> require('path')
{ resolve: [Function],
  normalize: [Function],
  join: [Function],
  relative: [Function],
  sep: '/',
  delimiter: ':',
  dirname: [Function],
  basename: [Function],
  extname: [Function],
  exists: [Function: deprecated],
  existsSync: [Function: deprecated],
  _makeLong: [Function] }
> require('path').isAbsolute
undefined

$ node --version
v0.10.38

**Comment by jlecomte** [comment]
Something is wrong with my setup. I installed a new version of node via nvm and this went away. Closing issue as invalid...

**Comment by le0nik** [comment]
The issue is not invalid. Node-inspector doesn't work for Node versions < 12, because path module has doesn't have isAbsolute method in those versions.

Is this an issue or is node-inspector only supposed to work for Node 12+ or io?

**Comment by 3y3** [comment]
This is an issue. Fixup already merged. You can fork latest commit or wait `0.11.0` release. (Maybe I'll release `0.10.3` on this weekend)

**Comment by le0nik** [comment]
@3y3 thank you!

**Comment by kashesandr** [comment]
Updating to nodejs `5.6` solved the issue
