### ISSUE TITLE
Record Heap Allocations Error

### ISSUE THREAD

**Issue by thisjustin** [node-inspector/node-inspector#692]
Running Node 0.12.6 on OSX 10.10.3

About 10 seconds after starting a heap recording I get this error:
```
Node Inspector v0.11.1
Visit http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858 to start debugging.
/usr/local/lib/node_modules/node-inspector/node_modules/ws/lib/WebSocket.js:214
    else throw new Error('not opened');
               ^
Error: not opened
    at WebSocket.send (/usr/local/lib/node_modules/node-inspector/node_modules/ws/lib/WebSocket.js:214:16)
    at FrontendClient._sendMessage (/usr/local/lib/node_modules/node-inspector/lib/FrontendClient.js:62:20)
    at FrontendClient.sendEvent (/usr/local/lib/node_modules/node-inspector/lib/FrontendClient.js:114:10)
    at HeapProfilerAgent.<anonymous> (/usr/local/lib/node_modules/node-inspector/lib/HeapProfilerAgent.js:61:28)
    at DebuggerClient.emit (events.js:107:17)
    at DebuggerClient._emitDebuggerEvent (/usr/local/lib/node_modules/node-inspector/lib/DebuggerClient.js:92:8)
    at Debugger.emit (events.js:107:17)
    at Debugger._processResponse (/usr/local/lib/node_modules/node-inspector/lib/debugger.js:102:10)
    at Protocol.execute (_debugger.js:137:14)
    at Socket.emit (events.js:107:17)
```

**Comment by EricSmekens** [comment]
Also running Node 0.12.6 with Node-inspector 0.11.1.
I was not able to reproduce this, so it would be good if you could provide more info so somebody can reproduce it. Might also be worth it to try with newer version of inspector.
