### ISSUE TITLE
EACCESS error when running node-debug

### ISSUE THREAD

**Issue by samholmes** [node-inspector/node-inspector#693]
```
Node Inspector is now available from http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858
Debugging `app.js`

Debugger listening on port 5858
child_process.js:1162
    throw errnoException(err, 'spawn');
          ^
Error: spawn EACCES
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at exports.spawn (child_process.js:995:9)
    at checkOthers (/usr/local/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/lib/detect.js:124:16)
    at checkDarwin (/usr/local/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/lib/detect.js:113:3)
    at next (/usr/local/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/lib/detect.js:185:3)
    at /usr/local/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/lib/detect.js:202:4
    at /usr/local/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/lib/detect.js:94:6
    at check (/usr/local/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/lib/darwin/firefox.js:10:5)
    at /usr/local/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/lib/darwin/firefox.js:30:8
```

I'm running the command `node-debug app.js` and I also tried using `sudo`.

**Comment by stefanmayer13** [comment]
I had the same issue using node version 0.12. Node 0.10.x works.

**Comment by stefanmayer13** [comment]
I had the same issue. The problem was that it tried to determine the version if phantomjs and my console returned "permission denied". I fixed that and now it works. In my opinion the function `checkOthers` should handle such errors. It seems like the .on('error') is not sufficient as an expection is thrown.

**Comment by samholmes** [comment]
@stefanmayer13 I'm not using phantomjs though. I wonder what the issue is in my case.

**Comment by stefanmayer13** [comment]
@samholmes Even if you don't want to use phantomjs, node-inspector is checking it in the function checkOthers in detect.js. Try adding a console log of the process name in detect.js before line 124 and see which command is causing the issue. At least it helped me to find the root cause on my system.

**Comment by samholmes** [comment]
@stefanmayer13 If node-inspector is checking phantomjs in the function checkOthers in detect.js, then why isn't phantomjs a dependency in node-inspector's package.json (this appears to be a bug)?

Also, I cannot find detect.js in my installed node-inspector. Can you help me to find it?

**Comment by 3y3** [comment]
This error is not special for node-inspector.
Please google `node eaccess error child_process`

**Comment by samholmes** [comment]
@3y3 when I google "node eaccess error child_process", the first thing google shows is this issue. haha

**Comment by stefanmayer13** [comment]
@samholmes It says in the stack trace you posted where the detect.js file is located: /usr/local/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/lib/detect.js

**Comment by 3y3** [comment]
If you want to dig into `detect.js` you can start node-inspector separately
```
$ node-inspector &
$ node --debug-brk app.js
```

**Comment by figalex** [comment]
@stefanmayer13 and how did you fixed that phantomjs issue? I'm having the same problem but don't know if I have to update phantomjs to fix it or what to do. I'm not using phantomjs but node-inspector it is trying to check its version.
