### ISSUE TITLE
Error every time debugger is running during an http.request() call.

### ISSUE THREAD

**Issue by ghendricks** [node-inspector/node-inspector#700]
Since the update to chrome 44 I get the following error whenever running code with a http.request() call. 

    TypeError: Cannot read property &#39;_host&#39; of null
        at ClientRequest.http.ClientRequest.onSocket (eval at WRAPPED_BY_NODE_INSPECTOR (/Users/username/.nvm/v0.10.39/lib/node_modules/node-inspector/node_modules/v8-debug/v8-debug.js:95:15), &lt;anonymous&gt;:381:28)
        at new ClientRequest (http.js:1433:10)
        at Object.exports.request (https.js:123:10)
    ...

I suspect it has something to do with the WRAPPED_BY_NODE_INSPECTOR in chrome 44 since when I run my app without the debugger (I.e. node app.js), there is no error. I have confirmed this issue in multiple projects which were all working with node-inspector last week before chrome updated.

node version: v0.10.39
node-inspector: v0.11.1
Mac OS: 10.10.4
Chrome: 44.0.2403.89 (64-bit)

**Comment by 3y3** [comment]
Fixed in 0.11.2
Please confirm this and close the issue if all works fine here.

**Comment by ghendricks** [comment]
This appears to be working again in 0.11.2 thanks.
