### ISSUE TITLE
Unexpected token ILLEGAL [some UTF-8 characters]

### ISSUE THREAD

**Issue by simonh1000** [node-inspector/node-inspector#720]
Freshly installed node-inspector globally on a OSX device with node 0.12.7. How can I make debugging possible?

```
New-MBAir:ga-service-acct simon$ node-debug test
Node Inspector is now available from http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858
Debugging `test`

Debugger listening on port 5858
/bin/test:1
(function (exports, require, module, __filename, __dirname) { ����
                                                              ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.runMain [as _onTimeout] (module.js:501:10)
    at Timer.listOnTimeout (timers.js:119:15)
```

**Comment by Aweary** [comment]
Same issue here as well, running `Node Inspector v0.12.2` on `OS X 10.10 (14A361c)`

**Comment by 3y3** [comment]
Can you reproduce this on Node Inspector 0.12.0 or 0.12.1?

**Comment by simonh1000** [comment]
Yes, I do seem to be able to :-(

**Comment by 3y3** [comment]
Which encoding you use in files?

**Comment by simonh1000** [comment]
I'm using Atom on Ubuntu - i.e. nothing special

**Comment by cyberwombat** [comment]
I would try it on a blank file and go from there. It sounds like its not a JS file. I accidently called my script with `node-debug node app.js` and got the same error (as it was now debugging node itself which is not a js file instead of app.js). The process uses `fork` which expects a js script.

**Comment by simonh1000** [comment]
Thanks. Not sure what has happened, but I upgrade to node 4, reinstalled node-inspector and now everything looks as though it is working

**Comment by timaschew** [comment]
I had this issue with node 5.4.1, I switch with __n__ to 4.3.2 and there it works now.

**Comment by Vikasg7** [comment]
Its an issue with file encoding which holds your code
I am using sublime text and I have changed the file encoding to UTF-8 and now the code is working fine.

**Comment by dimirc** [comment]
I downgrade but still have the problem

**Comment by cagdastulek** [comment]
You are trying to debug `test` binary. I guess you should run something like `node-debug test.js`
