### ISSUE TITLE
TypeError: invalid data - Executing node-debug on Windows 10

### ISSUE THREAD

**Issue by giacomorebonato** [node-inspector/node-inspector#725]
Hi, I am trying to solve this error. I had problem installing node-inspector on Windows 10, but installing C++ things in Visual Studio installation and adding msvs_version 2015 in npm configuration allowed me to install it without error.
Now I am getting this when I run node-debug server.js for starting my application.
I am new to node-inspector, but I have already tried a lot of things.

```sh
$ > node-debug server.js
net.js:633
    throw new TypeError('invalid data');
          ^
TypeError: invalid data
    at WriteStream.Socket.write (net.js:633:11)
    at execFileSync (child_process.js:1364:20)
    at Function.module.exports.sync (C:\Users\Admin\AppData\Roaming\npm\node_modules\node-inspector\node_modules\yargs\node_modules\os-locale\index.js:78:16)
    at Argv (C:\Users\Admin\AppData\Roaming\npm\node_modules\node-inspector\node_modules\yargs\index.js:22:22)
    at Object.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\node-inspector\node_modules\yargs\index.js:10:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by giacomorebonato** [comment]
The problem is caused by the function childProcess.execFileSync inside the module
node-inspector > yargs > os-locale > exec-file-sync > index.js
A workaround is to set a static locale in node-inspector > yargs > index.js
```sh
   var y18n = Y18n({
    directory: path.resolve(__dirname, './locales'),
    //locale: osLocale.sync(),
    locale: 'en',
    updateFiles: false
  })
```

I really would like an explanation about this.
