### ISSUE TITLE
Cannot find module v8-profiler

### ISSUE THREAD

**Issue by bgdavidx** [node-inspector/node-inspector#727]
Hi, I tried running this with io.js 2.3.4 and I have this error:

    npm i -g node-inspector
    node-inspector --web-port=6969
    Node Inspector v0.12.2
    Visit http://127.0.0.1:6969/?ws=127.0.0.1:6969&port=5858 to start debugging.
    module.js:338
        throw err;
              ^
    Error: Cannot find module 'v8-profiler'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.require.resolve (module.js:388:19)
        at ProfilerAgent._inject (/usr/local/lib/node_modules/node-inspector/lib/ProfilerAgent.js:44:30)
        at emitOne (events.js:82:20)
        at InjectorClient.emit (events.js:169:7)
        at InjectorClient.<anonymous> (/usr/local/lib/node_modules/node-inspector/lib/InjectorClient.js:168:10)
        at /usr/local/lib/node_modules/node-inspector/lib/DebuggerClient.js:141:7
        at Object.create.processResponse.value (/usr/local/lib/node_modules/node-inspector/lib/callback.js:23:20)
        at Debugger._processResponse (/usr/local/lib/node_modules/node-inspector/lib/debugger.js:95:21)
        at Protocol.execute (_debugger.js:120:14)

Mac OSX Yosemite, io.js v2.3.4

**Comment by akdor1154** [comment]
I am seeing this on Linux without io.js at all.. node v0.12.7.

**Comment by wood1986** [comment]
same here

**Comment by NeZeD** [comment]
Same story. io 2.5.0, node 0.12.7
It is this [v8-profiler@5.2.10](https://github.com/node-inspector/v8-profiler/commit/4ef423df9fe92d745561ad60cd543f3ee473530c) is to blame?

**Comment by wood1986** [comment]
0.12.x, 0.11.x, 0.10.x have the same issue

**Comment by nanwangjkl** [comment]
Windows 10, node 0.12.7, same issue

**Comment by 3y3** [comment]
I release v8-profiler 5.2.11. Try to completely reinstall node-inspector

**Comment by NeZeD** [comment]
@3y3 :+1:

**Comment by 3y3** [comment]
Try to install 0.12.5. This version includes prebuilt binaries for all actual node versions from the box.
Feel free to reopen this issue if it still exist.
