### ISSUE TITLE
Node Inspector dies when UI opened (with electron)

### ISSUE THREAD

**Issue by apexskier** [node-inspector/node-inspector#730]
I'm running node-inspector (v0.12.2) with [Electron v0.31.1](https://github.com/atom/electron/tree/v0.31.1).

I run node-inspector, run electron with --debug-brk, then open the UI/web page specified by node-inspector and node-inspector crashes with the following output:

```
Node Inspector v0.12.2
Visit http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858 to start debugging.
/usr/local/lib/node_modules/node-inspector/lib/PageAgent.js:61
    var cwd = this._debuggerClient.target.cwd;
                                         ^
TypeError: Cannot read property 'cwd' of undefined
    at PageAgent.extend._doGetResourceTree (/usr/local/lib/node_modules/node-inspector/lib/PageAgent.js:61:42)
    at DebuggerClient.g (events.js:199:16)
    at DebuggerClient.emit (events.js:129:20)
    at DebuggerClient.<anonymous> (/usr/local/lib/node_modules/node-inspector/lib/DebuggerClient.js:93:10)
    at _handleEvaluateResponse (/usr/local/lib/node_modules/node-inspector/lib/DebuggerClient.js:187:23)
    at /usr/local/lib/node_modules/node-inspector/lib/DebuggerClient.js:136:7
    at Object.create.processResponse.value (/usr/local/lib/node_modules/node-inspector/lib/callback.js:23:20)
    at Debugger._processResponse (/usr/local/lib/node_modules/node-inspector/lib/debugger.js:95:21)
    at Protocol.execute (_debugger.js:137:14)
    at Socket.emit (events.js:107:17)
```

I've tried installing node-inspector both globally and within my project. The only warning I see when installing is the following:
```
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.7","npm":"2.14.1"})
```

Is this a bug, or something I'm doing wrong?

Edit:
Tried installing with `--target=1.6.3` and have the same results.

**Comment by apexskier** [comment]
This didn't actually fix the issue. I took a look at the code and found a few things that look suspicious. See pull request #735.

**Comment by iofjuupasli** [comment]
v0.12.3 - the same error.

Can't debug my app. Please merge #735 if it helps

```
Node Inspector v0.12.3
Visit http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858 to start debugging.
/home/iofjuupasli/.nvm/versions/io.js/v3.1.0/lib/node_modules/node-inspector/lib/PageAgent.js:61
    var cwd = this._debuggerClient.target.cwd;
                                         ^

TypeError: Cannot read property 'cwd' of undefined
    at PageAgent.extend._doGetResourceTree (/home/iofjuupasli/.nvm/versions/io.js/v3.1.0/lib/node_modules/node-inspector/lib/PageAgent.js:61:42)
    at DebuggerClient.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at DebuggerClient.emit (events.js:166:7)
    at DebuggerClient.<anonymous> (/home/iofjuupasli/.nvm/versions/io.js/v3.1.0/lib/node_modules/node-inspector/lib/DebuggerClient.js:93:10)
    at _handleEvaluateResponse (/home/iofjuupasli/.nvm/versions/io.js/v3.1.0/lib/node_modules/node-inspector/lib/DebuggerClient.js:187:23)
    at /home/iofjuupasli/.nvm/versions/io.js/v3.1.0/lib/node_modules/node-inspector/lib/DebuggerClient.js:136:7
    at Object.create.processResponse.value (/home/iofjuupasli/.nvm/versions/io.js/v3.1.0/lib/node_modules/node-inspector/lib/callback.js:23:20)
    at Debugger._processResponse (/home/iofjuupasli/.nvm/versions/io.js/v3.1.0/lib/node_modules/node-inspector/lib/debugger.js:95:21)
    at Protocol.execute (_debugger.js:120:14)
```
```
{ http_parser: '2.5.0',
  node: '3.1.0',
  v8: '4.4.63.25',
  uv: '1.6.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '45',
  openssl: '1.0.2d',
  electron: '0.31.2',
  'atom-shell': '0.31.2',
  chrome: '44.0.2403.125' }
```

**Comment by 3y3** [comment]
Releted issue in electron https://github.com/atom/electron/issues/2741

**Comment by ed-appdev** [comment]
Hello I think this is still an issue. The node-inspector still crashes in version 0.12.3 with the fixes for #730, #724 on Windows 7. 

```
D:\workspace\yyy\desktop-app\electron-app>node-inspector --debug-port=5858 --web-host=localhost --inject
Node Inspector v0.12.3
Visit http://localhost:8080/?ws=localhost:8080&port=5858 to start debugging.
C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\lib\PageAgent.js:61
    var cwd = this._debuggerClient.target.cwd;
                                         ^

TypeError: Cannot read property 'cwd' of undefined
    at PageAgent.extend._doGetResourceTree (C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\lib\PageAgent.js:61:42)
    at DebuggerClient.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at DebuggerClient.emit (events.js:166:7)
    at DebuggerClient.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\lib\DebuggerClient.js:93:10)
    at _handleEvaluateResponse (C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\lib\DebuggerClient.js:187:23)
    at C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\lib\DebuggerClient.js:136:7
    at Object.create.processResponse.value (C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\lib\callback.js:23:20)
    at Debugger._processResponse (C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\lib\debugger.js:95:21)
    at Protocol.execute (_debugger.js:120:14)
```

When electron is started with: electron --debug-brk=5858 .\electron-app\index.js    
    
electron --version -> v0.33.7
node-inspector --version -> Node Inspector v0.12.3
OS: Windows 7

**Comment by lukeapage** [comment]
this is an electron bug - with some help I've improved the instructions on how to debug electron with node-inspector

atom/electron#4004

this bug is a duplicate of #774 and #649
