### ISSUE TITLE
new_chrome.exe ENOENT

### ISSUE THREAD

**Issue by utuhori** [node-inspector/node-inspector#732]
Hi all,

I do not know for sure what happened. I installed and used node-inspector without problem until yesterday. And then the Chrome browser lost his icon (but still worked), I uninstalled and reinstalled Chrome. After that whenever I tried to run **node-debug my_app.js**, I've got this message

*Debugger listening on port 5858
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn C:\Program Files (x86)\Google\Chrome\Application\new_chrome.exe ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)*

The directory C:\Program Files (x86)\Google\Chrome\Application\ has just *chrome.exe*

I removed and reinstalled **node-inspector** and **Chrome browser** also restarted my PC many times but the error still persists. I made a copy of chrome.exe and renamed it **new_chrome.exe**, the error's gone but node-inspector doesn't work (no new debug window). 

Have anyone any idea of this error or how to config the node-debug to have it run chrome.exe instead of new_chrome.exe ? 

Thanks for your help

**Comment by jakub-g** [comment]
This seems very weird (`new_chrome.exe` thing), though the file not found error seems a bit similar #694 

Can you open
`~/.config/browser-launcher2` in git bash, or
`%HOMEDRIVE%%HOMEPATH%/.config/browser-launcher2` in cmd 
and delete `config.json` and check again?

**Comment by gopinathshiva** [comment]
Suggested a temporary fix for this error at http://stackoverflow.com/questions/36201302/node-inspector-unable-to-open-chrome-browser-throwing-error-enoent . Permanent fix is more welcome
