### ISSUE TITLE
Cannot install on Windows 8.1

### ISSUE THREAD

**Issue by sovattha** [node-inspector/node-inspector#734]
Hello,

I am struggling while trying to install node-inspector on my machine which runs on Windows 8.1.

By following the [installation guide of node-gyp](https://www.npmjs.com/package/node-gyp), I installed Python 2.7, Visual Studio community edition, Windows SDK and node-gyp successfully.

I do not understand what I am missing. Here below is my console output (I replaced my personal information with xxx and zzz):

```
C:\dev\xxxxxxxxxxx>npm install -g node-gyp
C:\Users\zzzzz\AppData\Roaming\npm\node-gyp -> C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js
node-gyp@2.0.2 C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-gyp
├── graceful-fs@3.0.8
├── semver@4.3.6
├── osenv@0.1.3 (os-tmpdir@1.0.1, os-homedir@1.0.1)
├── nopt@3.0.3 (abbrev@1.0.7)
├── fstream@1.0.7 (inherits@2.0.1)
├── minimatch@1.0.0 (sigmund@1.0.1, lru-cache@2.6.5)
├── which@1.1.1 (is-absolute@0.1.7)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── tar@1.0.3 (inherits@2.0.1, block-stream@0.0.8)
├── path-array@1.0.0 (array-index@0.1.1)
├── glob@4.5.3 (inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.10)
├── rimraf@2.4.3 (glob@5.0.14)
├── npmlog@1.2.1 (ansi@0.3.0, are-we-there-yet@1.0.4, gauge@1.2.2)
└── request@2.61.0 (aws-sign2@0.5.0, forever-agent@0.6.1, stringstream@0.0.4, caseless@0.11.0, tunnel-agent@0.4.1, oauth-sign@0.8.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.3, qs@4.0.0, combined-stream@1.0.5, form-data@1.0.0-rc3, mime-types@2.1.5, http-signature@0.11.0, bl@1.0.0, tough-cookie@2.0.0, hawk@3.1.0, har-validator@1.8.0)

C:\dev\xxxxxxxxxxx>npm install -g node-inspector
|


> v8-profiler@5.2.11 preinstall C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler
>

-


> v8-debug@0.5.2 preinstall C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug
>

|


> bufferutil@1.1.0 install C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild


C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\dev\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Génération des projets individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version  number. [C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]
TRACKER : error TRK0005: échec de localisation de : "CL.exe". Le fichier spécifié est introuvable. [C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\dev\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\dev\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing default-browser-id@1.0.2
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})

> utf-8-validate@1.1.0 install C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild


C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\dev\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Génération des projets individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version  number. [C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
TRACKER : error TRK0005: échec de localisation de : "CL.exe". Le fichier spécifié est introuvable. [C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\dev\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\dev\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.1.0
npm WARN optional dep failed, continuing utf-8-validate@1.1.0

> v8-debug@0.5.2 install C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug
> node-pre-gyp install --fallback-to-build

[v8-debug] Success: "C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.5.2\node-v14-win32-x64\debug.node" is installed via remote

> v8-profiler@5.2.11 install C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler
> node-pre-gyp install --fallback-to-build

Génération des projets individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version  number. [C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler.vcxproj]
TRACKER : error TRK0005: échec de localisation de : "CL.exe". Le fichier spécifié est introuvable. [C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\dev\\nodejs\\node.exe" "C:\\Users\\zzzzz\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\zzzzz\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\v8-profiler\\build\\profiler\\v5.2.11\\node-v14-win32-x64\\profiler.node" "--module_name=profiler" "--module_path=C:\\Users\\zzzzz\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\v8-profiler\\build\\profiler\\v5.2.11\\node-v14-win32-x64"
gyp ERR! cwd C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\dev\nodejs\node.exe C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.11\node-v14-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.11\node-v14-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "node" "C:\\Users\\zzzzz\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\v8-profiler\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler
node-pre-gyp ERR! node -v v0.12.7
node-pre-gyp ERR! node-pre-gyp -v v0.6.9
node-pre-gyp ERR! not ok
Failed to execute 'C:\dev\nodejs\node.exe C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.11\node-v14-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\zzzzz\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.11\node-v14-win32-x64' (1)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\dev\\nodejs\\\\node.exe" "C:\\dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-inspector"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! v8-profiler@5.2.11 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler@5.2.11 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\xxxxxxxxxxx\npm-debug.log
```

Thank you in advance for your help.
Sovattha

**Comment by 3y3** [comment]
Please try to reproduce this on Node Inspector 0.12.3

**Comment by jakub-g** [comment]
What happens if you try to install node-inspector without installing node-gyp or any or its deps?

I managed to install node-inspector successfully on Windows 8.1 despite the node-gyp python errors.

The only issue I had was that npm didn't update PATH, I had to follow this
http://stackoverflow.com/a/28339816
i.e. add `PATH` with value `%AppData%\npm;` in the user env variables settings

**Comment by sovattha** [comment]
Thank you for your help! Fixing the PATH was the solution to my problem.
