### ISSUE TITLE
Cannot find module './lib/cookies' when first npm install

### ISSUE THREAD

**Issue by rrgarciach** [node-inspector/node-inspector#746]
Hi
I've created a new project, but when doing npm install (after bower install) by the first time, an error is thrown:

It seems that when attempting to install v8-debug, "Error: Cannot find module './lib/cookies'" comes up

yp info using node-gyp@1.0.1
gyp info using node@0.10.36 | darwin | x64
gyp verb command configure []
gyp verb check python checking for Python executable "python" in the PATH
gyp verb which succeeded python /usr/bin/python
gyp verb check python version python -c "import platform; print(platform.python_version());" returned: "2.7.6\n"
gyp verb get node dir no --target version specified, falling back to host node version: v0.10.36
gyp verb command install [ 'v0.10.36' ]
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: Cannot find module './lib/cookies'
gyp ERR! stack at Function.Module._resolveFilename (module.js:338:15)
gyp ERR! stack at Function.Module._load (module.js:280:25)
gyp ERR! stack at Module.require (module.js:364:17)
gyp ERR! stack at require (module.js:380:17)
gyp ERR! stack at Object. (/Users/rrgarciach/node_modules/npm/node_modules/request/index.js:16:29)
gyp ERR! stack at Module._compile (module.js:456:26)
gyp ERR! stack at Object.Module._extensions..js (module.js:474:10)
gyp ERR! stack at Module.load (module.js:356:32)
gyp ERR! stack at Function.Module._load (module.js:312:12)
gyp ERR! stack at Module.require (module.js:364:17)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "/usr/local/bin/node" "/Users/rrgarciach/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/rrgarciach/Documents/Development/Node/Jupiter-App/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v11-darwin-x64/debug.node" "--module_name=debug" "--module_path=/Users/rrgarciach/Documents/Development/Node/Jupiter-App/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v11-darwin-x64"
gyp ERR! cwd /Users/rrgarciach/Documents/Development/Node/Jupiter-App/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! This is a bug in node-gyp.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR! https://github.com/TooTallNate/node-gyp/issues
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /Users/rrgarciach/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/rrgarciach/Documents/Development/Node/Jupiter-App/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v11-darwin-x64/debug.node --module_name=debug --module_path=/Users/rrgarciach/Documents/Development/Node/Jupiter-App/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v11-darwin-x64' (7)
node-pre-gyp ERR! stack at ChildProcess. (/Users/rrgarciach/Documents/Development/Node/Jupiter-App/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Darwin 14.1.0
node-pre-gyp ERR! command "node" "/Users/rrgarciach/Documents/Development/Node/Jupiter-App/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/rrgarciach/Documents/Development/Node/Jupiter-App/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug
node-pre-gyp ERR! node -v v0.10.36
node-pre-gyp ERR! node-pre-gyp -v v0.6.10
node-pre-gyp ERR! not ok

Hope you can help me here. Thanks!

Info about versions used:
NPM: n2.14.3
node: v0.10.36

**Comment by iDrummer** [comment]
+1

**Comment by iDrummer** [comment]
upgraded to node v4.2.0. solved

**Comment by glennbech** [comment]
why did that solve the problem?
