### ISSUE TITLE
how can I work-around/fix "Unexpected token T"?

### ISSUE THREAD

**Issue by jcollum** [node-inspector/node-inspector#747]
Can't decide if this is an issue or something I'm doing wrong.

This happens when I start node-inspector then open the url in the startup message. I can use NI successfully but sometimes it gets in these loops where I: 

1. start NI
1. browse to URL provided
1. immediately get a message about socket closed
1. check terminal and see:  

```
$ node-inspector
Node Inspector v0.12.1
Visit http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858 to start debugging.
undefined:1
TypeError: undefined is not a function
^
SyntaxError: Unexpected token T
    at Object.parse (native)
    at Protocol.execute (_debugger.js:134:52)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

```

Then I start the whole process again and it happens again. It's like there's some cached value that's causing NI to fail as soon as it tries to load up. 

I can use NI successfully most of the time but these loops are frustrating. 

```
$ versions
npm 2.14.2
node v4.0.0
```

(happened in 0.12.5 as well)

**Comment by 3y3** [comment]
Hello @jcollum 
It will be useful to see your [debug logs](https://github.com/node-inspector/node-inspector/wiki/Debug-logs)

**Comment by jcollum** [comment]
OK I can post those next time it happens. I got it fixed today, I think by killing all my node processes.

**Comment by jiripospisil** [comment]
The same happens to me too sometimes. Unfortunately I cannot provide precise steps to reproduce because it's kind of random and I'm not aware of any pattern in what I do. I did however manage to get the [log](https://gist.github.com/jiripospisil/be56e8b81d147d521b1f) (although I'm not sure if it's of any help).

node v0.12.7

**Comment by rdingwell** [comment]
I think this happens when the node process becomes disconnected somehow and is running off in the background even though you don't know it.  When this has happened to me I've looked in the various terminal windows I may have open to ensure that there are no running node processes.  Then I will list all of the running node processes on the system, inevitably there will be at least one which I then kill.  After that the debugger is up and running again without issue.

**Comment by jcollum** [comment]
I hit this error today, here's the logging when I hit the error: 

```
node-inspector:protocol:devtools frontend: {"id":49,"method":"Debugger.getScriptSource","params":{"scriptId":"87"}} +70ms
  node-inspector:protocol:v8-debug request: {"seq":35171,"type":"request","command":"scripts","arguments":{"includeSource":true,"types":4,"ids":[87],"maxStringLength":-1}} +1ms
  node-inspector:protocol:v8-debug response: {"seq":35,"request_seq":35171,"type":"response","command":"scripts","success":true,"body":[{"handle":12,"type":"script","name":"/Users/collumj/work/projects-aquaKod/monitoring/node_modules/aquaKod/dist/start.js","id":87,"lineOffset":0,"columnOffset":0,"lineCount":46,"source":"(function (exports, require, module, __filename, __dirname) { (function() {\n  var Manager, YAML, args, cl, configPath;\n\n  args = process.argv.slice(2);\n\n  console.log(\"process cwd: \" + (process.cwd()) + \"; args: \" + (JSON.stringify(args)) + \" \");\n\n  YAML = require('yamljs');\n\n  cl = new (require('./configLoader'))();\n\n  if (args.length === 1) {\n\n    /* assume the manager file is in this directory */\n    Manager = require('./manager');\n    configPath = args[0];\n  } else {\n\n    /* pull the manager in from the supplied path */\n    console.log(\"loading manager from  \" + args[1]);\n    configPath = args[1];\n    Manager = require(require(\"path\").join(process.cwd(), args[0].toLowerCase()));\n  }\n\n  cl.loadFromFile(configPath, (function(_this) {\n    return function(err, config) {\n      var m;\n      if (err != null) {\n        throw err;\n      }\n      m = new Manager(config);\n      return m.start(function() {\n        var msg;\n        msg = \"Manager start complete.\";\n        if (m.logger != null) {\n          return m.logger.warn(msg);\n        } else {\n          return console.log(msg);\n        }\n      });\n    };\n  })(this));\n\n}).call(this);\n\n});","sourceLength":1150,"scriptType":2,"compilationType":0,"context":{"ref":11},"text":"/Users/collumj/work/projects-aquaKod/monitoring/node_modules/aquaKod/dist/start.js (lines: 46)"}],"refs":[{"handle":11,"type":"context","text":"#<ContextMirror>"}],"running":false} +11ms
  node-inspector:protocol:devtools backend: {"id":49,"result":{"scriptSource":"(function (exports, require, module, __filename, __dirname) { (function() {\n  var Manager, YAML, args, cl, configPath;\n\n  args = process.argv.slice(2);\n\n  console.log(\"process cwd: \" + (process.cwd()) + \"; args: \" + (JSON.stringify(args)) + \" \");\n\n  YAML = require('yamljs');\n\n  cl = new (require('./configLoader'))();\n\n  if (args.length === 1) {\n\n    /* assume the manager file is in this directory */\n    Manager = require('./manager');\n    configPath = args[0];\n  } else {\n\n    /* pull the manager in from the supplied path */\n    console.log(\"loading manager from  \" + args[1]);\n    configPath = args[1];\n    Manager = require(require(\"path\").join(process.cwd(), args[0].toLowerCase()));\n  }\n\n  cl.loadFromFile(configPath, (function(_this) {\n    return function(err, config) {\n      var m;\n      if (err != null) {\n        throw err;\n      }\n      m = new Manager(config);\n      return m.start(function() {\n        var msg;\n        msg = \"Manager start complete.\";\n        if (m.logger != null) {\n          return m.logger.warn(msg);\n        } else {\n          return console.log(msg);\n        }\n      });\n    };\n  })(this));\n\n}).call(this);\n\n});"}} +4ms
  node-inspector:protocol:v8-debug request: {"seq":0,"type":"request","command":"disconnect"} +234ms
  node-inspector:protocol:v8-debug request: {"seq":0,"type":"request","command":"disconnect"} +2ms
  node-inspector:protocol:devtools frontend: {"id":1,"method":"Page.canScreencast"} +527ms
  node-inspector:protocol:devtools backend: {"id":1,"result":{"result":false}} +0ms
  node-inspector:protocol:devtools frontend: {"id":2,"method":"Page.canEmulate"} +1ms
  node-inspector:protocol:devtools backend: {"id":2,"result":{"result":false}} +0ms
  node-inspector:protocol:devtools frontend: {"id":3,"method":"Worker.canInspectWorkers"} +0ms
  node-inspector:protocol:devtools backend: {"id":3,"result":{"result":false}} +0ms
  node-inspector:protocol:devtools frontend: {"id":4,"method":"Console.setTracingBasedTimeline","params":{"enabled":true}} +0ms
  node-inspector:protocol:devtools backend: {"id":4} +0ms
  node-inspector:protocol:devtools frontend: {"id":5,"method":"Console.enable"} +1ms
  node-inspector:protocol:devtools backend: {"id":5} +0ms
  node-inspector:protocol:devtools frontend: {"id":6,"method":"Network.enable"} +0ms
  node-inspector:protocol:devtools backend: {"id":6} +0ms
  node-inspector:protocol:devtools frontend: {"id":7,"method":"Page.enable"} +0ms
  node-inspector:protocol:devtools backend: {"id":7} +0ms
  node-inspector:protocol:devtools frontend: {"id":8,"method":"Page.getResourceTree"} +1ms
  node-inspector:protocol:devtools frontend: {"id":9,"method":"Debugger.enable"} +0ms
  node-inspector:protocol:devtools frontend: {"id":10,"method":"Debugger.setPauseOnExceptions","params":{"state":"none"}} +0ms
  node-inspector:protocol:v8-debug request: {"seq":35172,"type":"request","command":"setexceptionbreak","arguments":{"type":"all","enabled":false,"maxStringLength":-1}} +0ms
  node-inspector:protocol:v8-debug request: {"seq":35173,"type":"request","command":"evaluate","arguments":{"expression":"JSON.stringify((function () {\n    return {\n      pid: process.pid,\n      cwd: process.cwd(),\n      filename: process.mainModule ? process.mainModule.filename : process.argv[1],\n      nodeVersion: process.version\n    };\n  })()).match(/.{1,80}/g).slice()","global":true,"maxStringLength":-1}} +1ms
  node-inspector:protocol:devtools frontend: {"id":11,"method":"Debugger.setAsyncCallStackDepth","params":{"maxDepth":0}} +0ms
  node-inspector:protocol:devtools backend: {"id":11} +0ms
  node-inspector:protocol:devtools frontend: {"id":12,"method":"Debugger.skipStackFrames","params":{"script":"","skipContentScripts":false}} +0ms
  node-inspector:protocol:devtools backend: {"id":12} +0ms
  node-inspector:protocol:devtools frontend: {"id":13,"method":"Runtime.enable"} +1ms
  node-inspector:protocol:devtools backend: {"id":13} +0ms
  node-inspector:protocol:v8-debug unknown: {} +0ms
  node-inspector:protocol:devtools frontend: {"id":14,"method":"DOM.enable"} +0ms
  node-inspector:protocol:devtools backend: {"id":14} +0ms
undefined:1
TypeError: this.extendedProcessDebugJSONRequest_ is not a function
^

SyntaxError: Unexpected token T
    at Object.parse (native)
    at Protocol.execute (_debugger.js:117:43)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by jcollum** [comment]
Happening again today, same message:

```
undefined:1
TypeError: this.extendedProcessDebugJSONRequest_ is not a function
^

SyntaxError: Unexpected token T
    at Object.parse (native)
    at Protocol.execute (_debugger.js:117:43)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by jcollum** [comment]
I can recreate this issue really easily by hitting the back button on the browser while debugging. The ` Unexpected token T` error happens instantly. Chrome 45.

**Comment by jcollum** [comment]
I posted my debug logs a month ago guys. I've hit this error like 8 times in the last 15 minutes. It'd be nice to be able to fix this when NI gets into these failure loops.
