### ISSUE TITLE
node-inspector crashes with http.request in VM() on Windows

### ISSUE THREAD

**Issue by phdunham** [node-inspector/node-inspector#752]
I have created a simple program to show a typical crash using vm.runInContext().

I am using node v0.12.7 and node-inspector v0.12.3 on  Windows 7 SP1. To reproduce, run node-inspector, run the code below, then step through the code. On the http.request() step, you get the error listed here. 

================
Chrome console error text:
================
 Internal error: TypeError: Cannot read property 'line' of null test.js:17 

================
Node-inspector output from cmd.exe:
================

Node Inspector v0.12.3
Visit http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858 to start debugging.
Received request for a method not implemented: Debugger.setBreakpoint
undefined:1
TypeError: undefined is not a function
^
SyntaxError: Unexpected token T
    at Object.parse (native)
    at Protocol.execute (_debugger.js:134:52)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

===========================
Source code: test.js
===========================

var http = require('http');
var fs = require('fs');
var vm = require('vm');

function vmCode(script) {
	var sandbox = vm.createContext(),
	    vmScript = new vm.Script(script);
	sandbox.http = http;
	sandbox.console = console;
	vmScript.runInContext(sandbox);
}

function main() {
	var script = fs.readFileSync('script.js');

	setInterval(function() {
		console.log('\n\nRunning code,', script.length, 'bytes.');
		vmCode(script);
	}, 7000);
}

main();

===========================
Source code: script.js
===========================

debugger;
console.log('Making request: http://www.google.com/');
http.request({
	host: 'www.google.com',
	path: '/',
	method: 'GET'
}, function (res) {
	console.log('HTTP Status:', res.statusCode);
	var l = 0;

	res.on('data', function (chunk) {
		l += chunk.length;
	});

	res.on('end', function () {
		console.log('body size:', l, 'bytes');
	});
}).end();

Thanks for your support,
Paul

**Comment by 3y3** [comment]
Hello, @phdunham , thank you for verbose description.
I tried to reproduce your problem on Mac for node 0.12.7 and 4.0.0, but all works fine.
So I need some more time to check this code on Windows.

**Comment by phdunham** [comment]
I develop on OSX so everything there is fine. 
Windows has this issue. I just test Ubuntu 14.04 LTS and it has the same problem as windows.
Thanks

**Comment by vishyk** [comment]
Hello @3y3 were you able to reproduce this on Windows or Linux ? It seems to work on OSX but most of our developers use Windows. Trying to see if you have a sense for whether this is fixable in a realistic timeframe.

**Comment by phdunham** [comment]
Yury, Is there a roadmap for node-inspector support? My organization is very interested in support for node-inspector in the VM on Windows and Mac.  I see a lot of work on the marcominetti/node-inspector/ljve branch. Should we be using that version of node-inspector.

Also, is there anything we can do to help get this bug fixed? We can provide remote access to a windows machine if that will help.

Thanks
Paul

**Comment by 3y3** [comment]
Hello @phdunham , unfortunately Marko's branch is only backporting of changes from master. So it will not be useful.

I tried to reproduce this issue on Win8 in VirtualBox, but all works fine... Do you have any machine with Win8  to confirm what there is no problems.

The third step - deeper debugging on your Win7 machines. It's no so hard to debug debugger =)
The best in this situation to have stack trace of caused error, if it doesn't possible use console.log to find a place of error.

So you need to `git clone` node-inspector sources and add some logs to files in `lib/Injections/NetworkAgent.js`. It may be reasonable to use `console._log` because `console.log` was wrapped by node-inspector.
