### ISSUE TITLE
Doesn't build for MacOS, Node 4.1

### ISSUE THREAD

**Issue by iliakan** [node-inspector/node-inspector#760]
Here's the log:
```

npm WARN lifecycle v8-debug@0.5.4~preinstall: cannot run in wd %s %s (wd=%s) v8-debug@0.5.4   /usr/local/lib/node_modules/.staging/v8-debug-d56ef3c156d39eeb44cda4964e0a85c5
npm WARN lifecycle v8-profiler@5.3.2~preinstall: cannot run in wd %s %s (wd=%s) v8-profiler@5.3.2   /usr/local/lib/node_modules/.staging/v8-profiler-700a09d0cc4475efe8f794ecb7f798e3
/usr/local/bin/node-debug -> /usr/local/lib/node_modules/node-inspector/bin/node-debug.js
/usr/local/bin/node-inspector -> /usr/local/lib/node_modules/node-inspector/bin/inspector.js

> bufferutil@1.2.1 install /usr/local/lib/node_modules/node-inspector/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/bufferutil.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/node-inspector/node_modules/bufferutil
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "node-inspector"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! bufferutil@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/iliakan/npm-debug.log
```

**Comment by BlueDevil2k6** [comment]
+1 Getting the exact problem. Please help!

**Comment by adamdva** [comment]
+1 Getting the same on Windows 10 with node v4.1.1

**Comment by gabrielcmendes** [comment]
+1

**Comment by gabrielcmendes** [comment]
+1

**Comment by adamdva** [comment]
I updated to node v4.1.2 on Windows 10, and got the same error.
After I installed python 2.x branch and set the path, I was able to get node-inspector to install and run.

**Comment by chuckweinberger** [comment]
I'm seeing a very similar problem:

```
[nw-server (develop)]$ sudo npm install -g node-inspector --unsafe-perm
 
> v8-debug@0.5.4 preinstall /Users/charlesweinberger/.node_modules_global/lib/node_modules/node-inspector/node_modules/v8-debug
>  

 
> v8-profiler@5.3.2 preinstall /Users/charlesweinberger/.node_modules_global/lib/node_modules/node-inspector/node_modules/v8-profiler
>  

 
> bufferutil@1.2.1 install /Users/charlesweinberger/.node_modules_global/lib/node_modules/node-inspector/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.2.1","npm":"2.10.1"})

> utf-8-validate@1.2.1 install /Users/charlesweinberger/.node_modules_global/lib/node_modules/node-inspector/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished

> v8-profiler@5.3.2 install /Users/charlesweinberger/.node_modules_global/lib/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

sh: node-pre-gyp: command not found

> v8-debug@0.5.4 install /Users/charlesweinberger/.node_modules_global/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

sh: node-pre-gyp: command not found
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/Users/charlesweinberger/.node_modules_global/bin/npm" "install" "-g" "node-inspector" "--unsafe-perm"
npm ERR! node v4.2.1
npm ERR! npm  v2.10.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! v8-profiler@5.3.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the v8-profiler@5.3.2 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/charlesweinberger/software_projects/newswick/nw-server/npm-debug.log
```

**Comment by shreyasubale** [comment]
+1 - getting a slightly different problem

npm WARN prefer global node-inspector@0.10.2 should be installed with -g

> bufferutil@1.1.0 install /Users/shreyas.ubale/projects/beerhug/mean/meanjs/node_modules/node-inspector/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
/Users/shreyas.ubale/projects/beerhug/mean/meanjs/node_modules/.bin/touch: line 1: syntax error near unexpected token `('
/Users/shreyas.ubale/projects/beerhug/mean/meanjs/node_modules/.bin/touch: line 1: `var touch = require("../touch")'
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 2
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/shreyas.ubale/projects/beerhug/mean/meanjs/node_modules/node-inspector/node_modules/bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN EPACKAGEJSON mean@0.0.0 No repository field.
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "grunt-node-inspector"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.5
npm ERR! code ELIFECYCLE

npm ERR! bufferutil@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/shreyas.ubale/projects/beerhug/mean/meanjs/npm-debug.log

**Comment by iliakan** [comment]
Updated MacOS to El Capitan. Now everything builds fine.

**Comment by tjerkw** [comment]
That is not a solution, sometimes you cant upgrade due to other dependencies.

**Comment by chuckweinberger** [comment]
Not building even with el Capitan.

**Comment by gvelo** [comment]
same error here.

**Comment by xapou** [comment]
Same error on OS X Yosemite (10.10.5) with node 4.2.1 (LTM) after a clean install node / npm / yo / angular-generator-fullstack. 

Running:
```
npm install i -g node-inspector@0.10.2
```
...produces numerous errors:
```
> bufferutil@1.1.0 install /Users/xp/.node/lib/node_modules/node-inspector/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:
../../nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {

etc.
```

**Comment by OBJohn** [comment]
@shreyasubale I had that problem too; it seems to be caused by a buggy version of the node-touch package. If you add the newest version of node-touch to your project (npm install touch), it should get you past that particular issue.

**Comment by 3y3** [comment]
@iliakan , you original problem can be fixed by:
```
npm i -g --unsafe-perm node-inspector
```

**Comment by iliakan** [comment]
@3y3 you mean `unsafe-perm` is supposed to fix the 'library not found' problem?

Cannot check it now, everything installs fine. Recent node, recent macos.
