### ISSUE TITLE
"undefined is not a function" in Windows

### ISSUE THREAD

**Issue by beyondbill** [node-inspector/node-inspector#765]
I use v0.12.3 in Windows 7 and got this error. The stack trace is as follows:
```
"stack":"TypeError: undefined is not a function
    at getStackTrace (C:\\Users\\USE THIS\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\lib\\Injections\\NetworkAgent.js:77:18)
    at constructRequestInfo (C:\\Users\\USE THIS\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\lib\\Injections\\NetworkAgent.js:167:21)
    at ClientRequest.handleHttpRequest (C:\\Users\\USE THIS\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\lib\\Injections\\NetworkAgent.js:227:23)
    at Agent.http.Agent.addRequest (C:\\Users\\USE THIS\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\lib\\Injections\\NetworkAgent.js:374:25)
    at new ClientRequest (_http_client.js:154:16)\n    at Object.exports.request (http.js:49:10)
```

In node-inspector/lib/Injections/NetworkAgent.js L77 `return stack.reduce(function(stack, frame) {`, `stack` is a string "Error". That's why it breaks.

I'm trying to create a small test program that reproduces it. Then I'll post it as a follow-up.

**Comment by 3y3** [comment]
What?! How it is possible to get `string` in this place?!
Do you have redefined `Error.prepareStackTrace` in any other place?

**Comment by beyondbill** [comment]
@3y3 We use bunyan logger in our app and it redefines Error.prepareStackTrace.
Thank you for the suggestion! We'll look into the issue in this direction.
