### ISSUE TITLE
Cannot install on windows with node 4.1.1

### ISSUE THREAD

**Issue by togakangaroo** [node-inspector/node-inspector#767]
Just tried to uninstall and re-install node-inspector and it just won't work.

[Here's the npm debug log](https://www.dropbox.com/s/to54hili33kco2b/npm-debug.1.log?dl=0)

Please note that while the actual issue is being thrown by bufferutil, [according to them](https://github.com/websockets/bufferutil/issues/22) it is because the dependency is out of date.

```
W:\> npm uninstall -g node-inspector
W:\> npm install -g node-inspector
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.1.1","npm":"3.3.4"})
npm WARN install Couldn't install optional dependency: Unsupported

> v8-debug@0.5.4 preinstall C:\Users\George\AppData\Roaming\npm\node_modules\.staging\v8-debug-2835e2319fe238f028ae8d5d2df32c30
>


> v8-profiler@5.3.2 preinstall C:\Users\George\AppData\Roaming\npm\node_modules\.staging\v8-profiler-8ba8d2a158f95e40ca38eab5fe19a454
>

C:\Users\George\AppData\Roaming\npm\node-inspector -> C:\Users\George\AppData\Roaming\npm\node_modules\node-inspector\bin\inspector.js
C:\Users\George\AppData\Roaming\npm\node-debug -> C:\Users\George\AppData\Roaming\npm\node_modules\node-inspector\bin\node-debug.js

> bufferutil@1.2.1 install C:\Users\George\AppData\Roaming\npm\node_modules\node-inspector\node_modules\bufferutil
> node-gyp rebuild


C:\Users\George\AppData\Roaming\npm\node_modules\node-inspector\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\George\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\George\AppData\Roaming\npm\node_modules\node-inspector\node_modules\bufferutil\build\bufferutil.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\George\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\George\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\George\AppData\Roaming\npm\node_modules\node-inspector\node_modules\bufferutil
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\George\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-inspector"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.4
npm ERR! code ELIFECYCLE

npm ERR! bufferutil@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     W:\npm-debug.log
```

**Comment by swaheed2** [comment]
+1 same issue with 5.0.0

**Comment by maruf89** [comment]
+1 with 5.0.0 on Mac Yosemite

**Comment by XuJinNet** [comment]
Install node-inspector on the Windows too difficult，Windows 10、Node 5.0.0 .

**Comment by tehOPEologist** [comment]
any status report on this?  can't get it to install, either.  running windows 10, latest node (5.1.0)

**Comment by 3y3** [comment]
This is problem with npm v3 and `bufferutils` (part of `ws` module) module, not with `node-inspector` itself. Please call `ws` module contributors.

**Comment by JustinXinLiu** [comment]
+1, won't install with either 4.1.1 or 5.0.0.

**Comment by shavyg2** [comment]
+1

**Comment by rainabba** [comment]
Running Node 4.2.6 and npm 3.7.2 and getting the same. I've got VS2013 and VS2015 installed and this is the only package having this issue. I'm explicitly tried in the VS 2015 msbuild prompt as admin.

Base on a tip i read elsewhere I've also tried `npm config set msvs_version 2015 --global` and that didn't help, BUT `npm config set msvs_version 2013 --global` did.

Sadly, this didn't resolve the slow startup or crash that had me reinstalling to begin with :(

**Comment by 3y3** [comment]
@rainabba , you have slow startup on node-inspector 0.12.6?

**Comment by rainabba** [comment]
Very. My app takes ~4.5 seconds to get settled normally. With `node-debug` I get an initial break like with --debug-brk. I hit resume in the UI (which comes up quickly), then it takes ~10 before i see anything more and then I eventually get the crash that's holding me up.

**Comment by 3y3** [comment]
How about `node-debug --hidden node_modules` ?

**Comment by rainabba** [comment]
MUCH faster! I hit the crash as quickly as without --debug. Is there a way to make that default for node-inspector or should I just alias it?

Now to figure out why --debug is crashing my app :/

**Comment by 3y3** [comment]
You can add this to your global `.node-inspectorrc`
https://github.com/node-inspector/node-inspector#rc-configuration

**Comment by rainabba** [comment]
Thank you. Looked past that even after being linked to it :)  That rc file needs to be in the working folder where I'm running node-debug from, the root of my user profile (I'm on Windows) or elsewhere?

**Comment by 3y3** [comment]
Read [rc documentation](https://www.npmjs.com/package/rc) to understand there it search rc configs

**Comment by rainabba** [comment]
Should be able to tip you somehow for that. I wasn't aware of that convention. Thank you.

**Comment by rainabba** [comment]
Been trying without luck.

Saved the following as `.$myapp-namerc` in my project folder, where I'm launching node-debug from. What am I missing? I'm on Windows in case that matters.

```
{
  "save-live-edit": true,
  "preload": false,
  "hidden": ["\.test\.js$", "node_modules/"]
}
```

**Comment by asselin** [comment]
ws version 1.0.0 and above removed the dependency on bufferutil, so node-gyp compilation isn't necessary anymore.  node-inspector is currently depending on ws 0.8.0.

@3y3  Would you accept a PR to bump up the ws dependency to 1.0.1 (latest)?

**Comment by 3y3** [comment]
@asselin , yes, pr will be acceptable.

**Comment by asselin** [comment]
@3y3 Sorry, I don't think I got a notification for your reply. I'll submit a PR today.

**Comment by asselin** [comment]
@all version 0.12.8 is available on npm now, and should fix the Windows installation problem
