### ISSUE TITLE
Error when debuging Electron

### ISSUE THREAD

**Issue by cyrusthegreatking** [node-inspector/node-inspector#774]
When I want to open node-inspector to debug an Electron app I've got this error in opened node-inspector console:
```
Error: A dynamic link library (DLL) initialization routine failed.
C:\Users\****\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.5.4\node-v46-win32-x64\debug.node
```
Node.js: 4.1.1.
Node Inspector: 0.12.3
Got this error both in electron-v0.33.7-win32-ia32 and electron-v0.34.3-win32-x64 with --debug=5858.

If use --debug-brk=5858 i've got bellow error in cmd:
```
Node Inspector v0.12.3
Visit http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858 to start debugging.
C:\Users\****\AppData\Roaming\npm\node_modules\node-inspector\lib\PageAgent.js:94
        var realBaseName = files.filter(function(filename) {
                                ^

TypeError: Cannot read property 'filter' of undefined
    at PageAgent.<anonymous> (C:\Users\****\AppData\Roaming\npm\node_modules\node-inspector\lib\PageAgent.js:94:33)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Any help???

**Comment by leftstick** [comment]
Same issue

**Comment by lukeapage** [comment]
+1

**Comment by lukeapage** [comment]
Possibly a electron bug from the sounds of this: https://github.com/atom/electron/issues/3378

**Comment by lukeapage** [comment]
this is an electron bug - with some help I've improved the instructions on how to debug electron with node-inspector

https://github.com/atom/electron/pull/4004

this bug is a duplicate of #730 and #649
