### ISSUE TITLE
No rule to make target '../.node-gyp/5.1.0/include/node/common.gypi'

### ISSUE THREAD

**Issue by x-yuri** [node-inspector/node-inspector#778]
```
# npm install -g node-inspector
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN lifecycle v8-debug@0.5.4~preinstall: cannot run in wd %s %s (wd=%s) v8-debug@0.5.4   /usr/lib/node_modules/.staging/v8-debug-6c1006187cc6e2812b6726f80b738287
npm WARN lifecycle v8-profiler@5.3.2~preinstall: cannot run in wd %s %s (wd=%s) v8-profiler@5.3.2   /usr/lib/node_modules/.staging/v8-profiler-ab7c9b70c2a0d7a67147eff34edb3abe
/usr/bin/node-inspector -> /usr/lib/node_modules/node-inspector/bin/inspector.js
/usr/bin/node-debug -> /usr/lib/node_modules/node-inspector/bin/node-debug.js

> bufferutil@1.2.1 install /usr/lib/node_modules/node-inspector/node_modules/bufferutil
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.1.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/node-inspector/node_modules/bufferutil/.node-gyp"
make: Entering directory '/usr/lib/node_modules/node-inspector/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/usr/lib/node_modules/node-inspector/node_modules/bufferutil/build'

> utf-8-validate@1.2.1 install /usr/lib/node_modules/node-inspector/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.1.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/node-inspector/node_modules/utf-8-validate/.node-gyp"
make: Entering directory '/usr/lib/node_modules/node-inspector/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/usr/lib/node_modules/node-inspector/node_modules/utf-8-validate/build'

> v8-debug@0.5.4 install /usr/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.1.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/node-inspector/node_modules/v8-debug/.node-gyp"
make: Entering directory '/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build'
make: *** No rule to make target '../.node-gyp/5.1.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.5-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.4/node-v47-linux-x64/debug.node" "--module_name=debug" "--module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.4/node-v47-linux-x64"
gyp ERR! cwd /usr/lib/node_modules/node-inspector/node_modules/v8-debug
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.4/node-v47-linux-x64/debug.node --module_name=debug --module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.4/node-v47-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/node-inspector/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.2.5-1-ARCH
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-inspector/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/node-inspector/node_modules/v8-debug
node-pre-gyp ERR! node -v v5.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.17
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.4/node-v47-linux-x64/debug.node --module_name=debug --module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.4/node-v47-linux-x64' (1)
/usr/lib
`-- (empty)

npm WARN In win-detect-browsers@1.0.2 replacing bundled version of yargs with yargs@1.3.3
npm WARN In yargs@3.30.0 replacing bundled version of camelcase with camelcase@1.2.1
npm WARN In xmlbuilder@4.0.0 replacing bundled version of lodash with lodash@3.10.1
npm WARN In mkdirp@0.5.1 replacing bundled version of minimist with minimist@0.0.8
npm WARN In v8-profiler@5.3.2 replacing bundled version of nan with nan@2.0.9
npm WARN In node-inspector@0.12.3 replacing bundled version of glob with glob@5.0.15
npm WARN In node-inspector@0.12.3 replacing bundled version of debug with debug@2.2.0
npm WARN In node-inspector@0.12.3 replacing bundled version of path-is-absolute with path-is-absolute@1.0.0
npm WARN In node-inspector@0.12.3 replacing bundled version of which with which@1.2.0
npm WARN In node-inspector@0.12.3 replacing bundled version of async with async@0.9.2
npm WARN In node-inspector@0.12.3 replacing bundled version of rc with rc@1.1.5
npm WARN In node-inspector@0.12.3 replacing bundled version of serve-favicon with serve-favicon@2.3.0
npm WARN In node-inspector@0.12.3 replacing bundled version of ws with ws@0.8.0
npm WARN In node-inspector@0.12.3 replacing bundled version of camelcase with camelcase@1.2.1
npm WARN In node-inspector@0.12.3 replacing bundled version of semver with semver@4.3.6
npm WARN In node-inspector@0.12.3 replacing bundled version of express with express@4.13.3
npm WARN In node-inspector@0.12.3 replacing bundled version of biased-opener with biased-opener@0.2.7
npm WARN In node-inspector@0.12.3 replacing bundled version of strong-data-uri with strong-data-uri@1.0.3
npm WARN In node-inspector@0.12.3 replacing bundled version of nan with nan@2.0.9
npm WARN In node-inspector@0.12.3 replacing bundled version of v8-debug with v8-debug@0.5.4
npm WARN In node-inspector@0.12.3 replacing bundled version of minimist with minimist@1.2.0
npm WARN In node-inspector@0.12.3 replacing bundled version of x-default-browser with x-default-browser@0.3.1
npm WARN In node-inspector@0.12.3 replacing bundled version of browser-launcher2 with browser-launcher2@0.4.6
npm WARN In node-inspector@0.12.3 replacing bundled version of minimist with minimist@0.0.8
npm WARN In node-inspector@0.12.3 replacing bundled version of osenv with osenv@0.1.3
npm WARN In node-inspector@0.12.3 replacing bundled version of rimraf with rimraf@2.2.8
npm WARN In node-inspector@0.12.3 replacing bundled version of plist with plist@1.2.0
npm WARN In node-inspector@0.12.3 replacing bundled version of lodash with lodash@2.4.2
npm WARN In node-inspector@0.12.3 replacing bundled version of yargs with yargs@1.3.3
npm WARN In node-inspector@0.12.3 replacing bundled version of headless with headless@0.1.7
npm WARN In node-inspector@0.12.3 replacing bundled version of uid with uid@0.0.2
npm WARN In node-inspector@0.12.3 replacing bundled version of os-homedir with os-homedir@1.0.1
npm WARN In node-inspector@0.12.3 replacing bundled version of os-tmpdir with os-tmpdir@1.0.1
npm WARN In node-inspector@0.12.3 replacing bundled version of lodash with lodash@3.10.1
npm WARN In node-inspector@0.12.3 replacing bundled version of util-deprecate with util-deprecate@1.0.2
npm WARN In node-inspector@0.12.3 replacing bundled version of xmldom with xmldom@0.1.19
npm WARN In node-inspector@0.12.3 replacing bundled version of base64-js with base64-js@0.0.8
npm WARN In node-inspector@0.12.3 replacing bundled version of after with after@0.8.1
npm WARN In node-inspector@0.12.3 replacing bundled version of xtend with xtend@4.0.1
npm WARN In node-inspector@0.12.3 replacing bundled version of ms with ms@0.7.1
npm WARN In node-inspector@0.12.3 replacing bundled version of is-absolute with is-absolute@0.1.7
npm WARN In node-inspector@0.12.3 replacing bundled version of is-relative with is-relative@0.1.3
npm WARN In node-inspector@0.12.3 replacing bundled version of default-browser-id with default-browser-id@1.0.4
npm WARN In node-inspector@0.12.3 replacing bundled version of meow with meow@3.6.0
npm WARN In node-inspector@0.12.3 replacing bundled version of untildify with untildify@2.1.0
npm WARN In node-inspector@0.12.3 replacing bundled version of bplist-parser with bplist-parser@0.1.1
npm WARN In node-inspector@0.12.3 replacing bundled version of big-integer with big-integer@1.6.7
npm WARN In node-inspector@0.12.3 replacing bundled version of camelcase-keys with camelcase-keys@2.0.0
npm WARN In node-inspector@0.12.3 replacing bundled version of loud-rejection with loud-rejection@1.2.0
npm WARN In node-inspector@0.12.3 replacing bundled version of read-pkg-up with read-pkg-up@1.0.1
npm WARN In node-inspector@0.12.3 replacing bundled version of normalize-package-data with normalize-package-data@2.3.5
npm WARN In node-inspector@0.12.3 replacing bundled version of redent with redent@1.0.0
npm WARN In node-inspector@0.12.3 replacing bundled version of trim-newlines with trim-newlines@1.0.0
npm WARN In node-inspector@0.12.3 replacing bundled version of object-assign with object-assign@4.0.1
npm WARN In node-inspector@0.12.3 replacing bundled version of camelcase with camelcase@2.0.1
npm WARN In node-inspector@0.12.3 replacing bundled version of map-obj with map-obj@1.0.1
npm WARN In node-inspector@0.12.3 replacing bundled version of signal-exit with signal-exit@2.1.2
npm WARN In node-inspector@0.12.3 replacing bundled version of hosted-git-info with hosted-git-info@2.1.4
npm WARN In node-inspector@0.12.3 replacing bundled version of validate-npm-package-license with validate-npm-package-license@3.0.1
npm WARN In node-inspector@0.12.3 replacing bundled version of is-builtin-module with is-builtin-module@1.0.0
npm WARN In node-inspector@0.12.3 replacing bundled version of builtin-modules with builtin-modules@1.1.0
npm WARN In node-inspector@0.12.3 replacing bundled version of spdx-correct with spdx-correct@1.0.2
npm WARN In node-inspector@0.12.3 replacing bundled version of spdx-expression-parse with spdx-expression-parse@1.0.2
npm WARN In node-inspector@0.12.3 replacing bundled version of spdx-license-ids with spdx-license-ids@1.1.0
npm WARN In node-inspector@0.12.3 replacing bundled version of spdx-exceptions with spdx-exceptions@1.0.4
npm WARN In node-inspector@0.12.3 replacing bundled version of find-up with find-up@1.1.0
npm WARN In node-inspector@0.12.3 replacing bundled version of read-pkg with read-pkg@1.1.0
npm WARN In node-inspector@0.12.3 replacing bundled version of path-exists with path-exists@2.1.0
npm WARN In node-inspector@0.12.3 replacing bundled version of pinkie-promise with pinkie-promise@2.0.0
npm WARN In node-inspector@0.12.3 replacing bundled version of pinkie with pinkie@2.0.1
npm WARN In node-inspector@0.12.3 replacing bundled version of load-json-file with load-json-file@1.1.0
npm WARN In node-inspector@0.12.3 replacing bundled version of path-type with path-type@1.1.0
npm WARN In node-inspector@0.12.3 replacing bundled version of pify with pify@2.3.0
npm WARN In node-inspector@0.12.3 replacing bundled version of graceful-fs with graceful-fs@4.1.2
npm WARN In node-inspector@0.12.3 replacing bundled version of strip-bom with strip-bom@2.0.0
npm WARN In node-inspector@0.12.3 replacing bundled version of parse-json with parse-json@2.2.0
npm WARN In node-inspector@0.12.3 replacing bundled version of error-ex with error-ex@1.3.0
npm WARN In node-inspector@0.12.3 replacing bundled version of is-arrayish with is-arrayish@0.2.1
npm WARN In node-inspector@0.12.3 replacing bundled version of is-utf8 with is-utf8@0.2.0
npm WARN In node-inspector@0.12.3 replacing bundled version of indent-string with indent-string@2.1.0
npm WARN In node-inspector@0.12.3 replacing bundled version of strip-indent with strip-indent@1.0.1
npm WARN In node-inspector@0.12.3 replacing bundled version of repeating with repeating@2.0.0
npm WARN In node-inspector@0.12.3 replacing bundled version of is-finite with is-finite@1.0.1
npm WARN In node-inspector@0.12.3 replacing bundled version of number-is-nan with number-is-nan@1.0.0
npm WARN In node-inspector@0.12.3 replacing bundled version of get-stdin with get-stdin@4.0.1
npm WARN In node-inspector@0.12.3 replacing bundled version of accepts with accepts@1.2.13
npm WARN In node-inspector@0.12.3 replacing bundled version of array-flatten with array-flatten@1.1.1
npm WARN In node-inspector@0.12.3 replacing bundled version of content-type with content-type@1.0.1
npm WARN In node-inspector@0.12.3 replacing bundled version of escape-html with escape-html@1.0.2
npm WARN In node-inspector@0.12.3 replacing bundled version of cookie-signature with cookie-signature@1.0.6
npm WARN In node-inspector@0.12.3 replacing bundled version of cookie with cookie@0.1.3
npm WARN In node-inspector@0.12.3 replacing bundled version of etag with etag@1.7.0
npm WARN In node-inspector@0.12.3 replacing bundled version of content-disposition with content-disposition@0.5.0
npm WARN In node-inspector@0.12.3 replacing bundled version of finalhandler with finalhandler@0.4.0
npm WARN In node-inspector@0.12.3 replacing bundled version of methods with methods@1.1.1
npm WARN In node-inspector@0.12.3 replacing bundled version of merge-descriptors with merge-descriptors@1.0.0
npm WARN In node-inspector@0.12.3 replacing bundled version of parseurl with parseurl@1.3.0
npm WARN In node-inspector@0.12.3 replacing bundled version of on-finished with on-finished@2.3.0
npm WARN In node-inspector@0.12.3 replacing bundled version of path-to-regexp with path-to-regexp@0.1.7
npm WARN In node-inspector@0.12.3 replacing bundled version of proxy-addr with proxy-addr@1.0.8
npm WARN In node-inspector@0.12.3 replacing bundled version of fresh with fresh@0.3.0
npm WARN In node-inspector@0.12.3 replacing bundled version of type-is with type-is@1.6.9
npm WARN In node-inspector@0.12.3 replacing bundled version of send with send@0.13.0
npm WARN In node-inspector@0.12.3 replacing bundled version of vary with vary@1.0.1
npm WARN In node-inspector@0.12.3 replacing bundled version of utils-merge with utils-merge@1.0.0
npm WARN In node-inspector@0.12.3 replacing bundled version of range-parser with range-parser@1.0.3
npm WARN In node-inspector@0.12.3 replacing bundled version of serve-static with serve-static@1.10.0
npm WARN In node-inspector@0.12.3 replacing bundled version of qs with qs@4.0.0
npm WARN In node-inspector@0.12.3 replacing bundled version of depd with depd@1.0.1
npm WARN In node-inspector@0.12.3 replacing bundled version of mime-types with mime-types@2.1.7
npm WARN In node-inspector@0.12.3 replacing bundled version of negotiator with negotiator@0.5.3
npm WARN In node-inspector@0.12.3 replacing bundled version of mime-db with mime-db@1.19.0
npm WARN In node-inspector@0.12.3 replacing bundled version of unpipe with unpipe@1.0.0
npm WARN In node-inspector@0.12.3 replacing bundled version of ee-first with ee-first@1.1.1
npm WARN In node-inspector@0.12.3 replacing bundled version of forwarded with forwarded@0.1.0
npm WARN In node-inspector@0.12.3 replacing bundled version of ipaddr.js with ipaddr.js@1.0.1
npm WARN In node-inspector@0.12.3 replacing bundled version of http-errors with http-errors@1.3.1
npm WARN In node-inspector@0.12.3 replacing bundled version of destroy with destroy@1.0.3
npm WARN In node-inspector@0.12.3 replacing bundled version of mime with mime@1.3.4
npm WARN In node-inspector@0.12.3 replacing bundled version of statuses with statuses@1.2.1
npm WARN In node-inspector@0.12.3 replacing bundled version of inherits with inherits@2.0.1
npm WARN In node-inspector@0.12.3 replacing bundled version of media-typer with media-typer@0.3.0
npm WARN In node-inspector@0.12.3 replacing bundled version of inflight with inflight@1.0.4
npm WARN In node-inspector@0.12.3 replacing bundled version of once with once@1.3.3
npm WARN In node-inspector@0.12.3 replacing bundled version of minimatch with minimatch@3.0.0
npm WARN In node-inspector@0.12.3 replacing bundled version of wrappy with wrappy@1.0.1
npm WARN In node-inspector@0.12.3 replacing bundled version of brace-expansion with brace-expansion@1.1.1
npm WARN In node-inspector@0.12.3 replacing bundled version of balanced-match with balanced-match@0.2.1
npm WARN In node-inspector@0.12.3 replacing bundled version of concat-map with concat-map@0.0.1
npm WARN In node-inspector@0.12.3 replacing bundled version of deep-extend with deep-extend@0.4.0
npm WARN In node-inspector@0.12.3 replacing bundled version of ini with ini@1.3.4
npm WARN In node-inspector@0.12.3 replacing bundled version of strip-json-comments with strip-json-comments@1.0.4
npm WARN In node-inspector@0.12.3 replacing bundled version of truncate with truncate@1.0.5
npm WARN In node-inspector@0.12.3 replacing bundled version of nan with nan@2.1.0
npm WARN In node-inspector@0.12.3 replacing bundled version of options with options@0.0.6
npm WARN In node-inspector@0.12.3 replacing bundled version of bufferutil with bufferutil@1.2.1
npm WARN In node-inspector@0.12.3 replacing bundled version of utf-8-validate with utf-8-validate@1.2.1
npm WARN In node-inspector@0.12.3 replacing bundled version of ultron with ultron@1.0.2
npm WARN In node-inspector@0.12.3 replacing bundled version of bindings with bindings@1.2.1
npm WARN In node-inspector@0.12.3 replacing bundled version of cliui with cliui@3.0.3
npm WARN In node-inspector@0.12.3 replacing bundled version of decamelize with decamelize@1.1.1
npm WARN In node-inspector@0.12.3 replacing bundled version of os-locale with os-locale@1.4.0
npm WARN In node-inspector@0.12.3 replacing bundled version of y18n with y18n@3.2.0
npm WARN In node-inspector@0.12.3 replacing bundled version of window-size with window-size@0.1.4
npm WARN In node-inspector@0.12.3 replacing bundled version of strip-ansi with strip-ansi@3.0.0
npm WARN In node-inspector@0.12.3 replacing bundled version of string-width with string-width@1.0.1
npm WARN In node-inspector@0.12.3 replacing bundled version of wrap-ansi with wrap-ansi@1.0.0
npm WARN In node-inspector@0.12.3 replacing bundled version of code-point-at with code-point-at@1.0.0
npm WARN In node-inspector@0.12.3 replacing bundled version of is-fullwidth-code-point with is-fullwidth-code-point@1.0.0
npm WARN In node-inspector@0.12.3 replacing bundled version of ansi-regex with ansi-regex@2.0.0
npm WARN In node-inspector@0.12.3 replacing bundled version of lcid with lcid@1.0.0
npm WARN In node-inspector@0.12.3 replacing bundled version of invert-kv with invert-kv@1.0.0
npm WARN In node-inspector@0.12.3 replacing bundled version of yargs with yargs@3.30.0
npm WARN In node-inspector@0.12.3 replacing bundled version of v8-profiler with v8-profiler@5.3.2
npm WARN In node-inspector@0.12.3 replacing bundled version of mkdirp with mkdirp@0.5.1
npm WARN In node-inspector@0.12.3 replacing bundled version of win-detect-browsers with win-detect-browsers@1.0.2
npm WARN In node-inspector@0.12.3 replacing bundled version of xmlbuilder with xmlbuilder@4.0.0
npm ERR! Linux 4.2.5-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "node-inspector"
npm ERR! node v5.1.0
npm ERR! npm  v3.5.0
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.5.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.5.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
npm ERR! code 1
```

[npm-debug.txt](https://github.com/node-inspector/node-inspector/files/45313/npm-debug.txt)

**Comment by stelf** [comment]
same here., Linux 3.16.0 Debian stretch/sid. 
node 5.10
npm 3.5.0
node-gyp 3.0.3-2
gyp 0.1+20150913git1f374df9-1

**Comment by gunar** [comment]
Same here.

```
Linux zeno 4.1.13-1-MANJARO #1 SMP PREEMPT Tue Nov 10 22:11:15 UTC 2015 x86_64 GNU/Linux
npm 3.5.1 (3.5.0 didn't work as well)
node v5.1.0
```

**Comment by davejoem** [comment]
Same here

Linux Ubuntu 15.04 
npm 3.3.12
node v5.1.0

**Comment by 3y3** [comment]
How about `npm i -g --unsafe-perm node-inspector` ?

**Comment by x-yuri** [comment]
Indeed, that helped. What was the issue? Is it `npm` who's at fault?

**Comment by KenanSulayman** [comment]
@x-yuri Node 5 is using npm 3, which is considered a rewrite. It's using sane permissions for files, impacting modules that relied on bad permissions.

**Comment by gunar** [comment]
Yeah, that worked. @3y3 and @KenanSulayman, thank you!

**Comment by stelf** [comment]
also confirm this is a valid solution for node v5.2.0 // npm 3.3.12 on debian testing 3.16.7-ckt11-1
