### ISSUE TITLE
Errors on loading Inspector/Unable to hit breakpoints

### ISSUE THREAD

**Issue by codybousc** [node-inspector/node-inspector#780]
I get these two sexy errors when loading 8080: 

/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
Runtime.js:358 Assertion failed: Unknown experiment canvasInspectionRuntime._assert @ Runtime.js:358Runtime.ExperimentsSupport._checkExperiment @ Runtime.js:953Runtime.ExperimentsSupport.isEnabled @ Runtime.js:894WebInspector.ProfileTypeRegistry @ ProfileTypeRegistry.js:19(anonymous function) @ ProfileTypeRegistry.js:43evaluateScript @ Runtime.js:153scriptSourceLoaded @ Runtime.js:136
Runtime.js:367 TypeError: Cannot read property 'createSetting' of undefined
    at Object.WebInspector.FilterBar.setName (http://localhost:8080/ui/FilterBar.js:62:51)
    at Object.WebInspector.NetworkPanel (http://localhost:8080/network/NetworkPanel.js:47:21)
    at Function.WebInspector.NetworkPanel._instance (http://localhost:8080/network/NetworkPanel.js:408:53)
    at eval (http://localhost:8080/node/network/NetworkPanel.js:13:27)
    at eval (native)
    at evaluateScript (http://localhost:8080/Runtime.js:153:14)
    at scriptSourceLoaded (http://localhost:8080/Runtime.js:136:13)Runtime._reportError @ Runtime.js:367
InspectorBackend.js:185 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check 

I'm also unable to hit breakpoints, or inspect variables. Any help would be greatly appreciated!

**Comment by joshjung** [comment]
I'm experiencing a nearly identical issue. However, I can generally hit 'some' breakpoints but have been unable to determine which breakpoints it may or may not hit.

`joshuas-mbp:searchnode-edge jjung$ node -v
v5.5.0
joshuas-mbp:searchnode-edge jjung$ npm -v
3.3.12
joshuas-mbp:searchnode-edge jjung$ node-inspector -v
Node Inspector v0.12.6`

I experience the same issue whether I am using `node-debug` or `node --debug-brk` combined with `node-inspector`.
