### ISSUE TITLE
Installing latest on Debian & problems with node-gyp?

### ISSUE THREAD

**Issue by ChrisRus** [node-inspector/node-inspector#785]
I'm attempting to configure a new Debian 8.2 (64bit) work environment and did a clean install from source of Node 5.1.1, clean install of Chrome from Google, pulled all the latest development tools from Debian (running gcc 4.9.2).

I'm not sure if the errors I am encountering when attempting an `npm install -g node-inspector` as root are node-inspector rooted in node-inspector or local configuration problems and am hoping to get some advice on how best to proceed. (there are keywords in the console output that look like node-gyp discussions from a year ago here). But much has changed.

Here's what I'm seeing:

```
root@kestrel:~# npm install -g node-inspector
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN lifecycle v8-debug@0.6.1~preinstall: cannot run in wd %s %s (wd=%s) v8-debug@0.6.1 node -e 'process.exit(0)' /usr/local/lib/node_modules/.staging/v8-debug-d56ef3c156d39eeb44cda4964e0a85c5
npm WARN lifecycle v8-profiler@5.3.2~preinstall: cannot run in wd %s %s (wd=%s) v8-profiler@5.3.2   /usr/local/lib/node_modules/.staging/v8-profiler-700a09d0cc4475efe8f794ecb7f798e3
/usr/local/bin/node-inspector -> /usr/local/lib/node_modules/node-inspector/bin/inspector.js
/usr/local/bin/node-debug -> /usr/local/lib/node_modules/node-inspector/bin/node-debug.js

> bufferutil@1.2.1 install /usr/local/lib/node_modules/node-inspector/node_modules/bufferutil
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.1.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/node-inspector/node_modules/bufferutil/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/node-inspector/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/usr/local/lib/node_modules/node-inspector/node_modules/bufferutil/build'

> utf-8-validate@1.2.1 install /usr/local/lib/node_modules/node-inspector/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.1.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/node-inspector/node_modules/utf-8-validate/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/node-inspector/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/usr/local/lib/node_modules/node-inspector/node_modules/utf-8-validate/build'

> v8-debug@0.6.1 install /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

[v8-debug] Success: "/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.6.1/node-v47-linux-x64/debug.node" is installed via remote

> v8-profiler@5.3.2 install /usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.1.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler/build'
make: *** No rule to make target '../.node-gyp/5.1.1/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.3.2/node-v47-linux-x64/profiler.node" "--module_name=profiler" "--module_path=/usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.3.2/node-v47-linux-x64"
gyp ERR! cwd /usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler
gyp ERR! node -v v5.1.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.3.2/node-v47-linux-x64/profiler.node --module_name=profiler --module_path=/usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.3.2/node-v47-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/node-inspector/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 3.16.0-4-amd64
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/node-inspector/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler
node-pre-gyp ERR! node -v v5.1.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.17
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.3.2/node-v47-linux-x64/profiler.node --module_name=profiler --module_path=/usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.3.2/node-v47-linux-x64' (1)
npm WARN install:v8-profiler@5.3.2 v8-profiler@5.3.2 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:v8-profiler@5.3.2 Exit status 1
/usr/local/lib
└── (empty)

npm ERR! code 1
root@kestrel:~# 

```

The first thing that looks suspicious is the line:

```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.1.1"
```

Not sure why this would be: I'm running as root. This is a new VM and I have a snapshot so I just went ahead and created the missing directory as root, confirmed permissions, and tried again. Results were unchanged.

Later in the output we see a few ` --fallback-to-build` followed by subsequent `npm ERR! code 1`

Not entirely sure where to start with this. Any advice about how best to proceed would be appreciated. Thanks.

**Comment by 3y3** [comment]
Please try
```
npm i -g node-inspector --unsafe-perm
```

**Comment by ChrisRus** [comment]
@3y3 - sorry for the delay. I tried `npm i -g node-inspector --unsafe-perm` (executed as root) and this time received no build errors. Additionally, I'm single stepping through code and things look good. 

Curious, what have I actually done here? Will I need to take extra steps when next I upgrade for example?

Thank you very much!

**Comment by mfdeveloper** [comment]
I had the similar problem to install `v8-debugger` and `v8-profiler` dependencies, and the solution explained into: #776. Maybe this can be a solution for you too :)
