### ISSUE TITLE
files missing in Sources with node 5.2.0

### ISSUE THREAD

**Issue by peterwhitesell** [node-inspector/node-inspector#794]
os: ubuntu 14.04
node version: 5.2.0
node-inspector version: 0.12.5

After upgrading to node 5.2.0, when running with --no-preload flag, source files are no longer loaded into Node Inspector at runtime, when modules are required.
I'm running `...$ node-inspector --no-preload` and `...$ node --debug ./index.js`

index.js:
```Javascript
require('./server');
```

server.js:
```Javascript
require('http').createServer(function(req, res){
  console.log('received request');
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('Ok');
}).listen(3000, function(){
  console.log('app listening on port 3000');
});
```

only index.js appears in the Sources tab. I also see these errors in the chrome dev tools:
```shell
Assertion failed: Unknown experiment canvasInspectionRuntime._assert @ Runtime.js:358Runtime.ExperimentsSupport._checkExperiment @ Runtime.js:953Runtime.ExperimentsSupport.isEnabled @ Runtime.js:894WebInspector.ProfileTypeRegistry @ ProfileTypeRegistry.js:19(anonymous function) @ ProfileTypeRegistry.js:43evaluateScript @ Runtime.js:153scriptSourceLoaded @ Runtime.js:136
Runtime.js:367 TypeError: Cannot read property 'createSetting' of undefined
    at Object.WebInspector.FilterBar.setName (http://127.0.0.1:8080/ui/FilterBar.js:62:51)
    at Object.WebInspector.NetworkPanel (http://127.0.0.1:8080/network/NetworkPanel.js:47:21)
    at Function.WebInspector.NetworkPanel._instance (http://127.0.0.1:8080/network/NetworkPanel.js:408:53)
    at eval (http://127.0.0.1:8080/node/network/NetworkPanel.js:13:27)
    at eval (native)
    at evaluateScript (http://127.0.0.1:8080/Runtime.js:153:14)
    at scriptSourceLoaded (http://127.0.0.1:8080/Runtime.js:136:13)Runtime._reportError @ Runtime.js:367
ConsoleView.js:493 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
```

**Comment by ChrisGciso** [comment]
I see the same problem on Windows 10 Pro, Nodejs 5.2.0   My work around is to move all javascript files into the project root directory until this is resolved.

**Comment by 3y3** [comment]
There is a lot of problems with 5.2.0 - it breaks 20 tests in node-inspector
