### ISSUE TITLE
typeError on line break(point) when debugging

### ISSUE THREAD

**Issue by MathijsvVelde** [node-inspector/node-inspector#804]
I ran into a problem while debugging my node app and this specific error only occurs when I use a breaker (inline `debugger;` or/and **breakpoints** in the node-inspectors console).

The biggest issue for me is that is no indication of where the error originates from...

Here are my scenarios.:

debugging with `node debug ./app.js` results in:
```terminal
...
break in src/models/player.js:904

unhandled res:{"seq":587,"request_seq":1256,"type":"response","success":false,"message":"Internal error: TypeError: Cannot read property '0' of undefined"}
 902       }
 903       if (!this.currentSound.player.startedPlaying) {
>904         debugger;
 905         this.currentSound.player.playTrack(fade);
 906       } else {
debug> 
```

And debugging with `node --debug ./app.js` results in:
```
Internal error: TypeError: Cannot read property '0' of undefined
```
(in the node-inspectors console)

...any idea's?

**Comment by MathijsvVelde** [comment]
Node-Inspector crashed...

```
$ node-inspector --web-port=1234
```
output:
```terminal
Node Inspector v0.12.5
Visit http://127.0.0.1:1234/?ws=127.0.0.1:1234&port=5858 to start debugging.
undefined:1
TypeError: this.extendedProcessDebugJSONRequest_ is not a function
^

SyntaxError: Unexpected token T
    at Object.parse (native)
    at Protocol.execute (_debugger.js:117:43)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by loiclacombe** [comment]
Got the same 
> Internal error: TypeError: Cannot read property '0' of undefined
here, in chrome developper console, but not the same application.
Here are the steps to reproduce it:
- I launch `node-debug _mocha --compilers js:babel-register --recursive  --require test/components/testdom.js`
- mocha stops on a debugger break
- I resume in the debugger
- Doh !
I was just trying to debug a set of mocha tests with node-inspector

I am using: 
- node-inspector@0.12.5
- mocha@2.4.5
