### ISSUE TITLE
Node-debug doesn't work

### ISSUE THREAD

**Issue by myshov** [node-inspector/node-inspector#807]
Node-debug cause error:

```
$ node-debug test_file.js
Node Inspector is now available from http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858
Debugging `test_file.js`

internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOTDIR
    at exports._errnoException (util.js:874:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:339:9)
    at checkOthers (/Users/mysov/.nvm/versions/node/v4.2.1/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/lib/detect.js:124:16)
    at checkDarwin (/Users/mysov/.nvm/versions/node/v4.2.1/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/lib/detect.js:113:3)
    at next (/Users/mysov/.nvm/versions/node/v4.2.1/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/lib/detect.js:185:3)
    at /Users/mysov/.nvm/versions/node/v4.2.1/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/lib/detect.js:202:4
    at /Users/mysov/.nvm/versions/node/v4.2.1/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/lib/detect.js:105:7
    at Object.getPath [as path] (/Users/mysov/.nvm/versions/node/v4.2.1/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/lib/darwin/chrome.js:6:10)
    at /Users/mysov/.nvm/versions/node/v4.2.1/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/lib/detect.js:100:21
Debugger listening on port 5858
```

Node.js v4.2.1
Node Inspector v0.12.5
OS: Mac OS X 10.11.1

**Comment by rainabba** [comment]
Curious, try `node --debug test_file.js` and report if you get a crash with that alone. I'm having issues and tried to run the old way ( with --debug then node-inspector ) and my app is crashing with just --debug meaning is has nothing to do with node-inspector and I'm presently suspecting it's related to https://github.com/node-inspector/node-inspector/issues/823 since I'm lazy about .dir() vs .log() while in development (rarely use console in production thanks to Winston).

**Comment by cdaringe** [comment]
Hi all!

I have this issue as well.  I have a script that is reproducible too.

system info:

- node 4.4.3
- osx/mavericks
- npm 2.15.1

steps to reproduce:

- repo @ commit hash: https://github.com/MRN-Code/coinstac-client-core/commit/5a8c711736083dd29259bb69f706a5d768c4bdca
- clone, `npm i`
- `node-debug test/demo.js`

FYI, it _does_ work with nodes built-in cli debugger, e.g. `node debug test/demo.js`


```
cdieringer@Snapper-osx:~/node/coinstac-client-core$ node-debug test/demo.js
Node Inspector v0.12.8
Visit http://127.0.0.1:8080/?port=5858 to start debugging.
Debugging `test/demo.js`

Debugger listening on port 5858
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOTDIR
    at exports._errnoException (util.js:870:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at checkOthers (/usr/local/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/lib/detect.js:124:16)
    at checkDarwin (/usr/local/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/lib/detect.js:113:3)
    at next (/usr/local/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/lib/detect.js:185:3)
    at /usr/local/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/lib/detect.js:202:4
    at /usr/local/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/lib/detect.js:105:7
    at Object.getPath [as path] (/usr/local/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/lib/darwin/chrome.js:6:10)
    at /usr/local/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/lib/detect.js:100:21
cdieringer@Snapper-osx:~/node/coinstac-client-core$
```

**Comment by cdaringe** [comment]
it's an issue w/ browser-launcher2. will file a bug w/ them and cross ref. it would have to ripple up some before fixing `node-inspector` tho!
