### ISSUE TITLE
Error: node-inspector threw an error

### ISSUE THREAD

**Issue by MathijsvVelde** [node-inspector/node-inspector#813]
Node Inspector v0.12.5

running: (for a while during debugging...)
```terminal
$ node-inspector --web-port=1234
```

initial output:
```terminal
Node Inspector v0.12.5
Visit http://127.0.0.1:1234/?ws=127.0.0.1:1234&port=5858 to start debugging.
```

and then...:
```terminal
/usr/local/lib/node_modules/node-inspector/lib/DebuggerClient.js:181
      done(err, JSON.parse(result.value));
                                 ^

TypeError: Cannot read property 'value' of undefined
    at _handleEvaluateResponse (/usr/local/lib/node_modules/node-inspector/lib/DebuggerClient.js:181:34)
    at /usr/local/lib/node_modules/node-inspector/lib/DebuggerClient.js:136:7
    at Object.create.processResponse.value (/usr/local/lib/node_modules/node-inspector/lib/callback.js:23:20)
    at Debugger._processResponse (/usr/local/lib/node_modules/node-inspector/lib/debugger.js:95:21)
    at Protocol.execute (_debugger.js:120:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by JohanBeumer** [comment]
I am getting the same error when I try to start a debugging session for a nativescript app.
I start node-inspector on port 8181
In Google chrome I go to url : http://127.0.0.1:8181/debug?port=40001
At that time the same error as MathijsvVelde mentioned is thrown.

Can you look into this?
It's pretty hard to debug without the proper tooling.

Thanks in advance,
Johan Beumer

**Comment by ronie-z-wave** [comment]
Hi,

same occurs on my application after updating to latest v.12.7 ...
I'm using a ssh tunnel to debug my app directly on the server via port 8183 (Windows 7).

I've started node-inspector on port 8183 via windows commandline
``node-inspector --debug-port 8183``
no errors occured ...
and called it in google chrome with
http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=8183
... ui stops with same error in console like above.

> Can you look into this?
> It's pretty hard to debug without the proper tooling.

... there is nothing to add :)

Thanks,
Niels

**Comment by emimull** [comment]
Same here.

Node Inspector v0.12.8
