### ISSUE TITLE
custom port not working

### ISSUE THREAD

**Issue by tejasmanohar** [node-inspector/node-inspector#827]
```
$ node-debug bin/hubspot.js \
  --nodejs --harmony_destructuring \
  --web-port 3000
Node Inspector v0.12.6
Visit http://127.0.0.1:8080/?port=5858 to start debugging.
Debugging `bin/hubspot.js`

Debugger listening on port 5858
```

Why does it say visit :8080 when I asked for :3000? Is this a bug, or am I misunderstanding it?

**Comment by tejasmanohar** [comment]
@3y3 Moving issue from [here](https://github.com/node-inspector/node-inspector/issues/538#issuecomment-184895977) to this thread. In the docs - https://github.com/node-inspector/node-inspector#options -, it says 0.0.0.0 is the default value in the default column but in the description, it says "listens on 127.0.0.1 by default". Confused :confu]

**Comment by tejasmanohar** [comment]
@3y3 Saw latest response here- https://github.com/node-inspector/node-inspector/issues/538#issuecomment-184925364. I'll check on those two things and post back here instead of the old issue since that seems like a different question, not this bug.

**Comment by 3y3** [comment]
What will say
```
$ node-inspector --web-port 3000
```
Looks like a bug in passing options from `node-debug` to `node-inspector`

**Comment by tejasmanohar** [comment]
got it. now that it's running - it seems the web interface works for a bit until the inspector server crashes with the following error message-

```
$ node-inspector --web-host 0.0.0.0
Node Inspector v0.12.6
Visit http://127.0.0.1:8080/?port=5858 to start debugging.
Cannot send response - there is no front-end connection.
/usr/local/lib/node_modules/node-inspector/lib/NetworkAgent.js:79
    throw new Error('Data storage for request #' + requestId + ' already exists');
    ^

Error: Data storage for request #2686 already exists
    at NetworkAgent._registerInDataStorage (/usr/local/lib/node_modules/node-inspector/lib/NetworkAgent.js:79:11)
    at emitOne (events.js:90:13)
    at DebuggerClient.emit (events.js:182:7)
    at DebuggerClient._emitDebuggerEvent (/usr/local/lib/node_modules/node-inspector/lib/DebuggerClient.js:111:8)
    at emitOne (events.js:90:13)
    at Debugger.emit (events.js:182:7)
    at Debugger._processResponse (/usr/local/lib/node_modules/node-inspector/lib/debugger.js:102:10)
    at Protocol.execute (_debugger.js:120:14)
    at Protocol._newRes (_debugger.js:74:8)
    at Protocol.execute (_debugger.js:122:14)
```

so the web interface loses connection of course and gets a timeout request err code.

**Comment by lukebmay** [comment]
I am seeing a similar issue with `node-debug --web-port` option.  The browser window opens to the correct url but fails to load the code and the start debugging at the initial breakpoint.  For the record `node-debug src/app/app.js` works just fine.  The error I see occurs with all of these command-line options:

`node-debug --web-port=8008 src/app/app.js`
`node-debug --web-port 8008 src/app/app.js`
`node-debug -p 8008 src/app/app.js` 

Ubuntu 14.04
Chrome Version 49.0.2623.108 (64-bit)
node v5.9.1
npm 3.7.3
Node Inspector v0.12.7

Here is a screenshot:

![image](https://cloud.githubusercontent.com/assets/2091261/14196278/d54a3716-f790-11e5-9cbb-5f1fc83dea66.png)

**Comment by pacoita** [comment]
+1
Even using the same default port it fails, therefore it seems the issue is really related to how the parameter is processed:
 
`node-debug --web-port 8080 server.js`

**Comment by alvarocantador** [comment]
+1 using port redirection of the docker-compose
