### ISSUE TITLE
TypeError: rx.test is not a function

### ISSUE THREAD

**Issue by pedro93** [node-inspector/node-inspector#837]
Node-inspector module crashes when trying to access debug webpage.

```shell
Visit http://localhost:8080/?port=5858 to start debugging.
/Users/pedrosilva/Developer/Headless Server Browser/WebPage Downloader/node_modules/node-inspector/lib/ScriptFileStorage.js:278

    return exclude.some(function(rx) { return rx.test(rpath); });
                                                 ^

TypeError: rx.test is not a function
    at /Users/pedrosilva/Developer/Headless Server Browser/WebPage Downloader/node_modules/node-inspector/lib/ScriptFileStorage.js:278:50
    at Array.some (native)
    at excluded (/Users/pedrosilva/Developer/Headless Server Browser/WebPage Downloader/node_modules/node-inspector/lib/ScriptFileStorage.js:278:20)
    at /Users/pedrosilva/Developer/Headless Server Browser/WebPage Downloader/node_modules/node-inspector/lib/ScriptFileStorage.js:259:31
    at /Users/pedrosilva/Developer/Headless Server Browser/WebPage Downloader/node_modules/node-inspector/node_modules/async/lib/async.js:122:13
    at _each (/Users/pedrosilva/Developer/Headless Server Browser/WebPage Downloader/node_modules/node-inspector/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/Users/pedrosilva/Developer/Headless Server Browser/WebPage Downloader/node_modules/node-inspector/node_modules/async/lib/async.js:121:9)
    at /Users/pedrosilva/Developer/Headless Server Browser/WebPage Downloader/node_modules/node-inspector/lib/ScriptFileStorage.js:255:15
    at fn (/Users/pedrosilva/Developer/Headless Server Browser/WebPage Downloader/node_modules/node-inspector/node_modules/async/lib/async.js:638:34)
    at Immediate._onImmediate (/Users/pedrosilva/Developer/Headless Server Browser/WebPage Downloader/node_modules/node-inspector/node_modules/async/lib/async.js:554:34)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "debug"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! headless-tech-testing@0.0.1 debug: `node_modules/gulp/bin/gulp.js debug`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the headless-tech-testing@0.0.1 debug script 'node_modules/gulp/bin/gulp.js debug'.
npm ERR! This is most likely a problem with the headless-tech-testing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/gulp/bin/gulp.js debug
npm ERR! You can get their info via:
npm ERR!     npm owner ls headless-tech-testing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pedrosilva/Developer/Headless Server Browser/WebPage Downloader/npm-debug.log
```

I am using a gulp wrapper for node-inspector: https://github.com/koemei/gulp-node-inspector with the following gulp task:

```js
gulp.task('debug', function() {
    gulp.src([])
    .pipe(nodeInspector({
        webPort: 8080,
        webHost: 'localhost',
        saveLiveEdit: true,
        hidden: ['node_modules']
    }));
});
```

I am trying to debug a Q concurrent execution of functions, these functions will launch and execute external processes such as selenium and phantomjs. I don't know whether this may be a problem.

```js
function main(url) {
console.log("executing: "+url);
    Q.all([Phantomjs, Selenium].map(
        function(tech) { return execute(tech, url, "document.querySelector('html').outerHTML;"); }
    )).then(function(){
        stats.saveToFile();
    }).catch(function(err){
        //console.log("Algo se passou");
        console.log(err);
    });
}

function execute(tech, url, query){
    return tech.factory().create(url).then(function (process){
        stats.addEntry(process.driver);
        stats.setUrl(process.driver, url);
        stats.startTimer(process.driver);
        return process.execute(query).then(function(){
            stats.setStatus(process.driver,"Successful");
            process.handle();
        }).catch(function(err){
            console.log(err);
            stats.setStatus(process.driver,"Error");
            stats.setErrorText(process.driver,JSON.stringify(err));
            process.report(err);
        }).finally(function(){
            stats.endTimer(process.driver);
        });
    });
}
```
url is merely a string, e.g: "www.google.com"

Any help would be appreciated, thanks :)

**Comment by 3y3** [comment]
This is a problem in plugin.
In your case you can fix it by using
```js
hidden: [/node_modules/i]
```
https://github.com/koemei/gulp-node-inspector/pull/18
