### ISSUE TITLE
Install fails on v8-debug@0.7.6 preinstall script 'node -e 'process.exit(0)''

### ISSUE THREAD

**Issue by dmitrigrabov** [node-inspector/node-inspector#868]
I tried to re-install node-inspector because the network tab was not working. However, I get the following response when I try to do it. Any idea why the install might be failing?

```
holbmac0125:~ dmitri.grabov$ npm install node-inspector -g

> v8-profiler@5.6.3 preinstall /Users/dmitri.grabov/.npm-packages/lib/node_modules/.staging/v8-profiler-a21f5891
> npm install node-pre-gyp

/Users/dmitri.grabov/.npm-packages/bin/node-pre-gyp -> /Users/dmitri.grabov/.npm-packages/lib/node_modules/node-pre-gyp/bin/node-pre-gyp
/Users/dmitri.grabov/.npm-packages/lib
└── node-pre-gyp@0.6.28 


> v8-debug@0.7.6 preinstall /Users/dmitri.grabov/.npm-packages/lib/node_modules/.staging/v8-debug-7b9d93f1
> node -e 'process.exit(0)'

/Users/dmitri.grabov/.npm-packages/lib
└── (empty)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-inspector" "-g"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6
npm ERR! file sh
npm ERR! path sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn sh

npm ERR! v8-debug@0.7.6 preinstall: `node -e 'process.exit(0)'`
npm ERR! spawn sh ENOENT
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.6 preinstall script 'node -e 'process.exit(0)''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node -e 'process.exit(0)'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.
```

**Comment by dmash** [comment]
Same issue here... node 4.3.2 npm 3.8.5

**Comment by nodesocket** [comment]
👍  same issue.

**Comment by menocomp** [comment]
same issue for ubuntu 16
`20857 silly install printInstalled
20858 verbose stack Error: v8-debug@0.7.6 preinstall: `node -e 'process.exit(0)'`
20858 verbose stack spawn sh ENOENT
20858 verbose stack     at exports._errnoException (util.js:893:11)
20858 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
20858 verbose stack     at onErrorNT (internal/child_process.js:348:16)
20858 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
20858 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
20859 verbose pkgid v8-debug@0.7.6
20860 verbose cwd /home/sinedev/Development/sinecloud-api
20861 error Linux 4.4.0-22-generic
20862 error argv "/home/sinedev/.nvm/versions/node/v5.11.0/bin/node" "/home/sinedev/.nvm/versions/node/v5.11.0/bin/npm" "install" "-g" "node-inspector"
20863 error node v5.11.0
20864 error npm  v3.8.6
20865 error file sh
20866 error path sh
20867 error code ELIFECYCLE
20868 error errno ENOENT
20869 error syscall spawn sh
20870 error v8-debug@0.7.6 preinstall: `node -e 'process.exit(0)'`
20870 error spawn sh ENOENT
20871 error Failed at the v8-debug@0.7.6 preinstall script 'node -e 'process.exit(0)''.
20871 error Make sure you have the latest version of node.js and npm installed.
20871 error If you do, this is most likely a problem with the v8-debug package,
20871 error not with npm itself.
20871 error Tell the author that this fails on your system:
20871 error     node -e 'process.exit(0)'
20871 error You can get information on how to open an issue for this project with:
20871 error     npm bugs v8-debug
20871 error Or if that isn't available, you can get their info via:
20871 error     npm owner ls v8-debug
20871 error There is likely additional logging output above.`

**Comment by dmitrigrabov** [comment]
Install was working on another mac, which was running node v4.2.6, however after I used `nvm` to upgrade to node v5.11.1, I am getting the same error as above in first post

**Comment by PeterWoodITG** [comment]
Same issue in Windows 7,   node v4.2.3 npm  v3.8.9, as well as with bleading edge: node v6.1.0
npm  v3.9.0 (as well as 3.8.9)
The the c:\itg\npm directory was freshly created by npm via same user executing. Error is strange.
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "c:\\itg\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-pre-gyp"
npm ERR! node v6.1.0
npm ERR! npm  v3.9.0
npm ERR! path c:\itg\npm\node_modules\.staging\v8-profiler-b06770e7
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rmdir

npm ERR! EBUSY: resource busy or locked, rmdir 'c:\itg\npm\node_modules\.staging\v8-profiler-b06770e7'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\itg\npm\node_modules\.staging\v8-profiler-b06770e7\npm-debug.log

> v8-debug@0.7.7 preinstall c:\itg\npm\node_modules\.staging\v8-debug-def3ebc3
> node -e 'process.exit(0)'

c:\itg\npm
`-- (empty)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "c:\\itg\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-inspector"
npm ERR! node v6.1.0
npm ERR! npm  v3.9.0
npm ERR! code ELIFECYCLE

npm ERR! v8-profiler@5.6.3 preinstall: `npm install node-pre-gyp`
npm ERR! Exit status 4294963214
npm ERR!
npm ERR! Failed at the v8-profiler@5.6.3 preinstall script 'npm install node-pre-gyp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install node-pre-gyp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-profiler
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\wood\npm-debug.log
npm ERR! code 1

C:\Users\wood>
```

**Comment by jamesdixon** [comment]
Same here as well. Running Node 6.1/NPM 3.8.6 on a Mac

**Comment by markmcdermid** [comment]
Something's version is creeping up and breaking it, I don't have enough experience to find out what it is but I've forked it and removed all the ^ and ~ from the version numbers in the package.json and it works. 

I think it's working now but I've never used node-inspector before so not sure if it's 100% working. 

Feel free to install it from my git repo for now until someone smarter finds out :)

`npm install git+https://github.com/markmcdermid/node-inspector.git -g`

**Comment by romellem** [comment]
@markmcdermid thanks, that worked for me.

**Comment by jamesdixon** [comment]
Tried @markmcdermid's version, but unfortunately still breaking (different error) on Node 6.1

```
 npm install git+https://github.com/markmcdermid/node-inspector.git -g

> v8-profiler@5.6.0 preinstall /Users/jamesdixon/.nvm/versions/node/v6.1.0/lib/node_modules/.staging/v8-profiler-3abaa16c
> node -e 'process.exit(0)'


> v8-debug@0.7.1 preinstall /Users/jamesdixon/.nvm/versions/node/v6.1.0/lib/node_modules/.staging/v8-debug-47343fa9
> node -e 'process.exit(0)'

/Users/jamesdixon/.nvm/versions/node/v6.1.0/bin/node-debug -> /Users/jamesdixon/.nvm/versions/node/v6.1.0/lib/node_modules/node-inspector/bin/node-debug.js
/Users/jamesdixon/.nvm/versions/node/v6.1.0/bin/node-inspector -> /Users/jamesdixon/.nvm/versions/node/v6.1.0/lib/node_modules/node-inspector/bin/inspector.js

> v8-profiler@5.6.0 install /Users/jamesdixon/.nvm/versions/node/v6.1.0/lib/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-inspector.s3.amazonaws.com/profiler/v5.6.0/node-v48-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.6.0 and node@6.1.0 (node-v48 ABI) (falling back to source compile with node-gyp)
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/profiler/src/profiler.o
In file included from ../src/profiler.cc:2:
../node_modules/nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in
      'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in
      'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in
      'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in
      'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
make: *** [Release/obj.target/profiler/src/profiler.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jamesdixon/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/jamesdixon/.nvm/versions/node/v6.1.0/bin/node" "/Users/jamesdixon/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/jamesdixon/.nvm/versions/node/v6.1.0/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.6.0/node-v48-darwin-x64/profiler.node" "--module_name=profiler" "--module_path=/Users/jamesdixon/.nvm/versions/node/v6.1.0/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.6.0/node-v48-darwin-x64"
gyp ERR! cwd /Users/jamesdixon/.nvm/versions/node/v6.1.0/lib/node_modules/node-inspector/node_modules/v8-profiler
gyp ERR! node -v v6.1.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/jamesdixon/.nvm/versions/node/v6.1.0/bin/node /Users/jamesdixon/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/jamesdixon/.nvm/versions/node/v6.1.0/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.6.0/node-v48-darwin-x64/profiler.node --module_name=profiler --module_path=/Users/jamesdixon/.nvm/versions/node/v6.1.0/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.6.0/node-v48-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/jamesdixon/.nvm/versions/node/v6.1.0/lib/node_modules/node-inspector/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Darwin 14.5.0
node-pre-gyp ERR! command "/Users/jamesdixon/.nvm/versions/node/v6.1.0/bin/node" "/Users/jamesdixon/.nvm/versions/node/v6.1.0/lib/node_modules/node-inspector/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/jamesdixon/.nvm/versions/node/v6.1.0/lib/node_modules/node-inspector/node_modules/v8-profiler
node-pre-gyp ERR! node -v v6.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok
Failed to execute '/Users/jamesdixon/.nvm/versions/node/v6.1.0/bin/node /Users/jamesdixon/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/jamesdixon/.nvm/versions/node/v6.1.0/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.6.0/node-v48-darwin-x64/profiler.node --module_name=profiler --module_path=/Users/jamesdixon/.nvm/versions/node/v6.1.0/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.6.0/node-v48-darwin-x64' (1)
/Users/jamesdixon/.nvm/versions/node/v6.1.0/lib
└── (empty)

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/jamesdixon/.nvm/versions/node/v6.1.0/bin/node" "/Users/jamesdixon/.nvm/versions/node/v6.1.0/bin/npm" "install" "git+https://github.com/markmcdermid/node-inspector.git" "-g"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! v8-profiler@5.6.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler@5.6.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-profiler
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jamesdixon/Projects/scout/platform/api/npm-debug.log
npm ERR! code 1
```

Anyone else having the same issue?

**Comment by fend25** [comment]
+1
 - OS: windows 7 x64
 - node v6.1.0
 - npm v3.3.3

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\myuser\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-pre-gyp"
npm ERR! node v6.1.0
npm ERR! npm  v3.3.3
npm ERR! path C:\Users\myuser\AppData\Roaming\npm\node_modules\.staging\v8-profiler-ab65d3a27e7b1c6263729d941ff086d2
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rmdir

npm ERR! EBUSY: resource busy or locked, rmdir 'C:\Users\myuser\AppData\Roaming\npm\node_modules\.staging\v8-profiler-ab65d3a27e7b1c6263729d941ff086d2'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\myuser\AppData\Roaming\npm\node_modules\.staging\v8-profiler-ab65d3a27e7b1c6263729d941ff086d2\npm-debug.log
npm WARN install:v8-profiler v8-profiler@5.6.3 preinstall: `npm install node-pre-gyp`
npm WARN install:v8-profiler Exit status 4294963214

> v8-debug@0.7.7 preinstall C:\Users\myuser\AppData\Roaming\npm\node_modules\.staging\v8-debug-1699ab804c4acda23201f5f278b94854
> node -e 'process.exit(0)'

npm WARN install:v8-debug v8-debug@0.7.7 preinstall: `node -e 'process.exit(0)'`
npm WARN install:v8-debug spawn C:\Windows\system32\cmd.exe ENOENT
npm WARN install:v8-debug v8-debug@0.7.7 preinstall: `node -e 'process.exit(0)'`
npm WARN install:v8-debug Exit status -4058
```

**Comment by 3y3** [comment]
Can anyone to reinstall node-inspector now? I release new v8-profiler version which should fix this problem.

**Comment by mhingston** [comment]
Just tried with node 6.1.0, npm 3.9.0, OS X 10.11.4. Installed fine.

**Comment by fend25** [comment]
@3y3 thank you, node-inspector has been installed and now working fine. win7 x64, node v6.1.0

**Comment by abernix** [comment]
@3y3 I can confirm that it is also fixed.  Thanks!

**Comment by cosmosb** [comment]
Yay..success with Node v6.1.0 on Windows 10. Thanks.

**Comment by talbenbasat** [comment]
+1
I'm with ubuntu 14.10 64bit
node 0.6.2
npm 3.8.9

the installation from git fails with
node-pre-gyp ERR! Tried to download: https://node-inspector.s3.amazonaws.com/profiler/v5.6.0/node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.6.0 and node@6.2.0 (node-v48 ABI) (falling back to source compile with node-gyp) 

reinstall not working

reinstalling with target 1.6.3/1.8.3 not working either

**Comment by davidhhuan** [comment]
osx, the same issue

```
> v8-debug@0.7.7 install /usr/local/lib/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v47-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@5.0.0 (node-v47 ABI) (falling back to source compile with node-gyp) 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: unable to verify the first certificate
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1044:38)
gyp ERR! stack     at emitNone (events.js:67:13)
gyp ERR! stack     at TLSSocket.emit (events.js:166:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:581:8)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/v8-debug/build/debug/v0.7.7/node-v47-darwin-x64/debug.node" "--module_name=debug" "--module_path=/usr/local/lib/node_modules/v8-debug/build/debug/v0.7.7/node-v47-darwin-x64"
gyp ERR! cwd /usr/local/lib/node_modules/v8-debug
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/5.0.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/v8-debug/build/debug/v0.7.7/node-v47-darwin-x64/debug.node --module_name=debug --module_path=/usr/local/lib/node_modules/v8-debug/build/debug/v0.7.7/node-v47-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/v8-debug/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 14.5.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/lib/node_modules/v8-debug/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/v8-debug
node-pre-gyp ERR! node -v v5.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok
```

**Comment by colkito** [comment]
This works for me https://github.com/node-inspector/v8-debug/issues/7#issuecomment-154450807

**Comment by stefek99** [comment]
```npm --version
3.10.9
node --version
v7.2.1
verbose stack Error: v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
verbose stack Exit status 1
```

**Comment by XiaoLiz** [comment]
Same here As well,  node version 7.4.0  npm version 4.0.5 OS X 10.12.3 Installed fail

 Resolvent: Using nrm tools switch node version 6.2.0  success！
  

sudo npm install electron-inspector --save-dev
Password:
npm WARN lifecycle v8-debug@0.7.7~preinstall: cannot run in wd %s %s (wd=%s) v8-debug@0.7.7 node -e 'process.exit(0)' /Users/liyi/Desktop/desktop-app/node_modules/.staging/v8-debug-d903ba5d
npm WARN lifecycle v8-profiler@5.6.5~preinstall: cannot run in wd %s %s (wd=%s) v8-profiler@5.6.5 node -e 'process.exit(0)' /Users/liyi/Desktop/desktop-app/node_modules/.staging/v8-profiler-8c938cc1

> v8-debug@0.7.7 install /Users/liyi/Desktop/desktop-app/node_modules/electron-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

[v8-debug] Success: "/Users/liyi/Desktop/desktop-app/node_modules/electron-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v48-darwin-x64/debug.node" is installed via remote

> v8-profiler@5.6.5 install /Users/liyi/Desktop/desktop-app/node_modules/electron-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

[v8-profiler] Success: "/Users/liyi/Desktop/desktop-app/node_modules/electron-inspector/node_modules/v8-profiler/build/profiler/v5.6.5/node-v48-darwin-x64/profiler.node" is installed via remote
/Users/liyi/Desktop/desktop-app
└─┬ electron-inspector@0.1.4
  ├── node-inspector@0.12.8  (git://github.com/enlight/node-inspector.git#accd46758501d8187e55b32b54e3eff65c3fdaa3)
  ├── v8-debug@0.7.7
  └── v8-profiler@5.6.5  (git://github.com/enlight/v8-profiler.git#dc3a4e15f06dd6eaca705e69e235d21d5962eaf5)

@mhingston   Thank you so much！

**Comment by hustxiaoc** [comment]
Try `node-inspector@1.1.0` please.

**Comment by tinhnqjp** [comment]
Same error:
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@8.9.4 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)

I try and OK:
npm install -g node-inspector@0.7.5
