### ISSUE TITLE
node inspector not installing on windows-10

### ISSUE THREAD

**Issue by mzzn28** [node-inspector/node-inspector#882]
new to node, trying to install node inspector getting the following error, also tried after node-gyp

node-pre-gyp ERR! Tried to download: https://node-inspector.s3.amazonaws.com/deb
ug/v0.7.7/node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@6.2.0
 (node-v48 ABI) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targe
ts(362,5): warning MSB8003: Could not find WindowsSDKDir variable from the regi
stry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid versi
on number. [C:\Users\212569005\AppData\Roaming\npm\node_modules\node-inspector\
node_modules\v8-debug\build\debug.vcxproj]
  debug.cc
  InjectedScriptHost.cc
c:\users\212569005\.node-gyp\6.2.0\include\node\v8.h(18): fatal error C1083: Ca
nnot open include file: 'stddef.h': No such file or directory (..\src\InjectedS
criptHost.cc) [C:\Users\212569005\AppData\Roaming\npm\node_modules\node-inspect
or\node_modules\v8-debug\build\debug.vcxproj]
c:\users\212569005\.node-gyp\6.2.0\include\node\v8.h(18): fatal error C1083: Ca
nnot open include file: 'stddef.h': No such file or directory (..\src\debug.cc)
 [C:\Users\212569005\AppData\Roaming\npm\node_modules\node-inspector\node_modul
es\v8-debug\build\debug.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\212569005\AppData\Roaming\np
m\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:204:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\212569005\\Ap
pData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallba
ck-to-build" "--module=C:\\Users\\212569005\\AppData\\Roaming\\npm\\node_modules
\\node-inspector\\node_modules\\v8-debug\\build\\debug\\v0.7.7\\node-v48-win32-x
64\\debug.node" "--module_name=debug" "--module_path=C:\\Users\\212569005\\AppDa
ta\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\v8-debug\\build\\d
ebug\\v0.7.7\\node-v48-win32-x64"
gyp ERR! cwd C:\Users\212569005\AppData\Roaming\npm\node_modules\node-inspector\
node_modules\v8-debug
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.e
xe C:\Users\212569005\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js
build --fallback-to-build --module=C:\Users\212569005\AppData\Roaming\npm\node_m
odules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v48-win32-x6
4\debug.node --module_name=debug --module_path=C:\Users\212569005\AppData\Roamin
g\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-
v48-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\212569005\AppD
ata\Roaming\npm\node_modules\node-inspector\node_modules\node-pre-gyp\lib\util\c
ompile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:215:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\2125
69005\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\node-p
re-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\212569005\AppData\Roaming\npm\node_modules\node-i
nspector\node_modules\v8-debug
node-pre-gyp ERR! node -v v6.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\212569005\AppData\R
oaming\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --mod
ule=C:\Users\212569005\AppData\Roaming\npm\node_modules\node-inspector\node_modu
les\v8-debug\build\debug\v0.7.7\node-v48-win32-x64\debug.node --module_name=debu
g --module_path=C:\Users\212569005\AppData\Roaming\npm\node_modules\node-inspect
or\node_modules\v8-debug\build\debug\v0.7.7\node-v48-win32-x64' (1)
C:\Users\212569005\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-inspector"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fal
lback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\212569005\mygit\DMP-Reporting\npm-debug.log
npm ERR! code 1

C:\Users\212569005\mygit\DMP-Reporting>node gyp -v
module.js:442
    throw err;
    ^

Error: Cannot find module 'C:\Users\212569005\mygit\DMP-Reporting\gyp'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3

**Comment by Talento90** [comment]
Have you installed visual studio C++ and Python 2.7? It's a requirement when working with node gyp.

**Comment by mzzn28** [comment]
thanks, yes,It did work after setting up VS C++ environment.  It took me half day to figure out this problem.

**Comment by Talento90** [comment]
I'm glad that I could help you! 

If possible close the issue :)

**Comment by vrudhay** [comment]
I have installed VC++ 2017 of course - but not working.
