### ISSUE TITLE
Is it a bug? After some seconds the debug crash!

### ISSUE THREAD

**Issue by rafael-freitas** [node-inspector/node-inspector#885]
$ node-inspector
Node Inspector v0.12.5
Visit http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858 to start debugging.
/usr/local/lib/node_modules/node-inspector/lib/FrontendCommandHandler.js:140
      domainAndMethod = fullMethodName.split('.'),
                                      ^

TypeError: Cannot read property 'split' of undefined
    at Object.FrontendCommandHandler.handleCommand (/usr/local/lib/node_modules/node-inspector/lib/FrontendCommandHandler.js:140:39)
    at Object.FrontendCommandHandler._handleFrontendMessage (/usr/local/lib/node_modules/node-inspector/lib/FrontendCommandHandler.js:128:10)
    at emitOne (events.js:77:13)
    at FrontendClient.emit (events.js:169:7)
    at FrontendClient._onConnectionMessage (/usr/local/lib/node_modules/node-inspector/lib/FrontendClient.js:40:8)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (/usr/local/lib/node_modules/node-inspector/node_modules/ws/lib/WebSocket.js:816:10)
    at /usr/local/lib/node_modules/node-inspector/node_modules/ws/lib/Receiver.js:477:18
    at /usr/local/lib/node_modules/node-inspector/node_modules/ws/lib/Receiver.js:361:7

**Comment by Pajn** [comment]
I have the same problem

```
Node Inspector v0.12.8
Visit http://127.0.0.1:8080/?port=5858 to start debugging.
Debugging `dist/lib/cetti.js`

Debugger listening on port 5858
/home/rasmus/.nvm/versions/node/v5.5.0/lib/node_modules/node-inspector/lib/FrontendCommandHandler.js:140
      domainAndMethod = fullMethodName.split('.'),
                                      ^

TypeError: Cannot read property 'split' of undefined
    at Object.FrontendCommandHandler.handleCommand (/home/rasmus/.nvm/versions/node/v5.5.0/lib/node_modules/node-inspector/lib/FrontendCommandHandler.js:140:39)
    at Object.FrontendCommandHandler._handleFrontendMessage (/home/rasmus/.nvm/versions/node/v5.5.0/lib/node_modules/node-inspector/lib/FrontendCommandHandler.js:128:10)
    at emitOne (events.js:90:13)
    at FrontendClient.emit (events.js:182:7)
    at FrontendClient._onConnectionMessage (/home/rasmus/.nvm/versions/node/v5.5.0/lib/node_modules/node-inspector/lib/FrontendClient.js:40:8)
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
    at Receiver.ontext (/home/rasmus/.nvm/versions/node/v5.5.0/lib/node_modules/node-inspector/node_modules/ws/lib/WebSocket.js:841:10)
    at /home/rasmus/.nvm/versions/node/v5.5.0/lib/node_modules/node-inspector/node_modules/ws/lib/Receiver.js:536:18
    at /home/rasmus/.nvm/versions/node/v5.5.0/lib/node_modules/node-inspector/node_modules/ws/lib/Receiver.js:368:7
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:856:11)
    at TCP.onread (net.js:544:26)
```
