### ISSUE TITLE
node-debug on windows doesn't work.

### ISSUE THREAD

**Issue by pps83** [node-inspector/node-inspector#918]
It's kind of unclear if `node-debug script.js` should work on windows. Is it supposed to work?
In my case it does not work, I get this error:

```
C:\test>node-debug test.js
Node Inspector v0.12.8
Visit http://127.0.0.1:8080/?port=5858 to start debugging.
Debugging `test.js`

Debugger listening on [::]:5858
C:\Users\pps\AppData\Roaming\npm\node_modules\node-inspector\lib\InjectorClient.js:111
      cb(error, NM[0].ref);
                     ^

TypeError: Cannot read property 'ref' of undefined
    at InjectorClient.<anonymous> (C:\Users\pps\AppData\Roaming\npm\node_modules\node-inspector\lib\InjectorClient.js:111:22)
    at C:\Users\pps\AppData\Roaming\npm\node_modules\node-inspector\lib\DebuggerClient.js:121:7
    at Object.value (C:\Users\pps\AppData\Roaming\npm\node_modules\node-inspector\lib\callback.js:23:20)
    at Debugger._processResponse (C:\Users\pps\AppData\Roaming\npm\node_modules\node-inspector\lib\debugger.js:95:21)
    at Protocol.execute (_debugger.js:121:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:564:26)

C:\test>
```
while I get that error in console I get chrome-inspector started and I always get [this error there](http://i.imgur.com/zquGeUg.png).

**Comment by amelon** [comment]
just install a fresh version of node-inspector and I get the same error.

node version: 6.5.0
win7

**Comment by amelon** [comment]
The problem is here: https://github.com/node-inspector/node-inspector/blob/master/lib/InjectorClient.js#L98-L113

````
InjectorClient.prototype._findNMInScope = function(funcHandle, cb) {
    this._debuggerClient.request('scope', {
      functionHandle: funcHandle
    }, function(error, result, refs) {
      if (error) return cb(error);

      var NM = refs[result.object.ref].properties.filter(function(prop) {
        return prop.name == 'NativeModule';
      });

      if (!NM.length)
        error = new Error('No NativeModule in target scope');

      cb(error, NM[0].ref);
    }.bind(this));
};
````

Test `if (!NM.length)` should call cb and return

````
InjectorClient.prototype._findNMInScope = function(funcHandle, cb) {
    this._debuggerClient.request('scope', {
      functionHandle: funcHandle
    }, function(error, result, refs) {
      if (error) return cb(error);

      var NM = refs[result.object.ref].properties.filter(function(prop) {
        return prop.name == 'NativeModule';
      });

      if (!NM.length)
        return cb(new Error('No NativeModule in target scope'));

      cb(error, NM[0].ref);
    }.bind(this));
};
````

**Comment by 15920353089** [comment]
@amelon how can i do this error?

**Comment by amelon** [comment]
what do you mean?

**Comment by 15920353089** [comment]
just I see others:

Try this hack/workaround
Seek in /usr/lib64/node_modules/node-inspector/lib/InjectorClient.js (your location of node-inspector)
Look at
Function InjectorClient.prototype._getFuncWithNMInScope

Replace this

cb(null, result.handle);
with this

cb(null, result.constructorFunction.ref);
I have this message in node-ispector console tab

Internal error: TypeError: Cannot read property '0' of undefined
But breakpoints and other stuff works.
Tested with 6.6.0

P.s.
Seems node-inspector method for retrieval NativeModule link fails to handle -1 even with #906 or similar because this solves problem with response, but not with request.
You will recieve this message

Error: No NativeModule in target scope
and you will not able to go through breakpoints with node-inspector's UI.

**Comment by JasonKleban** [comment]
@15920353089 👍  This happens for me too following your hack.

**Comment by sc0ttwad3** [comment]
Same error for me using __node v7.0.0__, __node-inspector v0.12.8__:

    \AppData\Roaming\npm\node_modules\node-inspector\lib\InjectorClient.js:111
      cb(error, NM[0].ref);
                     ^

    TypeError: Cannot read property 'ref' of undefined
    at InjectorClient.<anonymous> (\AppData\Roaming\npm\node_modules\node-inspector\lib\InjectorClient.js:111:22)
    at C\AppData\Roaming\npm\node_modules\node-inspector\lib\DebuggerClient.js:121:7
    at Object.value (\AppData\Roaming\npm\node_modules\node-inspector\lib\callback.js:23:20)

    at Debugger._processResponse (\AppData\Roaming\npm\node_modules\node-inspector\lib\debugger.js:95:21)
    at Protocol.execute (_debugger.js:121:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
    events.js:160
      throw er; // Unhandled 'error' event
      ^

    Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:572:26)


Using __npm v4.0.1__ no problems installing dependencies, however using __yarn v0.16.1__ an install went bezerk, investigating that issue as well, most likely unrelated.

**Comment by Muzietto** [comment]
Same issue for me:
- node 6.9.4
- node-inspector 0.12.8
- win7pro || win10

Using workaround above, with many thanks to 15920353089
