### ISSUE TITLE
'console.group' is not a function

### ISSUE THREAD

**Issue by ncuillery** [node-inspector/node-inspector#923]
node-inspector seems to handle the "console group API" https://github.com/node-inspector/node-inspector/search?l=javascript&q=group+collapsed&type=Code&utf8=%E2%9C%93 but when I'm trying to use it, I get an error 

```
TypeError: console.group is not a function
    at Object.<anonymous> (/Users/ncuillery/app.js:1:71)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Timeout.Module.runMain [as _onTimeout] (module.js:575:10)
    at tryOnTimeout (timers.js:228:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

How can I get this working ?

Node Inspector v0.12.8, Chrome 52, Mac OS El Capitan, tested in the REPL and the UI console tab as well.

**Comment by hustxiaoc** [comment]
Sorry, `console.group` does not exists in node.
