### ISSUE TITLE
Errors while installing node-inspector ELIFECYCLE

### ISSUE THREAD

**Issue by sharikovvladislav** [node-inspector/node-inspector#944]
I have problem while installing node-inspector. How I can solve it?

I am using Win 7 x64 and latest versions of node and npm.

Short log and versions of node and npm (top of the log):
```
Vlad@VladPC MINGW64 /
$ node -v
v7.0.0

Vlad@VladPC MINGW64 /
$ npm -v
3.10.6

Vlad@VladPC MINGW64 /
$ npm i node-inspector -g

> v8-debug@0.7.7 preinstall C:\Users\Vlad\AppData\Roaming\npm\node_modules\.staging\v8-debug-2b753200
> node -e 'process.exit(0)'


> v8-profiler@5.6.5 preinstall C:\Users\Vlad\AppData\Roaming\npm\node_modules\.staging\v8-profiler-2c6d4476
> node -e 'process.exit(0)'

C:\Users\Vlad\AppData\Roaming\npm\node-inspector -> C:\Users\Vlad\AppData\Roaming\npm\node_modules\node-inspector\bin\inspector.js
C:\Users\Vlad\AppData\Roaming\npm\node-debug -> C:\Users\Vlad\AppData\Roaming\npm\node_modules\node-inspector\bin\node-debug.js

> v8-debug@0.7.7 install C:\Users\Vlad\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.0.0 (node-v51 ABI) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  debug.cc
  InjectedScriptHost.cc
..\src\debug.cc(38): error C2660: v8::Debug::Call: ▒㭪▒▒ ▒▒ ▒ਭ▒▒▒▒▒ 1 ▒▒㬥▒⮢ [C:\Users\Vlad\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug.vcxproj]
..\src\debug.cc(46): error C2660: v8::Debug::GetDebugContext: ▒㭪▒▒ ▒▒ ▒ਭ▒▒▒▒▒ 0 ▒▒㬥▒⮢ [C:\Users\Vlad\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug.vcxproj]
..\src\debug.cc(46): error C2227: ▒▒ࠦ▒▒▒▒ ᫥▒▒ ▒▒ "->GetIsolate" ▒▒▒▒▒▒ 㪠▒뢠▒▒ ▒▒ ⨯ ▒▒▒▒▒, ▒▒▒▒▒▒▒▒ ▒▒▒ ▒▒ꥤ▒▒▒▒▒▒ ▒▒▒▒ ▒▒ 㭨▒▒▒ᠫ▒▒ ⨯ [C:\Users\Vlad\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug.vcxproj]
..\src\debug.cc(61): error C2660: v8::Debug::GetDebugContext: ▒㭪▒▒ ▒▒ ▒ਭ▒▒▒▒▒ 0 ▒▒㬥▒⮢ [C:\Users\Vlad\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug.vcxproj]
..\src\debug.cc(66): error C2660: v8::Debug::GetDebugContext: ▒㭪▒▒ ▒▒ ▒ਭ▒▒▒▒▒ 0 ▒▒㬥▒⮢ [C:\Users\Vlad\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Vlad\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\Dev\\nodejs\\node.exe" "C:\\Users\\Vlad\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\Vlad\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\v8-debug\\build\\debug\\v0.7.7\\node-v51-win32-x64\\debug.node" "--module_name=debug" "--module_path=C:\\Users\\Vlad\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\v8-debug\\build\\debug\\v0.7.7\\node-v51-win32-x64"
gyp ERR! cwd C:\Users\Vlad\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'D:\Dev\nodejs\node.exe C:\Users\Vlad\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Vlad\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64\debug.node --module_name=debug --module_path=C:\Users\Vlad\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Vlad\AppData\Roaming\npm\node_modules\node-inspector\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "D:\\Dev\\nodejs\\node.exe" "C:\\Users\\Vlad\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Vlad\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug
node-pre-gyp ERR! node -v v7.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok
Failed to execute 'D:\Dev\nodejs\node.exe C:\Users\Vlad\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Vlad\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64\debug.node --module_name=debug --module_path=C:\Users\Vlad\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64' (1)
C:\Users\Vlad\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Dev\\nodejs\\node.exe" "C:\\Users\\Vlad\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "node-inspector" "-g"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Program Files\Git\npm-debug.log
npm ERR! code 1

```

Here is full log (npm-debug.log): http://dropmefiles.com/mVdr5

**Comment by fend25** [comment]
yep, same error
win7 x64
node v7.2.0
npm v3.9.0
node-inspector v0.12.8

**Comment by yaodehaung** [comment]
how to save process??

**Comment by athergeek** [comment]
i am using node 6.9.2 and i am getting same error

```
node-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@6.9.2 (node-v48 ABI) (falling back to source compile with node-gyp)
gyp WARN install got an error, rolling back install
gyp ERR! configure error
```

**Comment by jucajuca** [comment]
Same error here:

---> npm install -g node-inspector:

npm ERR! Linux 4.4.38-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "node-inspector"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/sharelatex/web/modules/npm-debug.log
npm ERR! code 1
