### ISSUE TITLE
Installation failed on  Debian (3.2.0-4-amd64 #1 SMP Debian 3.2.82-1 x86_64 GNU/Linux)

### ISSUE THREAD

**Issue by malickit** [node-inspector/node-inspector#952]
root@appserver:~# npm install -g node-inspector
npm WARN lifecycle v8-debug@0.7.7~preinstall: cannot run in wd %s %s (wd=%s) v8-debug@0.7.7 node -e 'process.exit(0)' /root/.nvm/versions/node/v7.1.0/lib/node_modules/.staging/v8-debug-2eb2bec8
npm WARN lifecycle v8-profiler@5.6.5~preinstall: cannot run in wd %s %s (wd=%s) v8-profiler@5.6.5 node -e 'process.exit(0)' /root/.nvm/versions/node/v7.1.0/lib/node_modules/.staging/v8-profiler-ca0424c0
/root/.nvm/versions/node/v7.1.0/bin/node-inspector -> /root/.nvm/versions/node/v7.1.0/lib/node_modules/node-inspector/bin/inspector.js
/root/.nvm/versions/node/v7.1.0/bin/node-debug -> /root/.nvm/versions/node/v7.1.0/lib/node_modules/node-inspector/bin/node-debug.js

> v8-debug@0.7.7 install /root/.nvm/versions/node/v7.1.0/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

sh: 1: node-pre-gyp: Permission denied
/root/.nvm/versions/node/v7.1.0/lib
└── (empty)

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/root/.nvm/versions/node/v7.1.0/bin/node" "/root/.nvm/versions/node/v7.1.0/bin/npm" "install" "-g" "node-inspector"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/meanjs/npm-debug.log
npm ERR! code 1

Any idea please ?

**Comment by mdjekic** [comment]
Having the same problem on macOS Sierra v10.12

**Comment by kalch** [comment]
Same issue with macOS Sierra v10.12.1, node v7.2.0, npm  v4.0.2 or yarn v0.17.9 i.e. This fails - 
node-pre-gyp install --fallback-to-build

**Comment by hpohlmeyer** [comment]
Same problem.

    MacOS Sierra: 10.12.1
    Node: 7.2.0
    NPM: 3.10.9

Also using `npm -g node-inspector`.

**Comment by simonmysun** [comment]
Mein is npm at 4.0.3 on Archlinux(4.8.11-1-ARCH). node is at v7.2.1

```
# npm install -g node-inspector
npm WARN lifecycle v8-debug@0.7.7~preinstall: cannot run in wd %s %s (wd=%s) v8-debug@0.7.7 node -e 'process.exit(0)' /usr/lib/node_modules/.staging/v8-debug-8568d751
npm WARN lifecycle v8-profiler@5.6.5~preinstall: cannot run in wd %s %s (wd=%s) v8-profiler@5.6.5 node -e 'process.exit(0)' /usr/lib/node_modules/.staging/v8-profiler-590bc5bb
/usr/bin/node-inspector -> /usr/lib/node_modules/node-inspector/bin/inspector.js
/usr/bin/node-debug -> /usr/lib/node_modules/node-inspector/bin/node-debug.js

> v8-debug@0.7.7 install /usr/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.2.1 (node-v51 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "mysun" does not have permission to access the dev dir "/root/.node-gyp/7.2.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/node-inspector/node_modules/v8-debug/.node-gyp"
make: Entering directory '/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build'
make: *** No rule to make target '../.node-gyp/7.2.1/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.8.11-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node" "--module_name=debug" "--module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64"
gyp ERR! cwd /usr/lib/node_modules/node-inspector/node_modules/v8-debug
gyp ERR! node -v v7.2.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node --module_name=debug --module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/node-inspector/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.8.11-1-ARCH
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-inspector/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/node-inspector/node_modules/v8-debug
node-pre-gyp ERR! node -v v7.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node --module_name=debug --module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64' (1)
/usr/lib
└── (empty)

npm ERR! Linux 4.8.11-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "node-inspector"
npm ERR! node v7.2.1
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mysun/npm-debug.log
```

**Comment by pach93** [comment]
same issue on: 
win7 32bits
node7.2.1
npm 4.0.5

**Comment by hahnsolo** [comment]
Anyone have any luck with this ?
