### ISSUE TITLE
[[[ INSTALL ISSUES ]]] 404 node-pre-gyp ERR! Pre-built binaries not found for v8-debug stack Error: Failed to execute

### ISSUE THREAD

**Issue by stefek99** [node-inspector/node-inspector#960]
Potential duplicate of #868 

```
node --version
v7.2.1

npm --version
3.10.9
```

New MacBook delivered yesterday.

First error I'm getting:

```xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance```

So I tried following the instructions here: https://github.com/nodejs/node-gyp/issues/569#issuecomment-255589932

```sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer```

# Output from the console:

```
npm install -g node-inspector


> v8-debug@0.7.7 preinstall /usr/local/lib/node_modules/.staging/v8-debug-5be573b2
> node -e 'process.exit(0)'


> v8-profiler@5.6.5 preinstall /usr/local/lib/node_modules/.staging/v8-profiler-4971d27a
> node -e 'process.exit(0)'

/usr/local/bin/node-debug -> /usr/local/lib/node_modules/node-inspector/bin/node-debug.js
/usr/local/bin/node-inspector -> /usr/local/lib/node_modules/node-inspector/bin/inspector.js

> v8-debug@0.7.7 install /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.2.1 (node-v51 ABI) (falling back to source compile with node-gyp)
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc:38:27: error: too few arguments to function call, expected at least 2, have 1
        v8::Debug::Call(fn);
        ~~~~~~~~~~~~~~~   ^
/Users/ms/.node-gyp/7.2.1/include/node/v8-debug.h:198:3: note: 'Call' declared here
  static MaybeLocal<Value> Call(Local<Context> context,
  ^
../src/debug.cc:46:61: error: too few arguments to function call, single argument 'isolate' was not
      specified
        Isolate* debug_isolate = v8::Debug::GetDebugContext()->GetIsolate();
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/ms/.node-gyp/7.2.1/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
../src/debug.cc:61:67: error: too few arguments to function call, single argument 'isolate' was not
      specified
        Local<Context> debug_context = v8::Debug::GetDebugContext();
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/ms/.node-gyp/7.2.1/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
../src/debug.cc:66:54: error: too few arguments to function call, single argument 'isolate' was not
      specified
          debug_context = v8::Debug::GetDebugContext();
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/ms/.node-gyp/7.2.1/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
4 errors generated.
make: *** [Release/obj.target/debug/src/debug.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/usr/local/Cellar/node/7.2.1/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64/debug.node" "--module_name=debug" "--module_path=/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64"
gyp ERR! cwd /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug
gyp ERR! node -v v7.2.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/7.2.1/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64/debug.node --module_name=debug --module_path=/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/node-inspector/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 16.0.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/7.2.1/bin/node" "/usr/local/lib/node_modules/node-inspector/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug
node-pre-gyp ERR! node -v v7.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/7.2.1/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64/debug.node --module_name=debug --module_path=/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64' (1)
/usr/local/lib
└── (empty)

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/7.2.1/bin/node" "/usr/local/bin/npm" "install" "-g" "node-inspector"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ms/Dropbox/Musafa/dev/tarot/npm-debug.log
npm ERR! code 1
```

**Comment by m-ahmadi** [comment]
The same thing happened to me too.
(failed with both of the following versions)
```
node --version
v7.0.0
v7.2.1

npm --version
3.10.9
4.0.5
```

**Comment by colymore** [comment]
Same error

**Comment by jledun** [comment]
same error here :

node v7.2.1
npm v4.0.5
node-gyp v3.4.0
node-pre-gyp v0.6.32

**Comment by Syzygy24** [comment]
👍

**Comment by Syzygy24** [comment]
Same Issue:
node 4
npm 2.15.6

**Comment by ArthurZ123** [comment]
same issue：
node 7.3.0
npm 3.10.10

**Comment by josephrocca** [comment]
Potentially the same issue here:
Ubuntu 16.04
node v7.3.0
npm v3.10.10

`sudo npm install -g node-inspector`:

```
npm WARN lifecycle v8-debug@0.7.7~preinstall: cannot run in wd %s %s (wd=%s) v8-debug@0.7.7 node -e 'process.exit(0)' /usr/lib/node_modules/.staging/v8-debug-8568d751
npm WARN lifecycle v8-profiler@5.6.5~preinstall: cannot run in wd %s %s (wd=%s) v8-profiler@5.6.5 node -e 'process.exit(0)' /usr/lib/node_modules/.staging/v8-profiler-590bc5bb
/usr/bin/node-inspector -> /usr/lib/node_modules/node-inspector/bin/inspector.js
/usr/bin/node-debug -> /usr/lib/node_modules/node-inspector/bin/node-debug.js

> v8-debug@0.7.7 install /usr/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.3.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/myusername/.node-gyp/7.3.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/node-inspector/node_modules/v8-debug/.node-gyp"
make: Entering directory '/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build'
make: *** No rule to make target '../.node-gyp/7.3.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-57-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node" "--module_name=debug" "--module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64"
gyp ERR! cwd /usr/lib/node_modules/node-inspector/node_modules/v8-debug
gyp ERR! node -v v7.3.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node --module_name=debug --module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/node-inspector/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.0-57-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/node-inspector/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/node-inspector/node_modules/v8-debug
node-pre-gyp ERR! node -v v7.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node --module_name=debug --module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64' (1)
/usr/lib
└── (empty)

npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "node-inspector"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/path/to/my/site/npm-debug.log
npm ERR! code 1

```

[the-npm-debug.txt](https://github.com/node-inspector/node-inspector/files/672545/the-npm-debug.txt)

**Comment by laedanthehuman** [comment]
same issue Here：
node 7.3.0
npm 3.10.10

**Comment by NejcZdovc** [comment]
Same issue:
MacOS 10.12.2
Node 7.2.0
NPM 4.0.3

**Comment by robertaramar** [comment]
Same issue here:
Node 7.2.1
NPM 4.1.1

**Comment by MiquelAdell** [comment]
same here:
    → npm --version
    4.0.5
    
    → node --version
    v7.3.0

I tried to execute with and without super user access on a OS X 10.11.6

I also noticed that the first two errors are:

	node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz
	node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.3.0 (node-v51 ABI) (falling back to source compile with node-gyp)

So it tries to download binaries and, not founding the binaries tries to compile those and fails.

Does anyone have any workaround or temporal fix for that?

Thanks!

**Comment by LeeXun** [comment]
I solved this by 

``
``` sh
cd [projectPath]/node_modules/node-gyp
yarn
cd [projectPath]/
yarn
```
just install it manually!

**Comment by clayzermk1** [comment]
Identical issue to OP.
OS X 10.12.2 (16C67)
node 7.3.0
npm 4.0.5

**Comment by ghamarian** [comment]
Same issue.
 node --version
v7.4.0
 npm --version
4.0.5

**Comment by SherryH** [comment]
Same issue
node --version
v7.4.0
npm --version
4.0.5

**Comment by MehdiRaash** [comment]
same one
node --version
v7.3.0
npm --verion
v4.0.5

**Comment by jaysonesmith** [comment]
Same issue
node --version
v7.4.0
npm --version
4.0.5

**Comment by ivxpingg** [comment]
Same issue
node --version
v7.3.0
npm --verion
v3.10.10

**Comment by AlexPoirier1** [comment]
Same issue here!
npm -- version
4.2.0
node --version
v7.4.0

**Comment by jnwu** [comment]
Same env as @AlexPoirier1 

npm -- version
4.2.0
node --version
v7.4.0

Reverted back to node v6.9.5 and the install worked.

**Comment by Ray285** [comment]
Moving from v7.4.0 back to v6.9.5 resolved the issue for me as well.

**Comment by michelgokan** [comment]
Any solution?

**Comment by michelgokan** [comment]
npm --version
v4.2.0
node --version
v6.9.5

stil the same issue. This time when installing bcrypt. It seems github release download URL changed from : 
https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v48-darwin-x64.tar.gz 
to
https://github.com/kelektiv/node.bcrypt.js/archive/v1.0.2.tar.gz

**Comment by apblack** [comment]
This bug is blocking me too:

```
$ npm install node-inspector

> v8-debug@0.7.7 preinstall /Users/black/node_modules/.staging/v8-debug-2cb7563b
> node -e 'process.exit(0)'


> v8-debug@0.7.7 install /Users/black/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.6.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc:38:27: error: too few arguments to function call, expected at least 2, have 1
        v8::Debug::Call(fn);
        ~~~~~~~~~~~~~~~   ^
/Users/black/.node-gyp/7.6.0/include/node/v8-debug.h:198:3: note: 'Call' declared here
  static MaybeLocal<Value> Call(Local<Context> context,
  ^
../src/debug.cc:46:61: error: too few arguments to function call, single argument 'isolate' was not specified
        Isolate* debug_isolate = v8::Debug::GetDebugContext()->GetIsolate();
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/black/.node-gyp/7.6.0/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
../src/debug.cc:61:67: error: too few arguments to function call, single argument 'isolate' was not specified
        Local<Context> debug_context = v8::Debug::GetDebugContext();
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/black/.node-gyp/7.6.0/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
../src/debug.cc:66:54: error: too few arguments to function call, single argument 'isolate' was not specified
          debug_context = v8::Debug::GetDebugContext();
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/black/.node-gyp/7.6.0/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
4 errors generated.
make: *** [Release/obj.target/debug/src/debug.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/n/versions/node/7.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/n/versions/node/7.6.0/bin/node" "/usr/local/n/versions/node/7.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/black/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64/debug.node" "--module_name=debug" "--module_path=/Users/black/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64"
gyp ERR! cwd /Users/black/node_modules/v8-debug
gyp ERR! node -v v7.6.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/n/versions/node/7.6.0/bin/node /usr/local/n/versions/node/7.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/black/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64/debug.node --module_name=debug --module_path=/Users/black/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/black/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:890:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 15.6.0
node-pre-gyp ERR! command "/usr/local/n/versions/node/7.6.0/bin/node" "/Users/black/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/black/node_modules/v8-debug
node-pre-gyp ERR! node -v v7.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/n/versions/node/7.6.0/bin/node /usr/local/n/versions/node/7.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/black/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64/debug.node --module_name=debug --module_path=/Users/black/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64' (1)
/Users/black
└── (empty)

npm WARN enoent ENOENT: no such file or directory, open '/Users/black/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/black/node_modules/finalhandler/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/black/node_modules/express/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/black/node_modules/mkdirp/package.json'
npm WARN black No description
npm WARN black No repository field.
npm WARN black No README data
npm WARN black No license field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/n/versions/node/7.6.0/bin/node" "/usr/local/bin/npm" "install" "node-inspector"
npm ERR! node v7.6.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/black/.npm/_logs/2017-02-26T17_07_13_496Z-debug.log
$
```
If this is as simple as the download URLs being wrong, could it be fixed quickly, please?

**Comment by m-ahmadi** [comment]
Looks like this project is not maintained anymore.

**Comment by hosenmatz** [comment]
hi all,

i had the same problems installing node-pre-gyp
i managed to install it manually, but with the same error messages after "npm install" in node-red directory

so after checking the error logs i found 

**gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.2.1"**

after **sudo su** i tried again, with the same github (404) download error, but this time the script started the make sequence without any errors

so my problem was just user permissions 
after "npm run build" in the node-red dir i can now start node red.js without any problems

hope that helps

**Comment by bbbenji** [comment]
I fixed this issue by doing the following 

```
sudo chmod -R 777 /root
sudo npm install -g node-inspector
sudo chmod -R 700 /root
```

**Comment by lifenautjoe** [comment]
@bbbenji seemed to work but when trying to run node-debug `my-file.js` I get 
```
module.js:487
    throw err;
    ^

Error: Cannot find module '_debugger'
```

**Comment by e-beach** [comment]
I had this issue and just used https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27, as mentioned in the README.

**Comment by m-ahmadi** [comment]
This is my baby now:

node --inspect-brk

( chrome:inspect  -->  Open dedicated DevTools for Node )

**Comment by raviverma89** [comment]
Guys,

**Comment by sebgam** [comment]
cambiar a la versión 6.11 me soluciono el problema

**Comment by PaulsBebris** [comment]
1. on OSX chmod -R user:admin(do not use staff !!!) /usr/local/lib/node_modules/node-inspector/node_modules
2. install as normal user. no sudo neede.

**Comment by kamaral75** [comment]
We had the same issue. To solve it, we upgraded the version of Node.

**Comment by tinhnqjp** [comment]
Same error:
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.3.0 (node-v51 ABI) (falling back to source compile with node-gyp) 

I try and OK:
npm install -g node-inspector@0.7.5

**Comment by lorenschwartz** [comment]
Any solution to this? I'm having the same issues.

**Comment by fenix011** [comment]
I'm having the same issue

```
node --version : v9.8.0
npm version 5.7.1
```
but just updating npm 

```
Update available 5.6.0 → 5.7.1    │
Run npm i npm to update  
```

& re-running yarn command it works fine ... now

FYI

**Comment by dmuzizian** [comment]
remove dependencies "tulind" from package.json.

Save, then manual install npm + tulip like this : `npm install tulind --build-from-source`

this work for me.

**Comment by rdamborsky** [comment]
installing "latest" node-inspector didn't cut it for me. I had to install the 0.7.5 version, as mentioned in above comments, to move on:

`npm install -g node-inspector@0.7.5`

**Comment by morganwilde** [comment]
I'm using `nvm` to manage my `node` versions on macOS, but it wasn't setup in my shell correctly, so it defaulted to native `node` version (`10.0.0` in this case) and after switching back to `9.11.1` I no longer have that error.

For me, it was due to the latest `node` version.

**Comment by IzaGz** [comment]
@morganwilde  i am confirming, i use macOS 10.13.4 sierra. NVM installed node 10, trying to npm i- got error
`4 warnings and 1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/z/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/Users/z/.nvm/versions/node/v10.0.0/bin/node" "/Users/z/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/z/project/catch_cronposts/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/z/project/catch_cronposts/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp ERR! cwd /Users/z/project/catch_cronposts/node_modules/fsevents
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/z/.nvm/versions/node/v10.0.0/bin/node /Users/z/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/z/project/catch_cronposts/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/z/project/catch_cronposts/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/z/project/catch_cronposts/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:947:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
node-pre-gyp ERR! System Darwin 17.5.0
node-pre-gyp ERR! command "/Users/z/.nvm/versions/node/v10.0.0/bin/node" "/Users/z/project/catch_cronposts/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/z/project/catch_cronposts/node_modules/fsevents
node-pre-gyp ERR! node -v v10.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/Users/z/.nvm/versions/node/v10.0.0/bin/node /Users/z/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/z/project/catch_cronposts/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/z/project/catch_cronposts/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)

> sse4_crc32@5.1.1 install /Users/z/project/catch_cronposts/node_modules/sse4_crc32
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/crc32c_sse42/src/crc32c_sse42.o
  LIBTOOL-STATIC Release/crc32c_sse42.a
  CXX(target) Release/obj.target/sse4_crc32/src/crc32c.o
`

**Comment by StuRuby** [comment]
same issues

**Comment by LeNguyenMinhTan** [comment]
same issues

**Comment by Dragon160** [comment]
Same issue here:

node --version
v9.8.0
npm --version
5.6.0

**Comment by AndrewRayCode** [comment]
Seeing the same thing, and just as a warning,

**Never** do what @bbbenji suggests. **Never** modify the permissions of root folders. **Never** sudo install with package managers (npm or otherwise). And **never** install `-g` for project-specific dependencies.

This is what "fixed" it for me, but I don't know how much of it was required

Remove the existing node-gyp folder [from this comment](https://github.com/nodejs/node-gyp/issues/809#issuecomment-155019383)
```
rm -r ~/.node-gyp
```

Update npm (why not?)
```
npm install npm@latest -g
```

Remove existing `node_modules/`
```
rm -r node_modules
```

Remove the existing `package-json.lock` (or `yarn.lock` if using yarn) from [this comment](https://github.com/strongloop/fsevents/issues/226#issuecomment-399698265). An older version of fsevent in the lockfile could be causing this error
```
rm package-json.lock
```

And then reinstalling
```
npm install
```

**Comment by edmondchui** [comment]
> rm package-json.lock

I think it should be 

> rm package-lock.json

**Comment by percentcent** [comment]
I came across the same error. I tried this to fix it.
---npm install fsevents
---npm audit fix

**Comment by cnssr4bb1t** [comment]
this solved my problem:
$ npm install fsevents

**Comment by khadkaPratik** [comment]
Try to downgrading node version since some packages are not supported by newer version .
It worked for me this time .

**Comment by lben** [comment]
I updated my npm version and since I have the 404 and 403 errors on node-pre-gyp which seems to be part of grpc which in turn I was using for my firebase project what I did was the following:

1. Update npm
2. rm -rf node_modules
3. rm package-lock.json
4. remove manually my firebase (and firebase/firestore in my case) dependencies from package.json (I think you should remove your firebase or grpc or similar dependencies)
5. npm install --save firebase
6. npm install
7. (optional) npm audit fix

After that, I was able to finally run my project as always. 

In my case it seems that the firestore package was drastically updated including its dependencies

I hope it helps someone else.

**Comment by maimai123** [comment]
use yarn！！！
