### ISSUE TITLE
Error: listen EADDRINUSE :::5858

### ISSUE THREAD

**Issue by adamzerner** [node-inspector/node-inspector#963]
Steps to reproduce:

1. Run `node-debug`.
2. Quit using `ctrl` + `c`.
3. Run `node-debug`.
4. Observe error.

Console output:

```
projects/10 » node-debug Compiler/main.js ArrayTest
Node Inspector v0.12.8
Visit http://127.0.0.1:8080/?port=5858 to start debugging.
Debugging `Compiler/main.js`

Debugger listening on port 5858
^C%                                                                                                                                                                                  projects/10 » node-debug Compiler/main.js ArrayTest
Node Inspector v0.12.8
Visit http://127.0.0.1:8080/?port=5858 to start debugging.
Debugging `Compiler/main.js`

Error: listen EADDRINUSE :::5858
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Agent.Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Agent.Server.listen (net.js:1366:5)
    at Object.start (_debug_agent.js:21:9)
    at startup (node.js:70:44)
    at node.js:968:3
```

**Comment by thePedroPaulino** [comment]
Hello @adamzerner 

I`m getting the same problem here.

Run on the terminal: 
**$ sudo lsof -i:5858**

You`ll find the process that is using the port.

And the, kill the process by running:
**$ sudo kill 0000**

Where the 0000 is the number of the process that is using the :5858 port.

Just warning: For me , also running Mac , it solved half of the problem, because I `m still unable to run node-debug without getting an error.

**Comment by Aryk** [comment]
Just tried that, solved my problem, thanks!

**Comment by tylik1** [comment]
`sudo killall -9 node`
This is how i solve it on MAC
