### ISSUE TITLE
InjectorClient.js:111 and no browser matching.

### ISSUE THREAD

**Issue by slopez15** [node-inspector/node-inspector#979]
$ node-debug bot.js
Node Inspector v0.12.8
Visit http://127.0.0.1:8080/?port=5858 to start debugging.
Debugging `bot.js`

Debugger listening on [::]:5858
No browser matching [chrome,chromium,opera] found in the system! If this is not true, submit a bug report on https://github.com/benderjs/browser-launcher2
Please open the URL manually in Chrome/Chromium/Opera or similar browser
C:\Users\user\AppData\Roaming\npm\node_modules\node-inspector\lib\InjectorClient.js:111
      cb(error, NM[0].ref);
                     ^

TypeError: Cannot read property 'ref' of undefined
    at InjectorClient.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\node-inspector\lib\InjectorClient.js:111:22)
    at C:\Users\user\AppData\Roaming\npm\node_modules\node-inspector\lib\DebuggerClient.js:121:7
    at Object.value (C:\Users\user\AppData\Roaming\npm\node_modules\node-inspector\lib\callback.js:23:20)
    at Debugger._processResponse (C:\Users\user\AppData\Roaming\npm\node_modules\node-inspector\lib\debugger.js:95:21)
    at Protocol.execute (_debugger.js:121:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)

**Comment by hustxiaoc** [comment]
Fixed in `node-inspector@1.0.0`
