### ISSUE TITLE
Error on starting

### ISSUE THREAD

**Issue by zwhitchcox** [node-inspector/node-inspector#981]
```
Node Inspector v0.12.8
Visit http://127.0.0.1:8080/?port=5858 to start debugging.
Debugging `/usr/local/bin/mocha`

Debugger listening on 127.0.0.1:5858
No browser matching [chrome,chromium,opera] found in the system! If this is not true, submit a bug report on https://github.com/benderjs/browser-launcher2
Please open the URL manually in Chrome/Chromium/Opera or similar browser
/usr/local/lib/node_modules/node-inspector/lib/InjectorClient.js:111
      cb(error, NM[0].ref);
                     ^

TypeError: Cannot read property 'ref' of undefined
    at InjectorClient.<anonymous> (/usr/local/lib/node_modules/node-inspector/lib/InjectorClient.js:111:22)
    at /usr/local/lib/node_modules/node-inspector/lib/DebuggerClient.js:121:7
    at Object.value (/usr/local/lib/node_modules/node-inspector/lib/callback.js:23:20)
    at Debugger._processResponse (/usr/local/lib/node_modules/node-inspector/lib/debugger.js:95:21)
    at Protocol.execute (_debugger.js:121:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

**Comment by mx601595686** [comment]
this problem has been fixed, but haven't update. you can fix it by youself .# 2e5309f75099753740c4567e17fd79ee27885d71
