### ISSUE TITLE
In node v7.7.1 . error on starting.

### ISSUE THREAD

**Issue by mx601595686** [node-inspector/node-inspector#982]
if code don`t has 'debugger' statement, on starting will occur a error.
```
Node Inspector v0.12.8
Visit http://127.0.0.1:8080/?port=5858 to start debugging.
Debugging `test.js`

(node:4180) DeprecationWarning: node --debug is deprecated. Please use node --inspect instead.
Debugger listening on 127.0.0.1:5858
C:\Users\HASEE\AppData\Roaming\npm\node_modules\node-inspector\lib\DebuggerClient.js:161
      done(err, JSON.parse(result.value));
                                 ^

TypeError: Cannot read property 'value' of undefined
    at _handleEvaluateResponse (C:\Users\HASEE\AppData\Roaming\npm\node_modules\node-inspector\lib\DebuggerClient.js:161:34)
    at C:\Users\HASEE\AppData\Roaming\npm\node_modules\node-inspector\lib\DebuggerClient.js:116:7
    at Object.value (C:\Users\HASEE\AppData\Roaming\npm\node_modules\node-inspector\lib\callback.js:23:20)
    at Debugger._processResponse (C:\Users\HASEE\AppData\Roaming\npm\node_modules\node-inspector\lib\debugger.js:95:21)
    at Protocol.execute (_debugger.js:125:14)
    at Protocol._newRes (_debugger.js:79:8)
    at Protocol.execute (_debugger.js:127:14)
    at Protocol._newRes (_debugger.js:79:8)
    at Protocol.execute (_debugger.js:127:14)
    at Protocol._newRes (_debugger.js:79:8)
events.js:4735: Uncaught Error: read ECONNRESET

```

**Comment by hustxiaoc** [comment]
Try `node-inspector@1.0.0` please.
