### ISSUE TITLE
Unable to `nam install -g node-inspector` for latest node

### ISSUE THREAD

**Issue by shaunstanislaus** [node-inspector/node-inspector#986]
```bash
shaun:~/ $ npm install -g node-inspector                    [16:53:50]

> v8-debug@0.7.7 preinstall /usr/local/lib/node_modules/.staging/v8-debug-5be573b2
> node -e 'process.exit(0)'


> v8-profiler@5.6.5 preinstall /usr/local/lib/node_modules/.staging/v8-profiler-4971d27a
> node -e 'process.exit(0)'

/usr/local/bin/node-debug -> /usr/local/lib/node_modules/node-inspector/bin/node-debug.js
/usr/local/bin/node-inspector -> /usr/local/lib/node_modules/node-inspector/bin/inspector.js

> v8-debug@0.7.7 install /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.7.2 (node-v51 ABI) (falling back to source compile with node-gyp)
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc:38:27: error: too few arguments to function call,
      expected at least 2, have 1
        v8::Debug::Call(fn);
        ~~~~~~~~~~~~~~~   ^
/Users/shaun/.node-gyp/7.7.2/include/node/v8-debug.h:198:3: note:
      'Call' declared here
  static MaybeLocal<Value> Call(Local<Context> context,
  ^
../src/debug.cc:46:61: error: too few arguments to function call,
      single argument 'isolate' was not specified
        Isolate* debug_isolate = v8::Debug::GetDebugContext()->GetIsola...
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/shaun/.node-gyp/7.7.2/include/node/v8-debug.h:248:3: note:
      'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
../src/debug.cc:61:67: error: too few arguments to function call,
      single argument 'isolate' was not specified
        Local<Context> debug_context = v8::Debug::GetDebugContext();
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/shaun/.node-gyp/7.7.2/include/node/v8-debug.h:248:3: note:
      'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
../src/debug.cc:66:54: error: too few arguments to function call,
      single argument 'isolate' was not specified
          debug_context = v8::Debug::GetDebugContext();
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/shaun/.node-gyp/7.7.2/include/node/v8-debug.h:248:3: note:
      'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
4 errors generated.
make: *** [Release/obj.target/debug/src/debug.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/Cellar/node/7.7.2/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64/debug.node" "--module_name=debug" "--module_path=/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64"
gyp ERR! cwd /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug
gyp ERR! node -v v7.7.2
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/7.7.2/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64/debug.node --module_name=debug --module_path=/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/node-inspector/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 15.6.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/7.7.2/bin/node" "/usr/local/lib/node_modules/node-inspector/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug
node-pre-gyp ERR! node -v v7.7.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/7.7.2/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64/debug.node --module_name=debug --module_path=/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64' (1)
/usr/local/lib
└── (empty)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shaun/.npm/_logs/2017-03-12T08_54_11_433Z-debug.log
```

**Comment by system65** [comment]
same issue here.

**Comment by PJLindsay** [comment]
Same

**Comment by cyc115** [comment]
```
➜  node_modules git:(master) ✗ sudo npm install -g babel-node-debug
npm WARN lifecycle v8-debug@0.7.7~preinstall: cannot run in wd %s %s (wd=%s) v8-debug@0.7.7 node -e 'process.exit(0)' /usr/local/lib/node_modules/.staging/v8-debug-feb4a37b
npm WARN lifecycle v8-profiler@5.6.5~preinstall: cannot run in wd %s %s (wd=%s) v8-profiler@5.6.5 node -e 'process.exit(0)' /usr/local/lib/node_modules/.staging/v8-profiler-0a76992b
/usr/local/bin/bode-debug -> /usr/local/lib/node_modules/babel-node-debug/bin/bode-debug.js
/usr/local/bin/babel-node-debug -> /usr/local/lib/node_modules/babel-node-debug/bin/bode-debug.js

> v8-debug@0.7.7 install /usr/local/lib/node_modules/babel-node-debug/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.4.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/yuechuan/.node-gyp/7.4.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/babel-node-debug/node_modules/v8-debug/.node-gyp"
make: Entering directory `/usr/local/lib/node_modules/babel-node-debug/node_modules/v8-debug/build'
make: *** No rule to make target `../.node-gyp/7.4.0/include/node/common.gypi', needed by `Makefile'.  Stop.
make: Leaving directory `/usr/local/lib/node_modules/babel-node-debug/node_modules/v8-debug/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-57-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/babel-node-debug/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node" "--module_name=debug" "--module_path=/usr/local/lib/node_modules/babel-node-debug/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64"
gyp ERR! cwd /usr/local/lib/node_modules/babel-node-debug/node_modules/v8-debug
gyp ERR! node -v v7.4.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/babel-node-debug/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node --module_name=debug --module_path=/usr/local/lib/node_modules/babel-node-debug/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/babel-node-debug/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.0-57-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/babel-node-debug/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/babel-node-debug/node_modules/v8-debug
node-pre-gyp ERR! node -v v7.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/babel-node-debug/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node --module_name=debug --module_path=/usr/local/lib/node_modules/babel-node-debug/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64' (1)
/usr/local/lib
└── (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/babel-node-debug/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "babel-node-debug"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/yuechuan/Github/distiller/node_modules/npm-debug.log
```

**Comment by elchado** [comment]
samehere!

**Comment by elchado** [comment]
Make sure guys you are not running the app in another tab. close the terminal and also read the documentation of the app. first install node-inspector running in terminal : node-inspector

**Comment by buschtoens** [comment]
@elchado 

> Make sure guys you are not running the app in another tab. close the terminal and also read the documentation of the app. first install node-inspector running in terminal : node-inspector

wat? This commment has nothing to do with the problem at hand. You must be confusing something.

**Comment by ImaCrea** [comment]
same problem here 😞

**Comment by keita-nishimoto** [comment]
node -v : v7.7.3
yarn --version : 0.21.3

```
yarn install v0.21.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/4] ⠄ v8-debug: make: *** [Release/obj.target/debug/src/debug.o] Error 1
[2/4] ⠄ v8-profiler: CXX(target) Release/obj.target/profiler/src/profiler.o
[-/4] ⠄ waiting...
[-/4] ⠄ waiting...
error /Users/kogakeita/git/aws-serverless-prototype/node_modules/v8-debug: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-pre-gyp install --fallback-to-build
Directory: /Users/kogakeita/git/aws-serverless-prototype/node_modules/v8-debug
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.33
node-pre-gyp info using node@7.7.3 | darwin | x64
node-pre-gyp info check checked for "/Users/kogakeita/git/aws-serverless-prototype/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64/debug.node" (not found)
node-pre-gyp http GET https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz
node-pre-gyp http 404 https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.7.3 (node-v51 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.7.3 | darwin | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.7.3 | darwin | x64
gyp http GET https://nodejs.org/download/release/v7.7.3/node-v7.7.3-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v7.7.3/node-v7.7.3-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v7.7.3/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v7.7.3/SHASUMS256.txt
gyp info spawn /Users/kogakeita/.pyenv/shims/python2
gyp info spawn args [ '/Users/kogakeita/.nodebrew/node/v7.7.3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/kogakeita/git/aws-serverless-prototype/node_modules/v8-debug/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/kogakeita/.nodebrew/node/v7.7.3/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/kogakeita/.node-gyp/7.7.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/kogakeita/.node-gyp/7.7.3',
gyp info spawn args   '-Dnode_gyp_dir=/Users/kogakeita/.nodebrew/node/v7.7.3/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/kogakeita/git/aws-serverless-prototype/node_modules/v8-debug',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.7.3 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc:38:27: error: too few arguments to function call, expected at least 2, have 1
        v8::Debug::Call(fn);
        ~~~~~~~~~~~~~~~   ^
/Users/kogakeita/.node-gyp/7.7.3/include/node/v8-debug.h:198:3: note: 'Call' declared here
  static MaybeLocal<Value> Call(Local<Context> context,
  ^
../src/debug.cc:46:61: error: too few arguments to function call, single argument 'isolate' was not specified
        Isolate* debug_isolate = v8::Debug::GetDebugContext()->GetIsolate();
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/kogakeita/.node-gyp/7.7.3/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
../src/debug.cc:61:67: error: too few arguments to function call, single argument 'isolate' was not specified
        Local<Context> debug_context = v8::Debug::GetDebugContext();
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/kogakeita/.node-gyp/7.7.3/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
../src/debug.cc:66:54: error: too few arguments to function call, single argument 'isolate' was not specified
          debug_context = v8::Debug::GetDebugContext();
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/kogakeita/.node-gyp/7.7.3/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
4 errors generated.
make: *** [Release/obj.target/debug/src/debug.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/kogakeita/.nodebrew/node/v7.7.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Users/kogakeita/.nodebrew/node/v7.7.3/bin/node" "/Users/kogakeita/.nodebrew/node/v7.7.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/kogakeita/git/aws-serverless-prototype/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64/debug.node" "--module_name=debug" "--module_path=/Users/kogakeita/git/aws-serverless-prototype/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64"
gyp ERR! cwd /Users/kogakeita/git/aws-serverless-prototype/node_modules/v8-debug
gyp ERR! node -v v7.7.3
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/kogakeita/.nodebrew/node/v7.7.3/bin/node /Users/kogakeita/.nodebrew/node/v7.7.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/kogakeita/git/aws-serverless-prototype/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64/debug.node --module_name=debug --module_path=/Users/kogakeita/git/aws-serverless-prototype/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/kogakeita/git/aws-serverless-prototype/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 15.6.0
node-pre-gyp ERR! command "/Users/kogakeita/.nodebrew/node/v7.7.3/bin/node" "/Users/kogakeita/git/aws-serverless-prototype/node_modules/v8-debug/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/kogakeita/git/aws-serverless-prototype/node_modules/v8-debug
node-pre-gyp ERR! node -v v7.7.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp ERR! not ok
Failed to execute '/Users/kogakeita/.nodebrew/node/v7.7.3/bin/node /Users/kogakeita/.nodebrew/node/v7.7.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/kogakeita/git/aws-serverless-prototype/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64/debug.node --module_name=debug --module_path=/Users/kogakeita/git/aws-serverless-prototype/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64' (1)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

This problem did not occur in Node v6.10.0.

**Comment by buschtoens** [comment]
Before submitting a new error log, please verify that it actually differs from the others in terms of the compiler errors.

Basically what's happening: yarn / npm execute `node-pre-gyp install --fallback-to-build` after downloading the package itself. This command attempts to download pre-built binaries from S3:

```
node-pre-gyp http GET https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz
node-pre-gyp http 404 https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz
```

These pre-built binaries do not exist yet for the current Node version:

```
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.7.3 (node-v51 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz
gyp info it worked if it ends with ok
```

That's why `node-gyp` attempts to build the binaries itself (`--fallback-to-build`) via `make`. But it ulitmately fails to do so:

```
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc:38:27: error: too few arguments to function call, expected at least 2, have 1
        v8::Debug::Call(fn);
        ~~~~~~~~~~~~~~~   ^
/Users/kogakeita/.node-gyp/7.7.3/include/node/v8-debug.h:198:3: note: 'Call' declared here
  static MaybeLocal<Value> Call(Local<Context> context,
  ^
../src/debug.cc:46:61: error: too few arguments to function call, single argument 'isolate' was not specified
        Isolate* debug_isolate = v8::Debug::GetDebugContext()->GetIsolate();
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/kogakeita/.node-gyp/7.7.3/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
../src/debug.cc:61:67: error: too few arguments to function call, single argument 'isolate' was not specified
        Local<Context> debug_context = v8::Debug::GetDebugContext();
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/kogakeita/.node-gyp/7.7.3/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
../src/debug.cc:66:54: error: too few arguments to function call, single argument 'isolate' was not specified
          debug_context = v8::Debug::GetDebugContext();
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/kogakeita/.node-gyp/7.7.3/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
4 errors generated.
```

This is because the source files of this package have not been updated yet. 4 functions of `v8-debug.h` are called with no or too few arguments.

I'm don't habe enough expertise with the source code of V8, otherwise I'd submit a PR.

**Comment by buschtoens** [comment]
@cyc115 Your error is a bit different. You're running `npm` as root and get file permission errors, weirdly enough. Try installing `babel-node-debug` as a non-root user or switch to a complete root shell with `sudo -s` and then `cd`.

You'll then get the same error as everybody else in this issue.

There's no suitable pre-built binary:
```
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.4.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
```

That's why `node-gyp` attempts to build them itself. But it fails accessing the desired temporary working directory, so it attempts to switch to a different one:
```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/yuechuan/.node-gyp/7.4.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/babel-node-debug/node_modules/v8-debug/.node-gyp"
```

This one's missing `node-gyp` configuration files though:

```
make: Entering directory `/usr/local/lib/node_modules/babel-node-debug/node_modules/v8-debug/build'
make: *** No rule to make target `../.node-gyp/7.4.0/include/node/common.gypi', needed by `Makefile'.
```

**Comment by babinc** [comment]
Same here...

**Comment by AndreTheHunter** [comment]
Same here

**Comment by think2011** [comment]
Same here

**Comment by buschtoens** [comment]
Please do not post "same here" comments. You're spamming everybody's inboxes. Please upvote the original comment instead.

Before posting a comment, please ask yourself: do I have something valuable to add or has this been said before?

Thank you 😄

**Comment by hustxiaoc** [comment]
Try `node-inspector@1.0.0` please.

**Comment by buschtoens** [comment]
Works like a charm. Thanks! :heart:

**Comment by maifs** [comment]
I am facing the same issue .
what do i need to fix it ?
Kindly guide. thank you.

https://stackoverflow.com/questions/44462901/how-to-install-latest-angular-cli-using-visual-studio-2017-node-js-interactive-w

**Comment by cyc115** [comment]
@buschtoens Thanks for the tip :). You are absolutely correct about running as root.

**Comment by maifs** [comment]
> .npm [On.Store.UI] install -g @angular/cli
C:\Users\child\AppData\Roaming\npm\ng -> C:\Users\child\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
> node-sass@4.5.3 install C:\Users\child\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass
> node scripts/install.js
Cached binary found at C:\Users\child\AppData\Roaming\npm-cache\node-sass\4.5.3\win32-x64-48_binding.node
> node-sass@4.5.3 postinstall C:\Users\child\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass
> node scripts/build.js
Binary found at C:\Users\child\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\vendor\win32-x64-48\binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-pre-gyp@0.6.33 (node_modules\@angular\cli\node_modules\fsevents\node_modules\node-pre-gyp):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\child\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\fsevents\node_modules\node-pre-gyp' -> 'C:\Users\child\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\fsevents\node_modules\.node-pre-gyp.DELETE'
+ @angular/cli@1.1.1
added 823 packages and updated 1 package in 167.125s
[On.Store.UI] install -g @angular/cli successfully completed
> .npm [On.Store.UI] install -g @angular/cli
C:\Users\child\AppData\Roaming\npm\ng -> C:\Users\child\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
> fsevents@1.1.1 install C:\Users\child\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\fsevents
> node install
+ @angular/cli@1.1.1
added 120 packages, removed 1 package and updated 1 package in 83.667s
[On.Store.UI] install -g @angular/cli successfully completed
>

**Comment by maifs** [comment]
my visual code compiler errors are mentioned below :

    Severity    Code    Description Project File    Line    Suppression State
Error   TS2304  Cannot find name 'Promise'. On.Store.UI (tsconfig project)  L:\ESaleStore\On.Store.UI\src\On.Store.UI\node_modules\@angular\common\src\location\platform_location.d.ts  51  Active
Error   TS2304  Cannot find name 'Promise'. On.Store.UI (tsconfig project)  L:\ESaleStore\On.Store.UI\src\On.Store.UI\node_modules\@angular\common\src\location\platform_location.d.ts  51  Active
Error   TS2304  Cannot find name 'Promise'. On.Store.UI (tsconfig project)  L:\ESaleStore\On.Store.UI\src\On.Store.UI\node_modules\@angular\common\src\pipes\async_pipe.d.ts    45  Active
Error   TS2304  Cannot find name 'Promise'. On.Store.UI (tsconfig project)  L:\ESaleStore\On.Store.UI\src\On.Store.UI\node_modules\@angular\compiler\src\aot\compiler_host.d.ts 25  Active
Error   TS2339  Property 'find' does not exist on type 'BillingPackage[]'.  On.Store.UI (ts
