### ISSUE TITLE
node-inspector error on install in node v7.7.4 

### ISSUE THREAD

**Issue by trojanliu** [node-inspector/node-inspector#992]
trojan$ sudo npm install node-inspector -g
Password:
npm WARN lifecycle v8-debug@0.7.7preinstall: cannot run in wd %s %s (wd=%s) v8-debug@0.7.7 node -e 'process.exit(0)' /Users/trojan/.nvm/versions/node/v7.7.4/lib/node_modules/.staging/v8-debug-89dbfbca
npm WARN lifecycle v8-profiler@5.6.5preinstall: cannot run in wd %s %s (wd=%s) v8-profiler@5.6.5 node -e 'process.exit(0)' /Users/trojan/.nvm/versions/node/v7.7.4/lib/node_modules/.staging/v8-profiler-64c78e35
/Users/trojan/.nvm/versions/node/v7.7.4/bin/node-inspector -> /Users/trojan/.nvm/versions/node/v7.7.4/lib/node_modules/node-inspector/bin/inspector.js
/Users/trojan/.nvm/versions/node/v7.7.4/bin/node-debug -> /Users/trojan/.nvm/versions/node/v7.7.4/lib/node_modules/node-inspector/bin/node-debug.js

v8-debug@0.7.7 install /Users/trojan/.nvm/versions/node/v7.7.4/lib/node_modules/node-inspector/node_modules/v8-debug
node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.7.4 (node-v51 ABI) (falling back to source compile with node-gyp)
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc:38:27: error: too few arguments to function call, expected at least 2, have 1
v8::Debug::Call(fn);
~~~~~~~~~~~~~~~ ^
/Users/trojan/.node-gyp/7.7.4/include/node/v8-debug.h:198:3: note: 'Call' declared here
static MaybeLocal Call(Local context,
^
../src/debug.cc:46:61: error: too few arguments to function call, single argument 'isolate' was not specified
Isolate* debug_isolate = v8::Debug::GetDebugContext()->GetIsolate();
~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/trojan/.node-gyp/7.7.4/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
static Local GetDebugContext(Isolate* isolate);
^
../src/debug.cc:61:67: error: too few arguments to function call, single argument 'isolate' was not specified
Local debug_context = v8::Debug::GetDebugContext();
~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/trojan/.node-gyp/7.7.4/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
static Local GetDebugContext(Isolate* isolate);
^
../src/debug.cc:66:54: error: too few arguments to function call, single argument 'isolate' was not specified
debug_context = v8::Debug::GetDebugContext();
~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/trojan/.node-gyp/7.7.4/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
static Local GetDebugContext(Isolate* isolate);
^
4 errors generated.
make: *** [Release/obj.target/debug/src/debug.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/Users/trojan/.nvm/versions/node/v7.7.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack at emitTwo (events.js:106:13)
gyp ERR! stack at ChildProcess.emit (events.js:194:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.4.0

**Comment by dwicao** [comment]
I'm also getting this error for node v7.6.0 and npm v4.1.2

**Comment by hustxiaoc** [comment]
Please try `node-inspector@1.0.0`.

**Comment by johntran** [comment]
I got an error running `npm install node-inspector`

```
> v8-debug@0.7.7 preinstall /Users/johntran/hopecommerce-proto/node_modules/.staging/v8-debug-8deed24d
> node -e 'process.exit(0)'

npm WARN prefer global node-inspector@1.0.0 should be installed with -g

> v8-debug@0.7.7 install /Users/johntran/hopecommerce-proto/node_modules/babel-node-debug/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.7.1 (node-v51 ABI) (falling back to source compile with node-gyp)
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc:38:27: error: too few arguments to function call, expected at least 2, have 1
        v8::Debug::Call(fn);
        ~~~~~~~~~~~~~~~   ^
/Users/johntran/.node-gyp/7.7.1/include/node/v8-debug.h:198:3: note: 'Call' declared here
  static MaybeLocal<Value> Call(Local<Context> context,
  ^
../src/debug.cc:46:61: error: too few arguments to function call, single argument 'isolate' was not specified
        Isolate* debug_isolate = v8::Debug::GetDebugContext()->GetIsolate();
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/johntran/.node-gyp/7.7.1/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
../src/debug.cc:61:67: error: too few arguments to function call, single argument 'isolate' was not specified
        Local<Context> debug_context = v8::Debug::GetDebugContext();
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/johntran/.node-gyp/7.7.1/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
../src/debug.cc:66:54: error: too few arguments to function call, single argument 'isolate' was not specified
          debug_context = v8::Debug::GetDebugContext();
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/johntran/.node-gyp/7.7.1/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
4 errors generated.
make: *** [Release/obj.target/debug/src/debug.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/johntran/.nvm/versions/node/v7.7.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.3.0
gyp ERR! command "/Users/johntran/.nvm/versions/node/v7.7.1/bin/node" "/Users/johntran/.nvm/versions/node/v7.7.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/johntran/hopecommerce-proto/node_modules/babel-node-debug/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64/debug.node" "--module_name=debug" "--module_path=/Users/johntran/hopecommerce-proto/node_modules/babel-node-debug/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64"
gyp ERR! cwd /Users/johntran/hopecommerce-proto/node_modules/babel-node-debug/node_modules/v8-debug
gyp ERR! node -v v7.7.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/johntran/.nvm/versions/node/v7.7.1/bin/node /Users/johntran/.nvm/versions/node/v7.7.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/johntran/hopecommerce-proto/node_modules/babel-node-debug/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64/debug.node --module_name=debug --module_path=/Users/johntran/hopecommerce-proto/node_modules/babel-node-debug/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/johntran/.nvm/versions/node/v7.7.1/lib/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 16.3.0
node-pre-gyp ERR! command "/Users/johntran/.nvm/versions/node/v7.7.1/bin/node" "/Users/johntran/.nvm/versions/node/v7.7.1/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/johntran/hopecommerce-proto/node_modules/babel-node-debug/node_modules/v8-debug
node-pre-gyp ERR! node -v v7.7.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.34
node-pre-gyp ERR! not ok
Failed to execute '/Users/johntran/.nvm/versions/node/v7.7.1/bin/node /Users/johntran/.nvm/versions/node/v7.7.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/johntran/hopecommerce-proto/node_modules/babel-node-debug/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64/debug.node --module_name=debug --module_path=/Users/johntran/hopecommerce-proto/node_modules/babel-node-debug/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64' (1)
HopeCommerce@0.0.8 /Users/johntran/hopecommerce-proto
├── UNMET PEER DEPENDENCY babel-relay-plugin@0.11.0
├── UNMET PEER DEPENDENCY formsy-react@0.19.2
├── UNMET PEER DEPENDENCY material-ui@0.17.1
└── node-inspector@1.0.0

npm WARN formsy-material-ui@0.5.5 requires a peer of formsy-react@^0.18.0 but none was installed.
npm WARN formsy-material-ui@0.5.5 requires a peer of material-ui@^0.16.0 but none was installed.
npm WARN react-relay@0.10.0 requires a peer of babel-relay-plugin@0.10.0 but none was installed.
npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/johntran/.nvm/versions/node/v7.7.1/bin/node" "/Users/johntran/.nvm/versions/node/v7.7.1/bin/npm" "install" "--save-dev" "node-inspector"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
```

Seems like the error is due to an AWS download failing?

`node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz`

Node version: 7.7.1

**Comment by hustxiaoc** [comment]
@johntran , you're not installing the latest version which is `1.0.0` and  v8-debug should be `1.0.0`.
